import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";

// Every GLB here is generated by a committed, deterministic Blender script
// (scripts/blender/<name>.py) and passes the harness inspect_asset hard gate
// Y-up. Measured tri / KB counts, refreshed by running each script and
// `du -k public/models/*.glb`:
//
// | asset                     | tris  | KB  | budget tris | budget KB |
// |---------------------------|-------|-----|-------------|-----------|
// | studio-orbit               | 14732 | 206 | 30000       | 337       |
// | signal-marker               |    24 |   2 |   300       |  20       |
// | skills-core                 |   140 |  10 |  1200       |  30       |
// | blueprint-instrument        |  1960 |  60 |  5000       | 150       |
// | chess-handoff-marker        |   456 |  11 |  1000       |  15       |
// | world-monuments (4 nodes)   |   138 |  14 |  3200       |  60       |
// | kmp-foundation-keystone     |   120 |   9 |   800       |  20       |

export const MODELS = {
  "studio-orbit": "/models/studio-orbit.glb",
  "signal-marker": "/models/signal-marker.glb",
  "skills-core": "/models/skills-core.glb",
  "blueprint-instrument": "/models/blueprint-instrument.glb",
  "chess-handoff-marker": "/models/chess-handoff-marker.glb",
  "world-monuments": "/models/world-monuments.glb",
  "kmp-foundation-keystone": "/models/kmp-foundation-keystone.glb",
} as const;

export type ModelName = keyof typeof MODELS;

/** useLoader caches by URL, so mounting the same model in several scenes
 * (signal-marker in StoryMapScene, FoundationGraphScene and SkillsOrbitScene)
 * fetches and parses the GLB once. */
export function useStudioModel(name: ModelName) {
  return useLoader(GLTFLoader, MODELS[name]);
}
