import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { MeshoptDecoder } from "three/addons/libs/meshopt_decoder.module.js";

// Every GLB here is generated by a committed, deterministic Blender script
// (scripts/blender/<name>.py) and passes the harness inspect_asset hard
// gate. Y-up. Five of the seven are meshopt-compressed by that same script
// via `npx gltfpack -cc -kn` (wow-pass, dev-only, never added to
// package.json): every asset mounted through useStudioModel below, which
// registers the decoder. studio-orbit and signal-marker are exported raw
// (no gltfpack pass) and stay that way:
//  - studio-orbit's only consumer, Phone3DScene.tsx's Orbit(), loads it
//    through its own bare useLoader(GLTFLoader, ...); design-spec.md#5
//    requires "zero code change" there, and that loader never registers
//    MeshoptDecoder, so a compressed file would throw at runtime.
//  - signal-marker's three consumers (StoryMapScene.tsx,
//    FoundationGraphScene.tsx, SkillsOrbitScene.tsx, none owned by this
//    lane) pull the Mesh straight off the scene graph
//    (getObjectByName("SignalMarker") / scene.children[0]) rather than
//    mounting the whole scene; gltfpack's quantization always wraps a
//    compressed mesh in an extra decode-transform node, which would
//    silently break that lookup. Both already fit comfortably inside their
//    KB row uncompressed, so there is no size reason to risk either.
//
// Measured tri / KB counts, refreshed by running each script and
// `stat -f%z public/models/*.glb`:
//
// | asset                     | tris  | KB    | budget tris | budget KB |
// |---------------------------|-------|-------|-------------|-----------|
// | studio-orbit (raw)         | 14792 | 207.2 | 30000       | 337       |
// | signal-marker (raw)         |   48 |   2.1 |   300       |  20       |
// | skills-core                 |  560 |  11.0 |  1200       |  30       |
// | blueprint-instrument        | 2820 |  19.8 |  5000       | 150       |
// | chess-handoff-marker        |  552 |   4.7 |  1000       |  15       |
// | world-monuments (4 nodes)   |  198 |   5.8 |  3200       |  60       |
// | kmp-foundation-keystone     |  540 |   7.8 |   800       |  20       |
//
// Total ~258 KB against the 340 KB wow-pass allowance (design-spec.md#4).

export const MODELS = {
  "studio-orbit": "/models/studio-orbit.glb",
  "signal-marker": "/models/signal-marker.glb",
  "skills-core": "/models/skills-core.glb",
  "blueprint-instrument": "/models/blueprint-instrument.glb",
  "chess-handoff-marker": "/models/chess-handoff-marker.glb",
  "world-monuments": "/models/world-monuments.glb",
  "kmp-foundation-keystone": "/models/kmp-foundation-keystone.glb",
} as const;

export type ModelName = keyof typeof MODELS;

/** useLoader caches by URL, so mounting the same model in several scenes
 * (signal-marker in StoryMapScene, FoundationGraphScene and SkillsOrbitScene)
 * fetches and parses the GLB once. Five of the seven GLBs are
 * meshopt-compressed (see the table above), so the loader needs the decoder
 * registered before parsing or GLTFLoader throws on those; registering it
 * unconditionally is a harmless no-op for the two raw GLBs. -kn on the
 * compressor kept every named node (e.g. blueprint-instrument's 'needle')
 * attached and lookup-able by name. */
export function useStudioModel(name: ModelName) {
  return useLoader(GLTFLoader, MODELS[name], (loader) => {
    loader.setMeshoptDecoder(MeshoptDecoder);
  });
}
