import { describe, expect, it } from "vitest";
import { ARTIFACTS, ARTIFACT_PICKUP_RADIUS } from "./artifacts.ts";
import { WORLD_BOUNDS } from "./craftPhysics.ts";
import { TERRAIN } from "./worldData.ts";

describe("artifacts are built from real data", () => {
  it("carries a non-empty fact on every one", () => {
    // They are read from profile.ts / projectStats.ts / chess.ts / weeb.ts,
    // all of which are regenerated by npm scripts. A shape change upstream
    // would otherwise show up as a silently blank collectible in the world
    // rather than as a failing build.
    for (const a of ARTIFACTS) {
      expect(a.label.trim().length, `${a.id} has no label`).toBeGreaterThan(0);
      expect(a.detail.trim().length, `${a.id} has no detail`).toBeGreaterThan(0);
    }
  });

  it("has unique ids", () => {
    expect(new Set(ARTIFACTS.map((a) => a.id)).size).toBe(ARTIFACTS.length);
  });
});

describe("completion requires every mechanic", () => {
  // The whole justification for the collection loop: it is the tutorial. If
  // every artifact could be reached on the wheels, none of the flying, sailing
  // or orbiting would ever need to be learned, and the world would be a lawn
  // with things on it.
  it("puts artifacts in both media", () => {
    // Was four media, when the world had flight and orbit. Two now — but the
    // point is unchanged: the set cannot be completed on the wheels, so
    // collecting is still how a visitor discovers the car swims.
    const media = new Set(ARTIFACTS.map((a) => a.medium));
    expect(media).toEqual(new Set(["land", "water"]));
  });

});

describe("every artifact is somewhere the craft can legally be", () => {
  it("sits inside the world bounds", () => {
    // An artifact outside the bounds box can never be collected: crossing the
    // boundary respawns the craft. That would make 100% permanently
    // unreachable, and the completion achievement a lie.
    for (const a of ARTIFACTS) {
      const [x, y, z] = a.position;
      expect(x, `${a.id} x`).toBeGreaterThan(WORLD_BOUNDS.minX);
      expect(x, `${a.id} x`).toBeLessThan(WORLD_BOUNDS.maxX);
      expect(z, `${a.id} z`).toBeGreaterThan(WORLD_BOUNDS.minZ);
      expect(z, `${a.id} z`).toBeLessThan(WORLD_BOUNDS.maxZ);
      expect(y, `${a.id} y`).toBeLessThan(WORLD_BOUNDS.maxY);
    }
  });

  it("keeps land artifacts on the mainland, not out over the cliff", () => {
    for (const a of ARTIFACTS.filter((a) => a.medium === "land")) {
      const [x, , z] = a.position;
      expect(Math.abs(x), `${a.id}`).toBeLessThan(TERRAIN.mainland.halfWidth);
      expect(z, `${a.id}`).toBeGreaterThan(TERRAIN.mainland.z0);
      expect(z, `${a.id}`).toBeLessThan(TERRAIN.mainland.z1);
    }
  });

  it("spaces them further apart than the pickup radius", () => {
    // Two artifacts inside one pickup radius would both fire from a single
    // drive-through, which reads as a bug even though it is generous.
    for (let i = 0; i < ARTIFACTS.length; i++) {
      for (let j = i + 1; j < ARTIFACTS.length; j++) {
        const a = ARTIFACTS[i].position;
        const b = ARTIFACTS[j].position;
        const d = Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
        expect(d, `${ARTIFACTS[i].id} overlaps ${ARTIFACTS[j].id}`).toBeGreaterThan(
          ARTIFACT_PICKUP_RADIUS,
        );
      }
    }
  });
});
