import { metrics, projects } from "../data/profile.ts";
import { projectStats } from "../data/projectStats.ts";
import { chess } from "../data/chess.ts";
import { weeb } from "../data/weeb.ts";
import { TERRAIN } from "./worldData.ts";

/**
 * The collectibles — and the reason this world is worth driving rather than
 * looking at.
 *
 * Every artifact is a REAL fact, read from the same data the rest of the site
 * renders: a shipped project and its module count, a production metric, the
 * chess corpus, the archive. Nothing here is invented flavour text. That is the
 * entire point — a portfolio whose 3D world is generic crates is a tech demo
 * bolted onto a CV, whereas one whose collectibles ARE the CV makes exploring
 * it the same act as reading it.
 *
 * They are spread over the whole desk on purpose: collecting the set is what
 * takes a visitor past every room, which is the only reason a hub needs a
 * collectible at all.
 */


export type Artifact = {
  id: string;
  /** Short name shown on the pickup toast. */
  label: string;
  /** The fact itself. */
  detail: string;
  position: [number, number, number];
};


/**
 * Deterministic placement. A seeded ring layout rather than Math.random so the
 * same artifact is always in the same place — a collectible that moves between
 * reloads cannot be hunted, and "I know there's one behind the CRT" is the
 * feeling worth protecting.
 */
/** Clearance kept between an artifact and any edge it could be knocked over. */
const MARGIN = 3;

/** 137.5° — the angle that makes a phyllotaxis spiral spread evenly. */
const GOLDEN_ANGLE = Math.PI * (3 - Math.sqrt(5));

function place(index: number, total: number): [number, number, number] {
  // Phyllotaxis — the sunflower spiral. Points at successive golden angles on a
  // sqrt radius are the standard way to scatter N things over a disc with no
  // two of them bunching, which concentric rings emphatically do not do: the
  // first version put sixteen artifacts on three rings and several landed
  // inside one pickup radius of each other, so a single drive-through
  // collected two at once. Deterministic, so a collectible never moves between
  // reloads and can actually be hunted.
  const { halfWidth, z0, z1, groundY } = TERRAIN.mainland;
  const angle = index * GOLDEN_ANGLE;
  const r = Math.sqrt((index + 0.5) / total);
  return [
    Math.cos(angle) * r * (halfWidth - MARGIN),
    groundY + 1.2,
    (z0 + z1) / 2 + Math.sin(angle) * r * ((z1 - z0) / 2 - MARGIN),
  ];
}

type Seed = { id: string; label: string; detail: string };

/** Built from the site's own data modules — see this file's header. */
function seeds(): Seed[] {
  const out: Seed[] = [];

  // Shipped work.
  for (const p of projects.slice(0, 5)) {
    out.push({ id: `project-${p.slug}`, label: p.name, detail: p.status });
  }

  // Production numbers — the ones the homepage leads with.
  for (const m of metrics) {
    out.push({
      id: `metric-${m.label.replace(/\s+/g, "-")}`,
      label: m.value,
      detail: `${m.label} — ${m.detail}`,
    });
  }

  // Repo scale, out over the water: these are the numbers that only mean
  // something once you know the codebase, so they sit past the shore.
  for (const [slug, stat] of Object.entries(projectStats)) {
    const modules = "modules" in stat ? stat.modules : undefined;
    const screenshots = "screenshots" in stat ? stat.screenshots : undefined;
    out.push({
      id: `stat-${slug}`,
      label: slug,
      detail: [modules && `${modules} modules`, screenshots && `${screenshots} screenshots`]
        .filter(Boolean)
        .join(" · "),
    });
  }

  // The side corpora, out on the water with the rooms that render them.
  // Shapes read from the generated files themselves, not assumed: chess keys
  // its counts under `totals`, weeb under `anime`. Both are regenerated by
  // npm scripts, so these numbers move on their own.
  out.push({
    id: "chess-corpus",
    label: "Chess corpus",
    detail: `${chess.totals.games.toLocaleString()} games · ${chess.totals.wins.toLocaleString()} wins`,
  });
  out.push({
    id: "weeb-corpus",
    label: "Weeb Central",
    detail: `${weeb.anime.total} titles logged, ${weeb.anime.matched} matched`,
  });

  // The two facts least visible from a CV: what this site actually is, and
  // that it keeps changing. Out in the far water, the longest sail on the map.
  out.push({
    id: "orbit-site",
    label: "This site",
    detail: "A running program, not a PDF with a pulse",
  });
  out.push({
    id: "orbit-loop",
    label: "Still shipping",
    detail: "The archive grows backwards as well as forwards",
  });

  return out;
}

export const ARTIFACTS: Artifact[] = seeds().map((s, i, all) => ({
  ...s,
  position: place(i, all.length),
}));

/** How close the craft has to get. Generous — hunting a collectible should be
 *  about finding it, not about threading a hitbox. */
export const ARTIFACT_PICKUP_RADIUS = 3.2;
