import { metrics, projects } from "../data/profile.ts";
import { projectStats } from "../data/projectStats.ts";
import { chess } from "../data/chess.ts";
import { weeb } from "../data/weeb.ts";
import { TERRAIN } from "./worldData.ts";
import { SPACE_ALTITUDE } from "./craftPhysics.ts";

/**
 * The collectibles — and the reason this world is worth driving rather than
 * looking at.
 *
 * Every artifact is a REAL fact, read from the same data the rest of the site
 * renders: a shipped project and its module count, a production metric, the
 * chess corpus, the archive. Nothing here is invented flavour text. That is the
 * entire point — a portfolio whose 3D world is generic crates is a tech demo
 * bolted onto a CV, whereas one whose collectibles ARE the CV makes exploring
 * it the same act as reading it.
 *
 * They are also deliberately spread across all four media. You cannot complete
 * the set on the ground: some sit over the Ink sea, some on the sky islands,
 * and two are in orbit. Collection is therefore the tutorial — it teaches the
 * hull, the thermals and the launch pads by putting something you want on the
 * far side of each.
 */

export type ArtifactMedium = "land" | "water" | "air" | "orbit";

export type Artifact = {
  id: string;
  /** Short name shown on the pickup toast. */
  label: string;
  /** The fact itself. */
  detail: string;
  tint: string;
  medium: ArtifactMedium;
  position: [number, number, number];
};

const TINTS = {
  land: "#3ddc84",
  water: "#5ee6ff",
  air: "#db61ff",
  orbit: "#f0883e",
} as const;

/**
 * Deterministic placement. A seeded ring layout rather than Math.random so the
 * same artifact is always in the same place — a collectible that moves between
 * reloads cannot be hunted, and "I know there's one behind the CRT" is the
 * feeling worth protecting.
 */
/** Clearance kept between an artifact and any edge it could be knocked over. */
const MARGIN = 3;

function place(medium: ArtifactMedium, index: number, total: number): [number, number, number] {
  const angle = (index / Math.max(1, total)) * Math.PI * 2;
  switch (medium) {
    case "land": {
      // Radii derived from the mainland's own extents rather than hand-picked.
      // The first version used a fixed radius that put an artifact at z=13.7,
      // past the south edge at z=12 — floating over the shore at land height,
      // unreachable by car and unreachable by boat. artifacts.test.ts caught it
      // before it was ever rendered, which is the entire argument for keeping
      // placement derived instead of typed out.
      const cz = (TERRAIN.mainland.z0 + TERRAIN.mainland.z1) / 2;
      const halfDepth = (TERRAIN.mainland.z1 - TERRAIN.mainland.z0) / 2;
      const spread = 0.55 + (index % 3) * 0.18; // three concentric rings
      const rx = (TERRAIN.mainland.halfWidth - MARGIN) * spread;
      const rz = (halfDepth - MARGIN) * spread;
      return [
        Math.cos(angle) * rx,
        TERRAIN.mainland.groundY + 1.4,
        cz + Math.sin(angle) * rz,
      ];
    }
    case "water":
      return [Math.cos(angle) * 17, 1.6, 34 + Math.sin(angle) * 12];
    case "air":
      return [Math.cos(angle) * 15, 22 + (index % 3) * 6, 55 + Math.sin(angle) * 9];
    case "orbit":
      return [Math.cos(angle) * 12, SPACE_ALTITUDE + 12 + index * 9, 58 + Math.sin(angle) * 10];
  }
}

type Seed = { id: string; label: string; detail: string; medium: ArtifactMedium };

/** Built from the site's own data modules — see this file's header. */
function seeds(): Seed[] {
  const out: Seed[] = [];

  // Shipped work, on the ground where the build rooms are.
  for (const p of projects.slice(0, 5)) {
    out.push({ id: `project-${p.slug}`, label: p.name, detail: p.status, medium: "land" });
  }

  // Production numbers — the ones the homepage leads with.
  for (const m of metrics) {
    out.push({
      id: `metric-${m.label.replace(/\s+/g, "-")}`,
      label: m.value,
      detail: `${m.label} — ${m.detail}`,
      medium: "land",
    });
  }

  // Repo scale, out over the water: these are the numbers that only mean
  // something once you know the codebase, so they sit past the shore.
  for (const [slug, stat] of Object.entries(projectStats)) {
    const modules = "modules" in stat ? stat.modules : undefined;
    const screenshots = "screenshots" in stat ? stat.screenshots : undefined;
    out.push({
      id: `stat-${slug}`,
      label: slug,
      detail: [modules && `${modules} modules`, screenshots && `${screenshots} screenshots`]
        .filter(Boolean)
        .join(" · "),
      medium: "water",
    });
  }

  // The side corpora, up on the sky islands with the rooms that render them.
  // Shapes read from the generated files themselves, not assumed: chess keys
  // its counts under `totals`, weeb under `anime`. Both are regenerated by
  // npm scripts, so these numbers move on their own.
  out.push({
    id: "chess-corpus",
    label: "Chess corpus",
    detail: `${chess.totals.games.toLocaleString()} games · ${chess.totals.wins.toLocaleString()} wins`,
    medium: "air",
  });
  out.push({
    id: "weeb-corpus",
    label: "Weeb Central",
    detail: `${weeb.anime.total} titles logged, ${weeb.anime.matched} matched`,
    medium: "air",
  });

  // Orbit. Deliberately the hardest to reach and deliberately the two facts
  // that are least visible from a CV: the thing this site is, and the fact that
  // it keeps changing.
  out.push({
    id: "orbit-site",
    label: "This site",
    detail: "A running program, not a PDF with a pulse",
    medium: "orbit",
  });
  out.push({
    id: "orbit-loop",
    label: "Still shipping",
    detail: "The archive grows backwards as well as forwards",
    medium: "orbit",
  });

  return out;
}

export const ARTIFACTS: Artifact[] = (() => {
  const all = seeds();
  const byMedium = new Map<ArtifactMedium, Seed[]>();
  for (const s of all) {
    const list = byMedium.get(s.medium) ?? [];
    list.push(s);
    byMedium.set(s.medium, list);
  }
  const out: Artifact[] = [];
  for (const [medium, list] of byMedium) {
    list.forEach((s, i) => {
      out.push({ ...s, tint: TINTS[medium], position: place(medium, i, list.length) });
    });
  }
  return out;
})();

/** How close the craft has to get. Generous — hunting a collectible should be
 *  about finding it, not about threading a hitbox. */
export const ARTIFACT_PICKUP_RADIUS = 3.2;
