// AUTO-GENERATED by scripts/gen-world-plate.mjs — do not edit by hand.
//
// The metadata src/world/CorridorPlate.tsx overlays on heavy/p/world/corridor.png
// — Night Survey art-direction doc §11's "8 year rules and lane monograms
// drawn as inline SVG on top of it in the DOM". Kept as committed data
// (never recomputed from three.js) so the DOM overlay can render with zero
// WebGL and zero drift from the baked image beneath it.
export interface CorridorPlateLane {
  key: string;
  label: string;
  color: string;
  /** 0..1 fraction of the image's height — the lane's own centreline. */
  yFraction: number;
}
export interface CorridorPlateYear {
  year: number;
  /** 0..1 fraction of the image's width. */
  xFraction: number;
}
export interface CorridorPlateMeta {
  generatedAt: string;
  width: number;
  height: number;
  from: string;
  to: string;
  lanes: CorridorPlateLane[];
  years: CorridorPlateYear[];
}
export const corridorPlateMeta: CorridorPlateMeta = {
  "generatedAt": "2026-10-07T14:15:09.129Z",
  "width": 2400,
  "height": 800,
  "from": "2019-01",
  "to": "2026-10",
  "lanes": [
    {
      "key": "work",
      "label": "work",
      "color": "#3ddc84",
      "yFraction": 0.125
    },
    {
      "key": "chess",
      "label": "chess",
      "color": "#5ee6ff",
      "yFraction": 0.375
    },
    {
      "key": "writing",
      "label": "writing",
      "color": "#f2a13d",
      "yFraction": 0.625
    },
    {
      "key": "opensource",
      "label": "open source",
      "color": "#e8efe9",
      "yFraction": 0.875
    }
  ],
  "years": [
    {
      "year": 2019,
      "xFraction": 0
    },
    {
      "year": 2020,
      "xFraction": 0.12765957446808512
    },
    {
      "year": 2021,
      "xFraction": 0.25531914893617025
    },
    {
      "year": 2022,
      "xFraction": 0.3829787234042553
    },
    {
      "year": 2023,
      "xFraction": 0.5106382978723405
    },
    {
      "year": 2024,
      "xFraction": 0.6382978723404256
    },
    {
      "year": 2025,
      "xFraction": 0.7659574468085106
    },
    {
      "year": 2026,
      "xFraction": 0.8936170212765957
    }
  ]
};
