/**
 * Everything true right now (living-ledger-spec §4). `STREAMS` is the live
 * counterpart of GRAMMAR (P2-03c): every live, modelled, computed, ambient
 * or per-viewer input the world draws has exactly one row here, up front,
 * with enough provenance that the Reality ledger can render straight from
 * it rather than from a hand-written caption.
 *
 * A `claim: false` row is ambient: ledger.ts, grammar.ts and the profile
 * data never back it, and its renderer never reaches for an amber/cyan/
 * green "live" token or opens a detail panel (streamFence.test.ts).
 */

import type { DeviceTier } from "../deviceTier.ts";

export type Altitude = "street" | "orbit" | "globe";
export type StreamClass = "live" | "modelled" | "computed" | "static" | "session" | "local" | "ambient";

export interface Stream {
  id: string;
  class: StreamClass;
  form: string | string[];
  source: string;
  licence: string;
  /** Never empty — this lane's acceptance checks it on every entry. */
  attribution: string;
  endpoint?: `/api/${string}`;
  pollMs?: number;
  altitudes: readonly Altitude[];
  tiers: Record<DeviceTier, string>;
  reducedMotion: string;
  /** What renders when this stream is down — never a stale value dressed
   *  as live (living-ledger-spec §4). */
  failure: string;
  claim: boolean;
}

const STREET_ONLY: readonly Altitude[] = ["street"];
const ALL_ALTITUDES: readonly Altitude[] = ["street", "orbit", "globe"];

export const STREAMS: readonly Stream[] = [
  {
    id: "sun",
    class: "computed",
    form: "sun-disc",
    source: "NOAA solar position equations",
    licence: "public domain",
    attribution: "Sun position: NOAA solar calculator equations",
    altitudes: ALL_ALTITUDES,
    tiers: { 1: "full sky dome, moving shadows", 2: "sky dome, static shadows", 3: "flat sky gradient by daypart" },
    reducedMotion: "sun position still updates per minute; the light itself does not animate between updates",
    failure: "falls back to the daypart computed from the clock alone (no live correction)",
    claim: true,
  },
  {
    id: "moon",
    class: "computed",
    form: "moon-disc",
    source: "low-precision lunar position and phase (Meeus, truncated)",
    licence: "public domain (published algorithm, no data licence)",
    attribution: "Moon position: Meeus, Astronomical Algorithms ch. 47 (truncated series)",
    altitudes: ["street", "orbit"],
    tiers: { 1: "moon disc with phase shading and water glint", 2: "moon disc, phase only", 3: "no moon disc, night key light only" },
    reducedMotion: "phase and position still update per minute; no glint animation",
    failure: "night key light falls back to a fixed dim level, moon disc hidden",
    claim: true,
  },
  {
    id: "weather",
    class: "live",
    form: "cloud-dim",
    source: "Open-Meteo forecast",
    licence: "CC BY 4.0",
    attribution: "Weather data by Open-Meteo.com (CC BY 4.0)",
    endpoint: "/api/weather",
    pollMs: 900_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "cloud dimming, wind sway and audio, live temperature row", 2: "cloud dimming, temperature row", 3: "temperature row only" },
    reducedMotion: "cloud cover and temperature still update on poll; wind sway animation is dropped",
    failure: "sky dims to a fixed overcast state; temperature row reads \"unavailable right now\"",
    claim: true,
  },
  {
    id: "rain6h",
    class: "live",
    form: "rain-ring",
    source: "Open-Meteo forecast, hourly precipitation, past 6 hours",
    licence: "CC BY 4.0",
    attribution: "Weather data by Open-Meteo.com (CC BY 4.0)",
    endpoint: "/api/weather",
    pollMs: 900_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "wet-bank darkening, rain rings on the water, river-bed audio gain", 2: "wet-bank darkening only", 3: "no rain visual" },
    reducedMotion: "wet-bank darkening still updates on poll; the ring animation is dropped",
    failure: "renders dry (0mm); nothing is guessed",
    claim: true,
  },
  {
    id: "air",
    class: "modelled",
    form: "haze",
    source: "Open-Meteo Air Quality, CAMS",
    licence: "CC BY 4.0",
    attribution: "Air quality: CAMS model via Open-Meteo.com (CC BY 4.0), contains modified Copernicus Atmosphere Monitoring Service information",
    endpoint: "/api/weather",
    pollMs: 900_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "haze/fog density from AOD, PM2.5 and US AQI in the ledger row", 2: "PM2.5 and US AQI in the ledger row, fixed haze", 3: "AQI number only" },
    reducedMotion: "no motion in this stream regardless of the setting",
    failure: "haze falls back to a fixed clear-day density; ledger row reads \"unavailable right now\"",
    claim: true,
  },
  {
    id: "river",
    class: "modelled",
    form: "ambient:geography",
    source: "Open-Meteo Flood API, GloFAS v4",
    licence: "CC BY 4.0, Copernicus EMS",
    attribution: "River discharge: GloFAS (Copernicus EMS) via Open-Meteo.com, modelled 5km cell, not a gauge",
    endpoint: "/api/weather",
    pollMs: 900_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "flow speed, foam and water level vs. the 7-day range, river-bed audio", 2: "water level vs. the 7-day range", 3: "static water level" },
    reducedMotion: "water level still updates on poll; foam/flow animation is dropped",
    failure: "water level holds its last-known state; ledger row reads \"unavailable right now\"",
    claim: false,
  },
  {
    id: "season",
    class: "modelled",
    form: "ambient:geography",
    source: "Open-Meteo forecast, daily precipitation sum, trailing 30 days",
    licence: "CC BY 4.0",
    attribution: "Weather data by Open-Meteo.com (CC BY 4.0)",
    endpoint: "/api/weather",
    pollMs: 900_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "monsoon-band ground wetness from the 30-day sum", 2: "monsoon-band ground wetness", 3: "no seasonal ground shift" },
    reducedMotion: "no motion in this stream regardless of the setting",
    failure: "ground wetness falls back to its dry-season baseline",
    claim: false,
  },
  {
    id: "stars",
    class: "ambient",
    form: "star",
    source: "Yale Bright Star Catalogue 5, mag < 4 subset",
    licence: "public",
    attribution: "Star positions: Yale Bright Star Catalogue 5 (public)",
    altitudes: ["street", "orbit"],
    tiers: { 1: "full bright-star field", 2: "brightest stars only", 3: "no stars, flat night sky" },
    reducedMotion: "static field either way; only their fade in/out at dawn and dusk is capped",
    failure: "renders as a flat night sky with no star field (static heavy asset, nothing to fail live)",
    claim: false,
  },
  {
    id: "aircraft",
    class: "ambient",
    form: "aircraft-light",
    source: "adsb.lol v2 point query, 60nm around the Sangam",
    licence: "ODbL",
    attribution: "Aircraft positions: adsb.lol (ODbL); callsign, registration and hex dropped server-side",
    endpoint: "/api/aircraft",
    pollMs: 20_000,
    altitudes: ["street", "globe"],
    tiers: { 1: "aircraft lights at true azimuth/elevation, local cluster on GLOBE", 2: "local cluster on GLOBE only", 3: "no aircraft" },
    reducedMotion: "positions still update on poll; the light does not tween between polls",
    failure: "renders absent, no aircraft lights; nothing is backfilled",
    claim: false,
  },
  {
    id: "satellites",
    class: "ambient",
    form: "satellite-point",
    source: "CelesTrak GP, stations group",
    licence: "public",
    attribution: "Orbital elements: CelesTrak (public)",
    endpoint: "/api/tle",
    pollMs: 21_600_000,
    altitudes: ["street", "globe"],
    tiers: { 1: "ISS crossing the valley sky when above the horizon, ~20 orbits on GLOBE", 2: "ISS crossing only, no GLOBE orbits", 3: "no satellites" },
    reducedMotion: "position still updates on poll; the crossing does not tween between polls",
    failure: "renders absent, no ISS crossing; nothing is backfilled",
    claim: false,
  },
  {
    id: "pushes24h",
    class: "live",
    form: "diya",
    source: "GitHub Events API, this account's public push events",
    licence: "GitHub API terms",
    attribution: "Activity: GitHub Events API",
    endpoint: "/api/ops",
    pollMs: 60_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "diyas launched per push, with a short float animation", 2: "diyas appear, no float animation", 3: "count only, no diyas drawn" },
    reducedMotion: "diyas still appear per push; the launch/float animation is dropped",
    failure: "no new diyas; the last known count holds and is labelled stale",
    claim: true,
  },
  {
    id: "ci-site",
    class: "live",
    form: "deck-lamp",
    source: "GitHub Actions runs, this repo",
    licence: "GitHub API terms",
    attribution: "CI status: GitHub Actions",
    endpoint: "/api/ops",
    pollMs: 60_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "keystone bridge deck-lamp state (pass/fail/none)", 2: "deck-lamp colour only, no per-run detail", 3: "text state only" },
    reducedMotion: "no motion in this stream regardless of the setting",
    failure: "deck-lamp holds its last known state, labelled stale",
    claim: true,
  },
  {
    id: "ci-family",
    class: "live",
    form: "deck-lamp",
    source: "GitHub Actions runs, the sibling KMP-family repos",
    licence: "GitHub API terms",
    attribution: "CI status: GitHub Actions (family repos)",
    endpoint: "/api/signals",
    pollMs: 60_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "per-repo deck-lamp state across the family", 2: "worst-state lamp only", 3: "text state only" },
    reducedMotion: "no motion in this stream regardless of the setting",
    failure: "family lamps hold their last known state, labelled stale",
    claim: true,
  },
  {
    id: "chess-presence",
    class: "live",
    form: "chess-ridge-glow",
    source: "lichess.org public user-status API",
    licence: "lichess API terms (no data licence stated; public endpoint)",
    attribution: "Presence: lichess.org",
    endpoint: "/api/signals",
    pollMs: 60_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "ridge glows while online, brighter while a game is live", 2: "ridge glow, online only, no live-game distinction", 3: "no glow" },
    reducedMotion: "glow state still updates on poll; no pulse animation",
    failure: "renders as offline; nothing is assumed",
    claim: true,
  },
  {
    id: "kites-devto",
    class: "live",
    form: "lesson-kite",
    source: "dev.to public articles API, this account",
    licence: "Forem/dev.to API terms (public endpoint)",
    attribution: "Reactions: dev.to",
    endpoint: "/api/signals",
    pollMs: 60_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "kite altitude from live reaction count", 2: "kite altitude from last-cached reaction count", 3: "kite at its unmeasured floor" },
    reducedMotion: "no motion in this stream regardless of the setting",
    failure: "kite renders at the unmeasured floor with a grey tether, never a guessed altitude",
    claim: true,
  },
  {
    id: "downloads",
    class: "live",
    form: "site-courses",
    source: "GitHub Releases API, the sibling KMP-family repos",
    licence: "GitHub API terms",
    attribution: "Downloads: GitHub Releases",
    endpoint: "/api/signals",
    pollMs: 60_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "live per-release download counts", 2: "totals only", 3: "no download detail" },
    reducedMotion: "no motion in this stream regardless of the setting",
    failure: "download counts hold their last known value, labelled stale",
    claim: true,
  },
  {
    id: "presence",
    class: "live",
    form: "lantern",
    source: "playhtml usePresence, this site",
    licence: "first-party (playhtml, self-hosted channel)",
    attribution: "Presence: this site's own realtime channel",
    altitudes: STREET_ONLY,
    tiers: { 1: "paper lanterns per visitor, live \"here now\" count", 2: "\"here now\" count only, no lanterns", 3: "no presence UI" },
    reducedMotion: "lantern positions still update in realtime; drift/bob animation is dropped",
    failure: "\"here now\" reads 1 (yourself only); no lanterns for anyone else",
    claim: true,
  },
  {
    id: "presence-countries",
    class: "live",
    form: "presence-dot",
    source: "edge request country header, this site",
    licence: "first-party (derived from the visitor's own edge-observed country, never stored)",
    attribution: "Presence: this site's own realtime channel",
    endpoint: "/api/whereami",
    altitudes: ["globe"],
    tiers: { 1: "live per-country dots and valley far-ring rim light", 2: "aggregate dot count only", 3: "no GLOBE presence layer" },
    reducedMotion: "dots still update in realtime; no rim-light pulse",
    failure: "GLOBE presence layer renders empty; nothing is guessed",
    claim: true,
  },
  {
    id: "radio",
    class: "live",
    form: "radio-note",
    source: "Spotify currently-playing API, this account",
    licence: "Spotify API terms",
    attribution: "Now playing: Spotify",
    endpoint: "/api/spotify",
    pollMs: 60_000,
    altitudes: STREET_ONLY,
    tiers: { 1: "hodi radio readout: track and artist", 2: "hodi radio readout, track title only", 3: "no radio readout" },
    reducedMotion: "no motion in this stream regardless of the setting",
    failure: "radio readout reads \"nothing playing right now\"",
    claim: true,
  },
  {
    id: "touched",
    class: "session",
    form: "touched-seam",
    source: "reality-spec sessionRipple, in-memory this tab",
    licence: "first-party (this session only, never persisted)",
    attribution: "first-party, no external source",
    altitudes: STREET_ONLY,
    tiers: { 1: "signal-green seam on every district you visited this session", 2: "seam on the current district only", 3: "no seam" },
    reducedMotion: "seam still appears on visit; no travelling-pulse animation",
    failure: "no seam anywhere (equivalent to an unvisited session)",
    claim: true,
  },
  {
    id: "last-visit",
    class: "local",
    form: "since-last-visit-diff",
    source: "localStorage world:lastSeen, this browser only",
    licence: "first-party (per-viewer convenience, wrapped in try/catch — artifact-design browser-storage rule)",
    attribution: "first-party, no external source",
    altitudes: STREET_ONLY,
    tiers: { 1: "\"since your last visit\" diff panel", 2: "one-line diff summary", 3: "no diff shown" },
    reducedMotion: "no motion in this stream regardless of the setting",
    failure: "renders as a first visit (no diff) when storage is blocked or empty",
    claim: true,
  },
  {
    id: "festival",
    class: "computed",
    form: ["festival:rangoli", "festival:toran", "festival:paper-kite", "festival:gudi"],
    source: "a fixed Indian festival calendar, computed from the date",
    licence: "first-party (dates only, no third-party data)",
    attribution: "first-party, no external source",
    altitudes: STREET_ONLY,
    tiers: { 1: "full festival-kit decoration set", 2: "one festival-kit form only", 3: "no festival decoration" },
    reducedMotion: "no motion in this stream regardless of the setting",
    failure: "renders as an ordinary (non-festival) day",
    claim: false,
  },
  {
    id: "birds",
    class: "ambient",
    form: "birds",
    source: "a fixed flock-motion sketch, no live data (visual-catalogue V2, master-plan M67)",
    licence: "first-party (no external data, ambient motion only)",
    attribution: "first-party, no external source",
    altitudes: STREET_ONLY,
    tiers: { 1: "flock instances with wing-flap motion", 2: "flock instances, static wings", 3: "no birds" },
    reducedMotion: "flock is static; no flap or flight-path motion",
    failure: "renders absent; there is no live upstream to fail",
    claim: false,
  },
  {
    id: "reach-counter",
    class: "live",
    form: "reach-column",
    source: "server-side visit counter, this site (/api/reach)",
    licence: "first-party",
    attribution: "first-party, no external source",
    endpoint: "/api/reach",
    altitudes: ["globe"],
    tiers: { 1: "off by default (D3 in living-ledger §9.1, owner decision)", 2: "off by default", 3: "off by default" },
    reducedMotion: "n/a while disabled",
    failure: "n/a while disabled — the column simply never renders",
    claim: false,
  },
];
