// scripts/gen-lanes.mjs
/**
 * Emits src/data/lanes.ts — the four-lane view timeline.ts already carries but
 * nothing on the site renders combined.
 *
 * NOT A SECOND DATA MODEL. timeline.ts (gen-timeline.mjs) already merged work,
 * chess, writing and open-source into one Timeline with a shared month axis —
 * that merge is what the Profile repo's own scripts/gen-lanes.mjs fetches over
 * HTTP and re-parses with regex to draw the GitHub-profile SVG strip
 * (assets/lanes-*.svg, README.md:16-19). This generator does the same
 * selection *in-repo*, with an import instead of a fetch-and-regex, and hands
 * the same four lanes to a live React view (Lanes.tsx) instead of a static SVG.
 * Same shape, same four keys, same house reason (timeline.ts's own header:
 * "nothing about the landscape is invented") — reused, not reinvented.
 *
 * DETERMINISTIC: timeline.ts is already committed and already the source of
 * truth; this only re-shapes it. Listed in check-generated.mjs.
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { timeline } from "../src/data/timeline.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "src/data/lanes.ts");

// One CSS custom property per lane, not a hex literal: readToken-free here
// because this file is emitted, read at render time as `var(--x)` inside an
// <svg>, which resolves theme-reactively with no JS. Chess and writing reuse
// tokens the site already ties to those exact domains (surfaces.ts's
// CHESS_GOLD is --lab-gold; --color-alt is otherwise unclaimed); work reuses
// the site's own accent; open source reuses --color-signal, already
// documented elsewhere as "lit/live/active" — which is what a merged PR is.
const HUE_VAR = {
  work: "--color-accent",
  opensource: "--color-signal",
  writing: "--color-alt",
  chess: "--lab-gold",
};

const ORDER = ["work", "opensource", "writing", "chess"];

const lanes = ORDER.map((key) => {
  const lane = timeline.lanes.find((l) => l.key === key);
  if (!lane) return null;
  return {
    key: lane.key,
    label: lane.label,
    unit: lane.unit,
    hueVar: HUE_VAR[key],
    months: lane.months,
    total: lane.total,
    peak: lane.peak,
  };
}).filter(Boolean);

if (lanes.length < 3) {
  console.error(`[gen-lanes] found only ${lanes.length}/4 lanes in timeline.ts, refusing to write a near-empty file.`);
  console.error("  timeline.ts's shape probably changed. Fix the key list above rather than deleting this guard.");
  process.exitCode = 1;
} else {
  const body =
    `// AUTO-GENERATED by scripts/gen-lanes.mjs from src/data/timeline.ts — do not edit by hand.\n` +
    `// The four lanes the Profile repo's README strip already draws (assets/lanes-*.svg),\n` +
    `// rendered live here instead of as a fetched-and-regexed static SVG. Run\n` +
    `// \`npm run gen:lanes\` to refresh after timeline.ts changes.\n` +
    `export interface Lane {\n  key: string;\n  label: string;\n  unit: string;\n  hueVar: string;\n  months: Record<string, number>;\n  total: number;\n  peak: { ym: string; v: number };\n}\n` +
    `export const laneMonths: string[] = ${JSON.stringify(timeline.months)};\n` +
    `export const lanes: Lane[] = ${JSON.stringify(lanes, null, 2)} as const;\n`;
  writeFileSync(OUT, body);
  console.log(`[gen-lanes] ${lanes.length} lanes x ${timeline.months.length} months (${timeline.months[0]} to ${timeline.months.at(-1)})`);
}
