// scripts/gen-history.mjs
/**
 * Emits src/data/history.ts — this repo's own commit history, bucketed by
 * month, for the git-history time machine (docs/SIDOS-VISION.md:30).
 *
 * SCOPED AGAINST THE EXISTING GENERATORS, NOT A LIVE SHELL-OUT: `git log`
 * runs exactly once, here, at generation time — the same contract
 * gen-repo-stats.mjs uses for `vitest list` and gen-timeline.mjs uses for its
 * live sources. The site itself never shells out to git; TimeMachine.tsx
 * only ever reads the committed src/data/history.ts this writes. A deployed
 * static site has no git binary to call anyway.
 *
 * NOT LISTED IN check-generated.mjs's DETERMINISTIC set, by the same rule
 * that file states for "git commit counts": this repo's history only grows,
 * so a second run never reproduces the first run's bytes. Its own staleness
 * is bounded instead by an entry in freshnessSla.ts, same as chess/weeb/etc.
 *
 * Per the house generator contract: a failed `git log` leaves the previously
 * committed file exactly as it was rather than writing a degraded one.
 */
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "src/data/history.ts");

const RECORD_SEP = "\x1e"; // ASCII record separator, never appears in a commit subject
const FIELD_SEP = "\x1f"; // ASCII unit separator

let raw;
try {
  raw = execFileSync(
    "git",
    ["-C", root, "log", `--pretty=format:${RECORD_SEP}%ad${FIELD_SEP}%s`, "--date=format:%Y-%m-%d", "--shortstat", "--reverse"],
    { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
  );
} catch (err) {
  console.error(`[gen-history] git log failed, keeping the committed file: ${err.message}`);
  process.exit(0);
}

if (!existsSync(join(root, ".git")) && !raw) {
  console.error("[gen-history] no .git history found, keeping the committed file.");
  process.exit(0);
}

/** One row per commit: date, subject, and the shortstat line that follows it (if any). */
const commits = raw
  .split(RECORD_SEP)
  .map((s) => s.trim())
  .filter(Boolean)
  .map((chunk) => {
    const nl = chunk.indexOf("\n");
    const head = nl === -1 ? chunk : chunk.slice(0, nl);
    const [date, subject] = head.split(FIELD_SEP);
    const stat = nl === -1 ? "" : chunk.slice(nl + 1);
    const files = Number(stat.match(/(\d+) files? changed/)?.[1] ?? 0);
    const insertions = Number(stat.match(/(\d+) insertions?\(\+\)/)?.[1] ?? 0);
    const deletions = Number(stat.match(/(\d+) deletions?\(-\)/)?.[1] ?? 0);
    return { date, subject, files, insertions, deletions };
  });

if (commits.length < 10) {
  console.error(`[gen-history] parsed only ${commits.length} commits, refusing to write a near-empty history.`);
  process.exitCode = 1;
  process.exit();
}

/** Every "YYYY-MM" from the first commit's month to the last, inclusive — no gaps. */
function monthRange(from, to) {
  const out = [];
  let [y, m] = from.split("-").map(Number);
  const [ty, tm] = to.split("-").map(Number);
  while (y < ty || (y === ty && m <= tm)) {
    out.push(`${y}-${String(m).padStart(2, "0")}`);
    m++;
    if (m > 12) { m = 1; y++; }
  }
  return out;
}

const firstMonth = commits[0].date.slice(0, 7);
const lastMonth = commits.at(-1).date.slice(0, 7);
const months = monthRange(firstMonth, lastMonth);

const byMonth = new Map(months.map((m) => [m, { commits: 0, insertions: 0, deletions: 0, filesChanged: 0, subjects: [] }]));
let cumulativeCommits = 0, cumulativeInsertions = 0, cumulativeDeletions = 0;
const cumulative = {};

for (const c of commits) {
  const ym = c.date.slice(0, 7);
  const bucket = byMonth.get(ym);
  bucket.commits++;
  bucket.insertions += c.insertions;
  bucket.deletions += c.deletions;
  bucket.filesChanged += c.files;
  // Conventional-commit prefixes read as milestones; capped at 6/month so a
  // busy month doesn't turn the scrubber into a full changelog.
  if (bucket.subjects.length < 6 && /^(feat|fix)(\(.+\))?:/.test(c.subject)) bucket.subjects.push(c.subject);
}
for (const m of months) {
  const b = byMonth.get(m);
  cumulativeCommits += b.commits;
  cumulativeInsertions += b.insertions;
  cumulativeDeletions += b.deletions;
  cumulative[m] = { commits: cumulativeCommits, insertions: cumulativeInsertions, deletions: cumulativeDeletions };
}

const monthRows = months.map((m) => ({ ym: m, ...byMonth.get(m), cumulative: cumulative[m] }));

const body =
  `// AUTO-GENERATED by scripts/gen-history.mjs from this repo's own \`git log\` — do not edit by hand.\n` +
  `// Run \`npm run gen:history\` to refresh. Bytes here change on every real commit,\n` +
  `// so this generator is NOT in check-generated.mjs's deterministic set (see that\n` +
  `// file's own note on "git commit counts").\n` +
  `export interface HistoryMonth {\n  ym: string;\n  commits: number;\n  insertions: number;\n  deletions: number;\n  filesChanged: number;\n  subjects: string[];\n  cumulative: { commits: number; insertions: number; deletions: number };\n}\n` +
  `export const historyMonths: HistoryMonth[] = ${JSON.stringify(monthRows, null, 2)} as const;\n` +
  `export const historyGeneratedAt = ${JSON.stringify(new Date().toISOString())};\n` +
  `export const historyFrom = ${JSON.stringify(firstMonth)};\n` +
  `export const historyTo = ${JSON.stringify(lastMonth)};\n` +
  `export const totalCommits = ${cumulativeCommits};\n`;

writeFileSync(OUT, body);
console.log(`[gen-history] ${cumulativeCommits} commits across ${months.length} months (${firstMonth} to ${lastMonth})`);
