/**
 * Generates src/data/store.ts — the shipped-app shelf.
 *
 * The package ids are MINED, not typed from memory: they come from the
 * `applicationId` lines in the product flavours of the app repos —
 *   ~/Repos/Dice/androidAppSaaS/app/build.gradle.kts
 *   ~/Repos/Android/Jugnoo/jugnoo-android-autos/.../jugnooNewUI/build.gradle
 *   ~/Repos/Android/Jugnoo/jugnoo-android-driver/app/build.gradle
 * and every one is then VERIFIED against the live Play Store before it is
 * written. An id that does not resolve is dropped with a warning rather than
 * shipped as a dead link, because a broken store link on a portfolio reads as
 * a claim that did not survive contact.
 *
 * WHAT THE 404s TAUGHT US, and why it is in the data:
 * the white-label flavours — product.clicklabs.jugnoo.white,
 * product.clicklabs.jugnoo.white.driver, product.customer.tempwl,
 * product.driver.tempwl — are NOT published. They are build templates; each
 * client ships under its own id. So "white label" here is a real thing with no
 * single listing to point at, and the honest version of that claim is a count
 * of flavours in the repo, not a link. Same story at Dice from the other
 * direction: ONE binary (io.eka.ekav2, flavours are sslPinning only) with
 * tenanting at runtime — 69 tenant packages and 204 feature flags in the
 * backend. Nobody forks the app to brand it, which is exactly what the CV says.
 *
 * Usage: npm run gen:store
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

/** Mined from the flavour blocks named above. Order is display order. */
const CANDIDATES = [
  { id: "io.eka.ekav2", role: "Technical owner & Product Owner", employer: "Dice.tech" },
  { id: "product.clicklabs.jugnoo", role: "Android engineer", employer: "Jugnoo" },
  { id: "product.clicklabs.jugnoo.driver", role: "Android engineer", employer: "Jugnoo" },
];

/** Unpublished white-label templates — kept as evidence, never linked. */
const WHITE_LABEL_TEMPLATES = [
  "product.clicklabs.jugnoo.white",
  "product.clicklabs.jugnoo.white.driver",
  "product.customer.tempwl",
  "product.driver.tempwl",
];

const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/124 Safari/537.36";

async function fetchListing(id) {
  const url = `https://play.google.com/store/apps/details?id=${id}&hl=en`;
  const res = await fetch(url, { headers: { "user-agent": UA } });
  if (!res.ok) return { id, ok: false, status: res.status };
  const html = await res.text();
  const name = html.match(/itemprop="name"[^>]*>([^<]{1,80})/)?.[1]?.trim();
  const rating = html.match(/aria-label="Rated ([0-9.]+) stars/)?.[1];
  // Play renders the install count in a few shapes depending on locale/layout.
  const installs =
    html.match(/([0-9.]+[KMB]\+)\s*<\/div><div[^>]*>Downloads/)?.[1] ??
    html.match(/>([0-9.,]+[KMB]?\+)<\/div><div[^>]*>Downloads/)?.[1] ??
    null;
  if (!name) return { id, ok: false, status: res.status, reason: "no name in page" };
  return { id, ok: true, name, rating: rating ? Number(rating) : null, installs, url };
}

const results = await Promise.all(CANDIDATES.map((c) => fetchListing(c.id).then((r) => ({ ...c, ...r }))));

const live = results.filter((r) => r.ok);
for (const r of results.filter((r) => !r.ok)) {
  console.warn(`[gen-store] DROPPED ${r.id} — ${r.status}${r.reason ? ` (${r.reason})` : ""}`);
}
if (live.length === 0) throw new Error("[gen-store] no listing resolved — refusing to write an empty shelf");

const out = `// AUTO-GENERATED by scripts/gen-store.mjs — do not edit by hand.
//
// Shipped Android apps, verified live on the Play Store at generation time.
// Package ids are mined from the applicationId lines in each repo's product
// flavours; anything that does not resolve is dropped rather than shipped as a
// dead link. Run \`npm run gen:store\` to refresh.
export const storeApps = ${JSON.stringify(
  live.map(({ id, name, rating, installs, url, role, employer }) => ({
    id,
    name,
    rating,
    installs,
    url,
    role,
    employer,
  })),
  null,
  2,
)} as const;

/**
 * White-label flavours that exist in the repos and are NOT separately published
 * — each client ships under its own package id. Counted, never linked.
 */
export const whiteLabelFlavours = ${JSON.stringify(WHITE_LABEL_TEMPLATES, null, 2)} as const;

export const storeGeneratedAt = ${JSON.stringify(new Date().toISOString().slice(0, 10))};
`;

const target = resolve(process.cwd(), "src/data/store.ts");
writeFileSync(target, out);
console.log(
  `[gen-store] wrote ${live.length} live listing(s): ${live.map((l) => `${l.name} ${l.rating ?? "?"}★`).join(" · ")}`,
);
