/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as ChessRouteImport } from './routes/chess'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as ExcelsiorRouteImport } from './routes/excelsior'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as HireRouteImport } from './routes/hire'
import { Route as InkRouteImport } from './routes/ink'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LoopdownRouteImport } from './routes/loopdown'
import { Route as MapRouteImport } from './routes/map'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ShippedRouteImport } from './routes/shipped'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as WeebRouteImport } from './routes/weeb'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as ReadSlugRouteImport } from './routes/read.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessRoute = ChessRouteImport.update({
  id: '/chess',
  path: '/chess',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcelsiorRoute = ExcelsiorRouteImport.update({
  id: '/excelsior',
  path: '/excelsior',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const InkRoute = InkRouteImport.update({
  id: '/ink',
  path: '/ink',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopdownRoute = LoopdownRouteImport.update({
  id: '/loopdown',
  path: '/loopdown',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippedRoute = ShippedRouteImport.update({
  id: '/shipped',
  path: '/shipped',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const WeebRoute = WeebRouteImport.update({
  id: '/weeb',
  path: '/weeb',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSlugRoute = ReadSlugRouteImport.update({
  id: '/read/$slug',
  path: '/read/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blueprint': typeof BlueprintRoute
  '/chess': typeof ChessRoute
  '/compose': typeof ComposeRoute
  '/excelsior': typeof ExcelsiorRoute
  '/forge': typeof ForgeRoute
  '/hire': typeof HireRoute
  '/ink': typeof InkRoute
  '/lab': typeof LabRoute
  '/loopdown': typeof LoopdownRoute
  '/map': typeof MapRoute
  '/playground': typeof PlaygroundRoute
  '/pulse': typeof PulseRoute
  '/resume': typeof ResumeRoute
  '/shipped': typeof ShippedRoute
  '/terminal': typeof TerminalRoute
  '/weeb': typeof WeebRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/read/$slug': typeof ReadSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blueprint': typeof BlueprintRoute
  '/chess': typeof ChessRoute
  '/compose': typeof ComposeRoute
  '/excelsior': typeof ExcelsiorRoute
  '/forge': typeof ForgeRoute
  '/hire': typeof HireRoute
  '/ink': typeof InkRoute
  '/lab': typeof LabRoute
  '/loopdown': typeof LoopdownRoute
  '/map': typeof MapRoute
  '/playground': typeof PlaygroundRoute
  '/pulse': typeof PulseRoute
  '/resume': typeof ResumeRoute
  '/shipped': typeof ShippedRoute
  '/terminal': typeof TerminalRoute
  '/weeb': typeof WeebRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/read/$slug': typeof ReadSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blueprint': typeof BlueprintRoute
  '/chess': typeof ChessRoute
  '/compose': typeof ComposeRoute
  '/excelsior': typeof ExcelsiorRoute
  '/forge': typeof ForgeRoute
  '/hire': typeof HireRoute
  '/ink': typeof InkRoute
  '/lab': typeof LabRoute
  '/loopdown': typeof LoopdownRoute
  '/map': typeof MapRoute
  '/playground': typeof PlaygroundRoute
  '/pulse': typeof PulseRoute
  '/resume': typeof ResumeRoute
  '/shipped': typeof ShippedRoute
  '/terminal': typeof TerminalRoute
  '/weeb': typeof WeebRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/read/$slug': typeof ReadSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/blueprint'
    | '/chess'
    | '/compose'
    | '/excelsior'
    | '/forge'
    | '/hire'
    | '/ink'
    | '/lab'
    | '/loopdown'
    | '/map'
    | '/playground'
    | '/pulse'
    | '/resume'
    | '/shipped'
    | '/terminal'
    | '/weeb'
    | '/project/$slug'
    | '/read/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/blueprint'
    | '/chess'
    | '/compose'
    | '/excelsior'
    | '/forge'
    | '/hire'
    | '/ink'
    | '/lab'
    | '/loopdown'
    | '/map'
    | '/playground'
    | '/pulse'
    | '/resume'
    | '/shipped'
    | '/terminal'
    | '/weeb'
    | '/project/$slug'
    | '/read/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/blueprint'
    | '/chess'
    | '/compose'
    | '/excelsior'
    | '/forge'
    | '/hire'
    | '/ink'
    | '/lab'
    | '/loopdown'
    | '/map'
    | '/playground'
    | '/pulse'
    | '/resume'
    | '/shipped'
    | '/terminal'
    | '/weeb'
    | '/project/$slug'
    | '/read/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BlueprintRoute: typeof BlueprintRoute
  ChessRoute: typeof ChessRoute
  ComposeRoute: typeof ComposeRoute
  ExcelsiorRoute: typeof ExcelsiorRoute
  ForgeRoute: typeof ForgeRoute
  HireRoute: typeof HireRoute
  InkRoute: typeof InkRoute
  LabRoute: typeof LabRoute
  LoopdownRoute: typeof LoopdownRoute
  MapRoute: typeof MapRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PulseRoute: typeof PulseRoute
  ResumeRoute: typeof ResumeRoute
  ShippedRoute: typeof ShippedRoute
  TerminalRoute: typeof TerminalRoute
  WeebRoute: typeof WeebRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  ReadSlugRoute: typeof ReadSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess': {
      id: '/chess'
      path: '/chess'
      fullPath: '/chess'
      preLoaderRoute: typeof ChessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excelsior': {
      id: '/excelsior'
      path: '/excelsior'
      fullPath: '/excelsior'
      preLoaderRoute: typeof ExcelsiorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ink': {
      id: '/ink'
      path: '/ink'
      fullPath: '/ink'
      preLoaderRoute: typeof InkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loopdown': {
      id: '/loopdown'
      path: '/loopdown'
      fullPath: '/loopdown'
      preLoaderRoute: typeof LoopdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipped': {
      id: '/shipped'
      path: '/shipped'
      fullPath: '/shipped'
      preLoaderRoute: typeof ShippedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeb': {
      id: '/weeb'
      path: '/weeb'
      fullPath: '/weeb'
      preLoaderRoute: typeof WeebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$slug': {
      id: '/read/$slug'
      path: '/read/$slug'
      fullPath: '/read/$slug'
      preLoaderRoute: typeof ReadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BlueprintRoute: BlueprintRoute,
  ChessRoute: ChessRoute,
  ComposeRoute: ComposeRoute,
  ExcelsiorRoute: ExcelsiorRoute,
  ForgeRoute: ForgeRoute,
  HireRoute: HireRoute,
  InkRoute: InkRoute,
  LabRoute: LabRoute,
  LoopdownRoute: LoopdownRoute,
  MapRoute: MapRoute,
  PlaygroundRoute: PlaygroundRoute,
  PulseRoute: PulseRoute,
  ResumeRoute: ResumeRoute,
  ShippedRoute: ShippedRoute,
  TerminalRoute: TerminalRoute,
  WeebRoute: WeebRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  ReadSlugRoute: ReadSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
