// Split from profile.ts along its export seams (arch-L15) — derives
// from projectCards.ts (the light projection), not projects.ts, so a
// route that only wants a thumbnail never pulls in the heavy case-study
// prose it doesn't render.
import { projectCards } from "./projectCards.ts";

/* ── Card thumbnails ──────────────────────────────────────────────────────
 * One thumbnail per project, from the daily-synced media. Lives here (not in
 * App.tsx, where it started) because two renderers need the same picture: the
 * home-page project grid and the AI assistant's inline project card
 * (src/ChatWidgets.tsx) — a second hand-maintained map is how thumbnails drift.
 */
/**
 * The banner each project card shows — authored, not screenshotted.
 *
 * Generated by scripts/gen-project-heroes.mjs from this same file's data, in
 * each project's own `theme` palette. Two rounds of trying to make screenshots
 * work here established why they can't:
 *
 *   1. Animated GIFs made the card a player. It showed whichever frame the loop
 *      landed on — multiplatform.gif is 108 frames across phone, watch and
 *      widgets, and 3 of 4 sampled frames rendered as a near-black watch face
 *      or empty space. paymentslab-kmp's checkout GIF opened on its FLAG_SECURE
 *      "screenshots blocked" screen: a great security story, a terrible
 *      thumbnail.
 *   2. Static screenshots fixed the randomness but not the shape. A tall phone
 *      screen seen through a ~2.7:1 band is one arbitrary horizontal slice, and
 *      the best available slice was still a Coverage table or an empty chart
 *      region — pixels that say nothing about what the project is. Two of the
 *      products are also light-themed, so they fought the dark page whatever
 *      the crop.
 *
 * A hero is correct by construction: right aspect, right palette, and it
 * carries the facts that earn attention (46 modules, 5 platforms, 66 gateways)
 * instead of whatever the app happened to be rendering. No focal point is
 * needed any more — the image IS the card's shape.
 *
 * `src` is the ORIGINAL raster; Picture derives the .avif/.webp siblings, so
 * pointing this at an .avif directly would break that chain.
 *
 * DERIVED, not hand-kept. This was a literal map of six slugs while
 * gen-project-heroes.mjs rendered a banner for every project in the registry,
 * so `kmp-family` and `the-loopdown` had heroes sitting on disk and cards that
 * rendered without one — two of eight cards visibly shorter than their
 * neighbours for no reason a reader could see. Deriving it from `projects` is
 * the same fix applied to the service worker's bypass list and vercel.json's
 * cache rules: the shape is known, so nothing has to remember to update a
 * second list. Guarded by cardMedia.test.ts.
 */
export const cardMedia: Record<string, { src: string; alt: string }> = Object.fromEntries(
  projectCards.map((p) => [
    p.slug,
    {
      src: `/projects/_heroes/${p.slug}.png`,
      // The status line already reads "46 modules · 5 platforms · 159 tests";
      // it is the same sentence this alt text used to hand-write per project,
      // and it cannot go stale against the card beside it.
      alt: `${p.name}: ${p.status}`,
    },
  ]),
);

