// GENERATED by scripts/gen-chess-stats.mjs — do not edit by hand.
// Hand-editing breaks the property that this file IS the claim audit for
// the chess section: every figure here traces to a live API response.
// Regenerate with: npm run gen:chess

export type ChessData = typeof chess;

export const chess = {
  "generatedAt": "2026-08-29T13:19:39.696Z",
  "username": "darkpandawarrior",
  "totals": {
    "games": 18938,
    "wins": 9219,
    "losses": 9247,
    "draws": 472,
    "hours": 763
  },
  "boardTime": {
    "scope": "both platforms, two measurements",
    "lichessHours": 763,
    "chesscomHours": 287,
    "combinedHours": 1050,
    "note": "lichess self-reports playTime.total; the chess.com half is derived from live-game PGN wall clock (UTCDate/StartTime to EndDate/EndTime). Two measurement methods, not one uniform metric.",
    "chesscom": {
      "games": 4515,
      "skipped": 0,
      "excludedDaily": 304,
      "byClass": {
        "bullet": 28.7,
        "blitz": 243.4,
        "rapid": 14.8
      },
      "meanMinutes": 3.8
    }
  },
  "length": {
    "scope": "chess.com",
    "games": 4515,
    "median": 31,
    "mean": 33.928,
    "max": 90,
    "winMedian": 29,
    "lossMedian": 33,
    "buckets": [
      {
        "lo": 0,
        "hi": 20,
        "n": 669,
        "winRate": 0.59,
        "flagShareOfLosses": 0.142
      },
      {
        "lo": 20,
        "hi": 30,
        "n": 1296,
        "winRate": 0.563,
        "flagShareOfLosses": 0.326
      },
      {
        "lo": 30,
        "hi": 40,
        "n": 1195,
        "winRate": 0.487,
        "flagShareOfLosses": 0.367
      },
      {
        "lo": 40,
        "hi": 50,
        "n": 576,
        "winRate": 0.465,
        "flagShareOfLosses": 0.338
      },
      {
        "lo": 50,
        "hi": 60,
        "n": 368,
        "winRate": 0.37,
        "flagShareOfLosses": 0.388
      },
      {
        "lo": 60,
        "hi": null,
        "n": 239,
        "winRate": 0.268,
        "flagShareOfLosses": 0.314
      }
    ],
    "decided": 4343
  },
  "material": {
    "scope": "chess.com",
    "winMedian": 39,
    "lossMedian": 33,
    "fullBoard": 78
  },
  "firstMoveWhite": {
    "scope": "chess.com",
    "moves": [
      {
        "move": "d4",
        "n": 1666
      },
      {
        "move": "g3",
        "n": 279
      },
      {
        "move": "Nf3",
        "n": 136
      },
      {
        "move": "d3",
        "n": 113
      },
      {
        "move": "e4",
        "n": 75
      },
      {
        "move": "b3",
        "n": 50
      }
    ]
  },
  "clutch": {
    "scope": "chess.com",
    "n": 541,
    "wins": 160,
    "rate": 0.296
  },
  "checkmate": {
    "scope": "chess.com",
    "delivered": 685,
    "received": 1026
  },
  "span": {
    "from": "2019-02-09",
    "to": "2026-08-29"
  },
  "activityByYear": [
    {
      "year": "2019",
      "lichess": 2480,
      "chesscom": 0
    },
    {
      "year": "2020",
      "lichess": 3262,
      "chesscom": 0
    },
    {
      "year": "2021",
      "lichess": 4672,
      "chesscom": 19
    },
    {
      "year": "2022",
      "lichess": 3365,
      "chesscom": 0
    },
    {
      "year": "2023",
      "lichess": 337,
      "chesscom": 2017
    },
    {
      "year": "2024",
      "lichess": 0,
      "chesscom": 1043
    },
    {
      "year": "2025",
      "lichess": 3,
      "chesscom": 590
    },
    {
      "year": "2026",
      "lichess": 0,
      "chesscom": 1150
    }
  ],
  "platforms": [
    {
      "id": "lichess",
      "url": "https://lichess.org/@/darkpandawarrior",
      "joined": "2019-02-06",
      "lastActive": "2025-01-16",
      "games": 14119,
      "peaks": [
        {
          "format": "bullet",
          "rating": 1662,
          "at": "2019-02-09"
        },
        {
          "format": "blitz",
          "rating": 1686,
          "at": "2020-08-03"
        },
        {
          "format": "rapid",
          "rating": 1552,
          "at": "2019-11-24"
        }
      ],
      "provisional": true,
      "puzzles": {
        "peak": 1661,
        "last": 1661,
        "solved": 3515
      }
    },
    {
      "id": "chess.com",
      "url": "https://www.chess.com/member/darkpandawarrior",
      "joined": "2021-01-22",
      "lastActive": "2026-08-29",
      "games": 4819,
      "peaks": [
        {
          "format": "blitz",
          "rating": 1425,
          "at": "2025-10-20"
        },
        {
          "format": "bullet",
          "rating": 1225,
          "at": "2023-01-26"
        },
        {
          "format": "rapid",
          "rating": 1307,
          "at": "2025-10-15"
        }
      ],
      "provisional": false,
      "puzzles": null
    }
  ],
  "thesis": {
    "decidedOnClock": 0.416,
    "lossesOnTime": 0.5,
    "winsOnTime": 0.331,
    "deciles": [
      {
        "bucket": 0,
        "win": 0.99,
        "loss": 0.987,
        "gap": 0.003
      },
      {
        "bucket": 1,
        "win": 0.951,
        "loss": 0.934,
        "gap": 0.017
      },
      {
        "bucket": 2,
        "win": 0.892,
        "loss": 0.858,
        "gap": 0.034
      },
      {
        "bucket": 3,
        "win": 0.821,
        "loss": 0.768,
        "gap": 0.053
      },
      {
        "bucket": 4,
        "win": 0.746,
        "loss": 0.677,
        "gap": 0.068
      },
      {
        "bucket": 5,
        "win": 0.671,
        "loss": 0.592,
        "gap": 0.079
      },
      {
        "bucket": 6,
        "win": 0.588,
        "loss": 0.501,
        "gap": 0.087
      },
      {
        "bucket": 7,
        "win": 0.508,
        "loss": 0.421,
        "gap": 0.087
      },
      {
        "bucket": 8,
        "win": 0.439,
        "loss": 0.356,
        "gap": 0.083
      },
      {
        "bucket": 9,
        "win": 0.37,
        "loss": 0.286,
        "gap": 0.083
      }
    ],
    "sampleSize": 3262
  },
  "discipline": {
    "distinctDays": 2292,
    "spanDays": 2759,
    "longestDayStreak": 298,
    "longestWin": 12,
    "longestLoss": 14
  },
  "tilt": {
    "afterWin": 0.503,
    "afterLoss": 0.469,
    "n": 8355
  },
  "sessionDecay": [
    {
      "position": 1,
      "winRate": 0.485,
      "n": 10348
    },
    {
      "position": 2,
      "winRate": 0.486,
      "n": 4209
    },
    {
      "position": 3,
      "winRate": 0.488,
      "n": 2013
    },
    {
      "position": 4,
      "winRate": 0.528,
      "n": 1012
    },
    {
      "position": 5,
      "winRate": 0.485,
      "n": 551
    },
    {
      "position": 6,
      "winRate": 0.482,
      "n": 309
    },
    {
      "position": 7,
      "winRate": 0.457,
      "n": 184
    },
    {
      "position": 8,
      "winRate": 0.5,
      "n": 122
    },
    {
      "position": 9,
      "winRate": 0.348,
      "n": 69
    },
    {
      "position": 10,
      "winRate": 0.6,
      "n": 40
    },
    {
      "position": 11,
      "winRate": 0.323,
      "n": 31
    },
    {
      "position": 12,
      "winRate": 0.421,
      "n": 19
    }
  ],
  "repertoire": [
    {
      "year": "2019",
      "openings": [
        {
          "name": "Scandinavian Defense Mieses Kotrc Variation",
          "count": 319,
          "share": 0.263
        },
        {
          "name": "Scandinavian Defense",
          "count": 122,
          "share": 0.1
        },
        {
          "name": "Queens Pawn Game",
          "count": 71,
          "share": 0.058
        },
        {
          "name": "Goldsmith Defense",
          "count": 69,
          "share": 0.057
        },
        {
          "name": "Ware Defense",
          "count": 48,
          "share": 0.04
        }
      ]
    },
    {
      "year": "2020",
      "openings": [
        {
          "name": "Modern Defense",
          "count": 583,
          "share": 0.358
        },
        {
          "name": "Queens Pawn Game Modern Defense",
          "count": 196,
          "share": 0.12
        },
        {
          "name": "Scandinavian Defense Mieses Kotrc Variation",
          "count": 149,
          "share": 0.091
        },
        {
          "name": "Owen Defense",
          "count": 81,
          "share": 0.05
        },
        {
          "name": "Scandinavian Defense",
          "count": 56,
          "share": 0.034
        }
      ]
    },
    {
      "year": "2021",
      "openings": [
        {
          "name": "Modern Defense",
          "count": 1277,
          "share": 0.545
        },
        {
          "name": "Queens Pawn Game Modern Defense",
          "count": 517,
          "share": 0.221
        },
        {
          "name": "Zukertort Opening Kingside Fianchetto",
          "count": 75,
          "share": 0.032
        },
        {
          "name": "Modern Defense Standard Line",
          "count": 69,
          "share": 0.029
        },
        {
          "name": "Vant Kruijs Opening",
          "count": 65,
          "share": 0.028
        }
      ]
    },
    {
      "year": "2022",
      "openings": [
        {
          "name": "Modern Defense",
          "count": 858,
          "share": 0.512
        },
        {
          "name": "Queens Pawn Game Modern Defense",
          "count": 389,
          "share": 0.232
        },
        {
          "name": "Zukertort Opening Kingside Fianchetto",
          "count": 61,
          "share": 0.036
        },
        {
          "name": "English Opening Great Snake Variation",
          "count": 53,
          "share": 0.032
        },
        {
          "name": "Nimzo Larsen Attack",
          "count": 53,
          "share": 0.032
        }
      ]
    },
    {
      "year": "2023",
      "openings": [
        {
          "name": "Modern Defense",
          "count": 248,
          "share": 0.211
        },
        {
          "name": "Scandinavian Defense Mieses Kotrc Variation",
          "count": 170,
          "share": 0.145
        },
        {
          "name": "Scandinavian Defense",
          "count": 70,
          "share": 0.06
        },
        {
          "name": "Modern Defense with 1 d4",
          "count": 67,
          "share": 0.057
        },
        {
          "name": "Reti Opening Kingside Fianchetto Variation",
          "count": 44,
          "share": 0.037
        }
      ]
    },
    {
      "year": "2024",
      "openings": [
        {
          "name": "Scandinavian Defense Mieses Kotrc Variation",
          "count": 89,
          "share": 0.172
        },
        {
          "name": "Nimzowitsch Defense",
          "count": 29,
          "share": 0.056
        },
        {
          "name": "Scandinavian Defense",
          "count": 21,
          "share": 0.041
        },
        {
          "name": "Nimzowitsch Defense Declined",
          "count": 18,
          "share": 0.035
        },
        {
          "name": "Queens Pawn Opening Mikenas Defense",
          "count": 17,
          "share": 0.033
        }
      ]
    },
    {
      "year": "2025",
      "openings": [
        {
          "name": "Scandinavian Defense Mieses Kotrc Variation",
          "count": 43,
          "share": 0.145
        },
        {
          "name": "Van t Kruijs Opening",
          "count": 12,
          "share": 0.041
        },
        {
          "name": "Scandinavian Defense",
          "count": 10,
          "share": 0.034
        },
        {
          "name": "Nimzowitsch Defense",
          "count": 10,
          "share": 0.034
        },
        {
          "name": "Queens Pawn Opening Zukertort Chigorin Variation",
          "count": 10,
          "share": 0.034
        }
      ]
    },
    {
      "year": "2026",
      "openings": [
        {
          "name": "Scandinavian Defense Mieses Kotrc Variation",
          "count": 157,
          "share": 0.272
        },
        {
          "name": "Scandinavian Defense",
          "count": 38,
          "share": 0.066
        },
        {
          "name": "Queens Pawn Opening",
          "count": 19,
          "share": 0.033
        },
        {
          "name": "French Defense Advance Variation",
          "count": 16,
          "share": 0.028
        },
        {
          "name": "Queens Pawn Opening Zukertort Chigorin Variation",
          "count": 15,
          "share": 0.026
        }
      ]
    }
  ],
  "colour": {
    "white": {
      "games": 9472,
      "winRate": 0.49
    },
    "black": {
      "games": 9466,
      "winRate": 0.483
    }
  },
  "accuracy": {
    "mean": 70.143,
    "inWins": 73.757,
    "inLosses": 64.154,
    "covered": 375,
    "total": 4819
  },
  "bestUpset": {
    "opRating": 1867,
    "myRating": 1078,
    "gap": 789,
    "at": "2019-03-07",
    "platform": "lichess",
    "speed": "rapid"
  },
  "puzzle": {
    "id": "Zjt5N",
    "fen": "4r1rk/3q1p1p/p4PpQ/2p5/3p4/3R4/PP3PPP/4R1K1 w - - 1 1",
    "solution": [
      "e1e8",
      "d7e8",
      "h6h7",
      "h8h7",
      "d3h3"
    ],
    "rating": 1983,
    "themes": [
      "endgame",
      "attraction",
      "long",
      "mateIn3",
      "sacrifice",
      "kingsideAttack"
    ],
    "lastMove": "a8e8"
  },
  "arc": [
    {
      "platform": "chess.com",
      "format": "blitz",
      "points": [
        {
          "t": 1611406227000,
          "r": 1035
        },
        {
          "t": 1612104299000,
          "r": 1153
        },
        {
          "t": 1689399824000,
          "r": 1272
        },
        {
          "t": 1690541422000,
          "r": 1332
        },
        {
          "t": 1691218572000,
          "r": 1340
        },
        {
          "t": 1691691007000,
          "r": 1420
        },
        {
          "t": 1692351529000,
          "r": 1376
        },
        {
          "t": 1692870076000,
          "r": 1409
        },
        {
          "t": 1693230474000,
          "r": 1401
        },
        {
          "t": 1694154896000,
          "r": 1391
        },
        {
          "t": 1694430927000,
          "r": 1400
        },
        {
          "t": 1695402037000,
          "r": 1377
        },
        {
          "t": 1696175561000,
          "r": 1397
        },
        {
          "t": 1696316331000,
          "r": 1389
        },
        {
          "t": 1697317404000,
          "r": 1392
        },
        {
          "t": 1697856641000,
          "r": 1408
        },
        {
          "t": 1698684273000,
          "r": 1373
        },
        {
          "t": 1698999493000,
          "r": 1328
        },
        {
          "t": 1700088106000,
          "r": 1316
        },
        {
          "t": 1700608076000,
          "r": 1301
        },
        {
          "t": 1701313037000,
          "r": 1349
        },
        {
          "t": 1701800156000,
          "r": 1149
        },
        {
          "t": 1702837210000,
          "r": 1170
        },
        {
          "t": 1703505806000,
          "r": 1163
        },
        {
          "t": 1704703456000,
          "r": 1153
        },
        {
          "t": 1705485528000,
          "r": 1200
        },
        {
          "t": 1706080976000,
          "r": 1216
        },
        {
          "t": 1706803902000,
          "r": 1247
        },
        {
          "t": 1707730035000,
          "r": 1272
        },
        {
          "t": 1708404033000,
          "r": 1334
        },
        {
          "t": 1708592878000,
          "r": 1318
        },
        {
          "t": 1709701223000,
          "r": 1285
        },
        {
          "t": 1710336000000,
          "r": 1303
        },
        {
          "t": 1710538263000,
          "r": 1304
        },
        {
          "t": 1711130136000,
          "r": 1287
        },
        {
          "t": 1712292381000,
          "r": 1284
        },
        {
          "t": 1712905401000,
          "r": 1368
        },
        {
          "t": 1713466604000,
          "r": 1346
        },
        {
          "t": 1713882021000,
          "r": 1352
        },
        {
          "t": 1714816041000,
          "r": 1382
        },
        {
          "t": 1715117069000,
          "r": 1377
        },
        {
          "t": 1715577598000,
          "r": 1369
        },
        {
          "t": 1716288223000,
          "r": 1318
        },
        {
          "t": 1717345657000,
          "r": 1336
        },
        {
          "t": 1717448367000,
          "r": 1346
        },
        {
          "t": 1718629348000,
          "r": 1353
        },
        {
          "t": 1718717602000,
          "r": 1340
        },
        {
          "t": 1719699565000,
          "r": 1257
        },
        {
          "t": 1720163405000,
          "r": 1259
        },
        {
          "t": 1721319065000,
          "r": 1329
        },
        {
          "t": 1721460941000,
          "r": 1362
        },
        {
          "t": 1722069091000,
          "r": 1260
        },
        {
          "t": 1722751285000,
          "r": 1224
        },
        {
          "t": 1723987448000,
          "r": 1234
        },
        {
          "t": 1724429824000,
          "r": 1268
        },
        {
          "t": 1725394218000,
          "r": 1303
        },
        {
          "t": 1725983503000,
          "r": 1301
        },
        {
          "t": 1726375960000,
          "r": 1276
        },
        {
          "t": 1727271879000,
          "r": 1322
        },
        {
          "t": 1727898952000,
          "r": 1317
        },
        {
          "t": 1728398036000,
          "r": 1316
        },
        {
          "t": 1728742977000,
          "r": 1272
        },
        {
          "t": 1729348181000,
          "r": 1239
        },
        {
          "t": 1730277870000,
          "r": 1243
        },
        {
          "t": 1731038240000,
          "r": 1253
        },
        {
          "t": 1731678253000,
          "r": 1252
        },
        {
          "t": 1732887382000,
          "r": 1245
        },
        {
          "t": 1733232129000,
          "r": 1170
        },
        {
          "t": 1734511355000,
          "r": 1167
        },
        {
          "t": 1734783910000,
          "r": 1169
        },
        {
          "t": 1737054231000,
          "r": 1168
        },
        {
          "t": 1737346678000,
          "r": 1173
        },
        {
          "t": 1738230739000,
          "r": 1181
        },
        {
          "t": 1739109361000,
          "r": 1189
        },
        {
          "t": 1739624621000,
          "r": 1178
        },
        {
          "t": 1740334776000,
          "r": 1164
        },
        {
          "t": 1741937695000,
          "r": 1173
        },
        {
          "t": 1744100167000,
          "r": 1184
        },
        {
          "t": 1745246678000,
          "r": 1196
        },
        {
          "t": 1745507424000,
          "r": 1186
        },
        {
          "t": 1746472514000,
          "r": 1193
        },
        {
          "t": 1747928091000,
          "r": 1232
        },
        {
          "t": 1749389242000,
          "r": 1234
        },
        {
          "t": 1750055998000,
          "r": 1223
        },
        {
          "t": 1750777338000,
          "r": 1192
        },
        {
          "t": 1752308173000,
          "r": 1189
        },
        {
          "t": 1753078808000,
          "r": 1197
        },
        {
          "t": 1753704569000,
          "r": 1206
        },
        {
          "t": 1755120384000,
          "r": 1240
        },
        {
          "t": 1755180712000,
          "r": 1248
        },
        {
          "t": 1755853183000,
          "r": 1240
        },
        {
          "t": 1757091201000,
          "r": 1240
        },
        {
          "t": 1757477512000,
          "r": 1240
        },
        {
          "t": 1758730653000,
          "r": 1231
        },
        {
          "t": 1760169156000,
          "r": 1288
        },
        {
          "t": 1760815383000,
          "r": 1407
        },
        {
          "t": 1760932237000,
          "r": 1425
        },
        {
          "t": 1761466374000,
          "r": 1344
        },
        {
          "t": 1762650359000,
          "r": 1341
        },
        {
          "t": 1763420278000,
          "r": 1334
        },
        {
          "t": 1763458204000,
          "r": 1342
        },
        {
          "t": 1764800534000,
          "r": 1292
        },
        {
          "t": 1766669006000,
          "r": 1318
        },
        {
          "t": 1767338319000,
          "r": 1333
        },
        {
          "t": 1767799702000,
          "r": 1342
        },
        {
          "t": 1768316860000,
          "r": 1318
        },
        {
          "t": 1769016108000,
          "r": 1303
        },
        {
          "t": 1769874598000,
          "r": 1294
        },
        {
          "t": 1770700245000,
          "r": 1247
        },
        {
          "t": 1771760089000,
          "r": 1255
        },
        {
          "t": 1772968989000,
          "r": 1295
        },
        {
          "t": 1773992903000,
          "r": 1341
        },
        {
          "t": 1774601540000,
          "r": 1349
        },
        {
          "t": 1775207962000,
          "r": 1382
        },
        {
          "t": 1775725912000,
          "r": 1405
        },
        {
          "t": 1775924833000,
          "r": 1380
        },
        {
          "t": 1777034673000,
          "r": 1309
        },
        {
          "t": 1777054265000,
          "r": 1308
        },
        {
          "t": 1777722538000,
          "r": 1217
        },
        {
          "t": 1779115028000,
          "r": 1258
        },
        {
          "t": 1779183665000,
          "r": 1249
        },
        {
          "t": 1780922920000,
          "r": 1314
        },
        {
          "t": 1781520085000,
          "r": 1316
        },
        {
          "t": 1781724899000,
          "r": 1358
        },
        {
          "t": 1782597736000,
          "r": 1303
        },
        {
          "t": 1783431637000,
          "r": 1299
        },
        {
          "t": 1783606680000,
          "r": 1297
        },
        {
          "t": 1784648431000,
          "r": 1282
        },
        {
          "t": 1784726042000,
          "r": 1314
        },
        {
          "t": 1785613112000,
          "r": 1331
        },
        {
          "t": 1786382063000,
          "r": 1373
        },
        {
          "t": 1786706996000,
          "r": 1347
        },
        {
          "t": 1787490296000,
          "r": 1298
        },
        {
          "t": 1787839212000,
          "r": 1251
        },
        {
          "t": 1787993783000,
          "r": 1247
        }
      ]
    },
    {
      "platform": "chess.com",
      "format": "bullet",
      "points": [
        {
          "t": 1611324757000,
          "r": 967
        },
        {
          "t": 1611725128000,
          "r": 1165
        },
        {
          "t": 1612069872000,
          "r": 1152
        },
        {
          "t": 1613315539000,
          "r": 1133
        },
        {
          "t": 1614082928000,
          "r": 1116
        },
        {
          "t": 1674728368000,
          "r": 1225
        },
        {
          "t": 1675512042000,
          "r": 1186
        },
        {
          "t": 1675957184000,
          "r": 1181
        },
        {
          "t": 1676810013000,
          "r": 1132
        },
        {
          "t": 1677185891000,
          "r": 1159
        },
        {
          "t": 1677778258000,
          "r": 1102
        },
        {
          "t": 1678418757000,
          "r": 1064
        },
        {
          "t": 1679403310000,
          "r": 1044
        },
        {
          "t": 1680352281000,
          "r": 1070
        },
        {
          "t": 1680356049000,
          "r": 1069
        },
        {
          "t": 1680961744000,
          "r": 1005
        },
        {
          "t": 1681745146000,
          "r": 972
        },
        {
          "t": 1682530370000,
          "r": 980
        },
        {
          "t": 1683369480000,
          "r": 962
        },
        {
          "t": 1683562078000,
          "r": 962
        },
        {
          "t": 1684627943000,
          "r": 954
        },
        {
          "t": 1684833660000,
          "r": 937
        },
        {
          "t": 1685625164000,
          "r": 773
        },
        {
          "t": 1686596206000,
          "r": 864
        },
        {
          "t": 1686991834000,
          "r": 918
        },
        {
          "t": 1687343375000,
          "r": 883
        },
        {
          "t": 1688274374000,
          "r": 836
        },
        {
          "t": 1688586167000,
          "r": 784
        },
        {
          "t": 1689345612000,
          "r": 753
        },
        {
          "t": 1690740739000,
          "r": 744
        },
        {
          "t": 1700142493000,
          "r": 730
        },
        {
          "t": 1700147512000,
          "r": 718
        }
      ]
    },
    {
      "platform": "chess.com",
      "format": "rapid",
      "points": [
        {
          "t": 1687235532000,
          "r": 1069
        },
        {
          "t": 1689346137000,
          "r": 963
        },
        {
          "t": 1692103738000,
          "r": 914
        },
        {
          "t": 1693640049000,
          "r": 1034
        },
        {
          "t": 1696066682000,
          "r": 1028
        },
        {
          "t": 1699731423000,
          "r": 1052
        },
        {
          "t": 1700341443000,
          "r": 1044
        },
        {
          "t": 1704006303000,
          "r": 1082
        },
        {
          "t": 1704986831000,
          "r": 1075
        },
        {
          "t": 1708195185000,
          "r": 1070
        },
        {
          "t": 1710076155000,
          "r": 1061
        },
        {
          "t": 1720162584000,
          "r": 1092
        },
        {
          "t": 1725714322000,
          "r": 1117
        },
        {
          "t": 1733607720000,
          "r": 1108
        },
        {
          "t": 1734615718000,
          "r": 1221
        },
        {
          "t": 1735817771000,
          "r": 1235
        },
        {
          "t": 1737286275000,
          "r": 1202
        },
        {
          "t": 1746084139000,
          "r": 1227
        },
        {
          "t": 1755341806000,
          "r": 1266
        },
        {
          "t": 1760532263000,
          "r": 1307
        },
        {
          "t": 1765878828000,
          "r": 1240
        },
        {
          "t": 1780406771000,
          "r": 1242
        },
        {
          "t": 1780407480000,
          "r": 1175
        }
      ]
    }
  ]
} as const;
