// AUTO-GENERATED by scripts/gen-chess-deep.mjs — do not edit by hand.
// Second-pass mining of fields the first pass never read: how the game was
// found, which time control, how it ended, and when the opening book ran out.
export const chessDeep = {
  "generatedAt": "2026-08-28T09:46:53.586Z",
  "lastSeenOnLichess": "2026-07-30",
  "sampleSize": 14119,
  "bySource": [
    {
      "source": "pool",
      "n": 13730,
      "winRate": 49.2
    },
    {
      "source": "arena",
      "n": 163,
      "winRate": 28.2
    },
    {
      "source": "lobby",
      "n": 117,
      "winRate": 29.1
    },
    {
      "source": "friend",
      "n": 104,
      "winRate": 59.6
    }
  ],
  "byTimeControl": [
    {
      "tc": "1+0",
      "n": 9653,
      "winRate": 49.4
    },
    {
      "tc": "5+0",
      "n": 3977,
      "winRate": 48.2
    },
    {
      "tc": "10+0",
      "n": 262,
      "winRate": 48.9
    }
  ],
  "byEnding": [
    {
      "status": "outoftime",
      "n": 6941,
      "share": 49.2
    },
    {
      "status": "mate",
      "n": 4059,
      "share": 28.7
    },
    {
      "status": "resign",
      "n": 2753,
      "share": 19.5
    },
    {
      "status": "timeout",
      "n": 145,
      "share": 1
    },
    {
      "status": "stalemate",
      "n": 92,
      "share": 0.7
    },
    {
      "status": "draw",
      "n": 92,
      "share": 0.7
    }
  ],
  "book": {
    "medianPly": 2,
    "deep": {
      "n": 109,
      "winRate": 54.1
    },
    "shallow": {
      "n": 12990,
      "winRate": 48.9
    }
  }
} as const;
