// AUTO-GENERATED by scripts/gen-compare-sets.mjs — do not edit by hand.
// Add versions under public/projects/<slug>/compare/<set>/N-label.png and they appear automatically.
export type CompareLayer = { src: string; label: string };
export const compareSets: Record<string, Record<string, CompareLayer[]>> = {
  "mileway": {
    "approvals": [
      {
        "src": "/projects/mileway/compare/approvals/1-ledger.png",
        "label": "ledger"
      },
      {
        "src": "/projects/mileway/compare/approvals/2-instrument.png",
        "label": "instrument"
      },
      {
        "src": "/projects/mileway/compare/approvals/3-signal.png",
        "label": "signal"
      },
      {
        "src": "/projects/mileway/compare/approvals/4-refined-ember.png",
        "label": "refined ember"
      },
      {
        "src": "/projects/mileway/compare/approvals/5-paper.png",
        "label": "paper"
      }
    ],
    "drive-review": [
      {
        "src": "/projects/mileway/compare/drive-review/1-ledger.png",
        "label": "ledger"
      },
      {
        "src": "/projects/mileway/compare/drive-review/2-instrument.png",
        "label": "instrument"
      },
      {
        "src": "/projects/mileway/compare/drive-review/3-signal.png",
        "label": "signal"
      },
      {
        "src": "/projects/mileway/compare/drive-review/4-refined-ember.png",
        "label": "refined ember"
      },
      {
        "src": "/projects/mileway/compare/drive-review/5-paper.png",
        "label": "paper"
      }
    ],
    "expense": [
      {
        "src": "/projects/mileway/compare/expense/1-ledger.png",
        "label": "ledger"
      },
      {
        "src": "/projects/mileway/compare/expense/2-instrument.png",
        "label": "instrument"
      },
      {
        "src": "/projects/mileway/compare/expense/3-signal.png",
        "label": "signal"
      },
      {
        "src": "/projects/mileway/compare/expense/4-refined-ember.png",
        "label": "refined ember"
      },
      {
        "src": "/projects/mileway/compare/expense/5-paper.png",
        "label": "paper"
      }
    ],
    "journey-guide": [
      {
        "src": "/projects/mileway/compare/journey-guide/1-ledger.png",
        "label": "ledger"
      },
      {
        "src": "/projects/mileway/compare/journey-guide/2-instrument.png",
        "label": "instrument"
      },
      {
        "src": "/projects/mileway/compare/journey-guide/3-signal.png",
        "label": "signal"
      },
      {
        "src": "/projects/mileway/compare/journey-guide/4-refined-ember.png",
        "label": "refined ember"
      },
      {
        "src": "/projects/mileway/compare/journey-guide/5-paper.png",
        "label": "paper"
      }
    ],
    "live-drive": [
      {
        "src": "/projects/mileway/compare/live-drive/1-ledger.png",
        "label": "ledger"
      },
      {
        "src": "/projects/mileway/compare/live-drive/2-instrument.png",
        "label": "instrument"
      },
      {
        "src": "/projects/mileway/compare/live-drive/3-signal.png",
        "label": "signal"
      },
      {
        "src": "/projects/mileway/compare/live-drive/4-refined-ember.png",
        "label": "refined ember"
      },
      {
        "src": "/projects/mileway/compare/live-drive/5-paper.png",
        "label": "paper"
      }
    ],
    "saved-tracks": [
      {
        "src": "/projects/mileway/compare/saved-tracks/1-ledger.png",
        "label": "ledger"
      },
      {
        "src": "/projects/mileway/compare/saved-tracks/2-instrument.png",
        "label": "instrument"
      },
      {
        "src": "/projects/mileway/compare/saved-tracks/3-signal.png",
        "label": "signal"
      },
      {
        "src": "/projects/mileway/compare/saved-tracks/4-refined-ember.png",
        "label": "refined ember"
      },
      {
        "src": "/projects/mileway/compare/saved-tracks/5-paper.png",
        "label": "paper"
      }
    ],
    "track-detail": [
      {
        "src": "/projects/mileway/compare/track-detail/1-ledger.png",
        "label": "ledger"
      },
      {
        "src": "/projects/mileway/compare/track-detail/2-instrument.png",
        "label": "instrument"
      },
      {
        "src": "/projects/mileway/compare/track-detail/3-signal.png",
        "label": "signal"
      },
      {
        "src": "/projects/mileway/compare/track-detail/4-refined-ember.png",
        "label": "refined ember"
      },
      {
        "src": "/projects/mileway/compare/track-detail/5-paper.png",
        "label": "paper"
      }
    ],
    "track-evidence": [
      {
        "src": "/projects/mileway/compare/track-evidence/1-ledger.png",
        "label": "ledger"
      },
      {
        "src": "/projects/mileway/compare/track-evidence/2-instrument.png",
        "label": "instrument"
      },
      {
        "src": "/projects/mileway/compare/track-evidence/3-signal.png",
        "label": "signal"
      },
      {
        "src": "/projects/mileway/compare/track-evidence/4-refined-ember.png",
        "label": "refined ember"
      },
      {
        "src": "/projects/mileway/compare/track-evidence/5-paper.png",
        "label": "paper"
      }
    ]
  }
};
