// AUTO-GENERATED by scripts/gen-excelsior.mjs — do not edit by hand.
// Page images live under public/excelsior/pages/<year>/pNNN.webp.
export interface ExcelsiorEdition {
  year: string;
  pages: number;
  /** MANIT's own copy — the canonical source this was rendered from. */
  source: string;
}

export const excelsiorEditions: ExcelsiorEdition[] = [
  {
    "year": "2021",
    "pages": 128,
    "source": "https://flip.manit.ac.in/wp-content/uploads/2024/04/Excelsior-2021.pdf"
  },
  {
    "year": "2020",
    "pages": 124,
    "source": "https://flip.manit.ac.in/wp-content/uploads/2024/04/Excelsior-2020.pdf"
  },
  {
    "year": "2019",
    "pages": 144,
    "source": "https://flip.manit.ac.in/wp-content/uploads/2024/04/Excelsior-2019-.pdf"
  }
];

export const excelsiorPage = (year: string, n: number) =>
  `/excelsior/pages/${year}/p${String(n).padStart(3, "0")}.webp`;
