/**
 * The freshness perimeter's rules, in ONE place.
 *
 * These lived inside freshness.test.ts, which was fine while the test was the
 * only thing that knew them. `/ops` draws the same perimeter as a board a
 * reader can look at, and a dashboard about silent drift that keeps its own
 * private copy of the SLA table would be the joke writing itself: the test
 * could go green on 21 days while the board rendered 45.
 *
 * So the test and the board import the same constants, and neither owns them.
 *
 * scripts/generators.mjs folds SLA_DAYS in as a `slaDays` field on the node
 * that owns each named file (a generator can be read alongside its own
 * deadline instead of a reader cross-referencing two files), reading FROM
 * this table rather than the other way round — this stays the one place the
 * deadlines are actually set.
 */
import { readdirSync, readFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

/** Anything not named below. Generous on purpose: it is not there to nag about
 *  a quiet week, it is there so a generator failing for a MONTH cannot keep
 *  passing for one that works. */
export const MAX_AGE_DAYS = 45;

/**
 * Per-file SLAs, because one blanket threshold is a licence to rot.
 *
 * chessDeep.ts sat 29 days stale under the flat 45-day rule with the suite
 * green and 16 more days of legal silence still to run. The deadline now
 * matches how fast the SOURCE actually moves: a file fed by a live external
 * API on a daily cron has no business being three weeks old, while the Play
 * Store fleet sweep is deliberately slow and rate-limited, so it gets room.
 */
export const SLA_DAYS: Record<string, number> = {
  "chess.ts": 21,
  "chessDeep.ts": 21,
  "weeb.ts": 21,
  "store.ts": 45,
  "history.ts": 21,
  // Live and external, refreshed by refresh-media.yml's weekly cron.
  "writing.ts": 21,
  "anthology.ts": 21,
  // Sibling-kind: only as fresh as refresh-media's Android/KMP checkouts,
  // which is a slower, more failure-prone path than a plain HTTP fetch.
  "systemGraph.ts": 30,
  "repoStats.ts": 30,
  // network but not wired into refresh.mjs's automatic cadence yet — see
  // generators.mjs's note on archive-text having no refresh stage. Generous
  // until it is.
  "archiveText.ts": 45,
  "projectStats.ts": 21,
  // Derived from timeline.ts's own commit date (see gen-lanes.mjs), not a
  // network cadence, so generous.
  "lanes.ts": 45,
};

export const slaFor = (file: string): number => SLA_DAYS[file] ?? MAX_AGE_DAYS;

/**
 * How stale a running `*-app` build's manifest.json may get before its panel
 * (DeviceWall, DeviceMorph, the project pages) renders DEGRADED.
 *
 * Ties to gen-app-manifests.mjs's own cadence: the twin's half runs inside
 * refresh-twin.yml's weekly cron (Monday), the other four are refreshed by
 * hand when their sibling repo is checked out. Three weekly cycles of slack,
 * not the blanket 45-day default — a build panel claiming to show "the commit
 * running in front of you" has less business being a month stale than a
 * hand-curated prose section does.
 */
export const APP_MANIFEST_SLA_DAYS = 21;

/**
 * Every `src/data/**\/*.ts` (recursive, tests excluded) whose header names
 * itself AUTO-GENERATED. A later generator earns a spot in freshness
 * checking just by writing that word in its header comment — no lane edits
 * this file to register it (M22).
 *
 * `dir` is a parameter (not baked to this module's own folder) so a fixture
 * test can point it at a scratch directory instead of the real src/data.
 */
export function discoverAutoGenerated(dir: string, base: string = dir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...discoverAutoGenerated(full, base));
      continue;
    }
    if (!entry.name.endsWith(".ts") || entry.name.endsWith(".test.ts")) continue;
    if (full === fileURLToPath(import.meta.url)) continue; // this file is hand-authored
    if (readFileSync(full, "utf8").slice(0, 400).includes("AUTO-GENERATED")) {
      out.push(relative(base, full).split(sep).join("/"));
    }
  }
  return out;
}

/**
 * This file is imported client-side (EvidenceChip.tsx, appManifest.ts) for
 * its pure helpers (ageDays, slaFor, stateForAge). Node's fs/path/url APIs
 * do not exist in that bundle, so the discovery below, which only
 * check-freshness.mjs and freshness.test.ts actually consume, must never
 * run as a side effect of merely importing this module in a browser. A
 * bundled-but-uncalled import is harmless; calling fileURLToPath at module
 * scope unconditionally is what shipped a hydration-time crash on every
 * route (self-healing-spec.md#2.2).
 */
const isNode = typeof process !== "undefined" && typeof process.versions?.node === "string";

/**
 * Files whose generator can never carry a `generatedAt`, by design, not by
 * omission: each scans `heavy/` (gitignored) with no committed input to date
 * against, so a wall-clock stamp would fail every day regardless of whether
 * a screenshot changed. See gen-galleries.mjs, gen-compare-sets.mjs,
 * gen-system-graph.mjs (storyMap.ts) and gen-excelsior.mjs's own comments.
 *
 * This is the one list a new generator's own author still has to touch — the
 * rare case a file self-registers via its AUTO-GENERATED header but can
 * never meet the "must carry a stamp" half of that registration.
 */
export const CADENCE_NOT_TRACKED = ["galleries.ts", "compareSets.ts", "storyMap.ts", "excelsior.ts"];

/**
 * The discovered set, plus a floor of every file that ever earned a hand-set
 * SLA_DAYS row: chess.ts says "GENERATED", not "AUTO-GENERATED", so header
 * discovery alone would drop it — a floor built from SLA_DAYS's own keys
 * means the SLA table stays the one place that registration happens, rather
 * than a second list that can drift from it. CADENCE_NOT_TRACKED files are
 * excluded outright: check-freshness.mjs treats MUST_BE_STAMPED membership
 * as "watched even with no stamp at all" (by design — that IS the alarm for
 * a regressing generator), so a file that will never stamp itself has to
 * stay off this list rather than merely earn a soft pass on it.
 */
export const MUST_BE_STAMPED = [
  ...new Set([
    ...(isNode ? discoverAutoGenerated(join(fileURLToPath(import.meta.url), "..")) : []),
    ...Object.keys(SLA_DAYS),
  ]),
].filter((f) => !CADENCE_NOT_TRACKED.includes(f));

export type StampVerdict = "stamped" | "cadence-not-tracked" | "missing";

/**
 * hasStamp: does the file match STAMP_RE. hasSlaRow: is it a key in
 * SLA_DAYS. A file with no SLA row was never promised a cadence, so a
 * missing stamp there is not a regression (the SLA breach alarm itself
 * lives in scripts/check-freshness.mjs, not here — self-healing-spec.md#2.2).
 */
export function stampVerdict(hasStamp: boolean, hasSlaRow: boolean): StampVerdict {
  if (hasStamp) return "stamped";
  return hasSlaRow ? "missing" : "cadence-not-tracked";
}

/**
 * The two stamp shapes generators actually emit.
 *
 * Most write the JSON-ish `"generatedAt": "…"`; store.ts writes a TypeScript
 * const, `export const storeGeneratedAt = "…"`. Knowing only the first hid the
 * largest generated file in the repo (5,150 lines) from the alarm entirely.
 */
export const STAMP_RE = /(?:"generatedAt":|[A-Za-z]*[Gg]eneratedAt\s*=)\s*"(\d{4}-\d{2}-\d{2})/;

/**
 * The rare files whose package.json alias does not follow the kebab-case
 * convention generatorFor derives below — package.json is not owned by this
 * file, so the exception lives here rather than as a rename this lane has no
 * business making. Checked mechanically by ops.test.ts's "names a generator
 * that is a real npm script" against the CURRENT package.json, so a script
 * rename shows up here as a failing test, not a silently dead link.
 */
const GENERATOR_ALIAS: Record<string, string> = {
  "compareSets.ts": "compare",
  "projectStats.ts": "stats",
  // gen-project-stats.mjs writes both projectStats.ts and kmpGraph.ts from
  // one run (generators.mjs's single node lists both as `outputs`) — there
  // is no separate `gen:kmp-graph` script for the derived kebab-case guess
  // to find.
  "kmpGraph.ts": "stats",
  // gen-weeb.mjs writes both weeb.ts and weebTitles.ts from one run; the
  // derived kebab-case guess for the second file ("gen:weeb-titles") has no
  // matching script.
  "weebTitles.ts": "weeb",
  "writing.ts": "loopdown",
};

/** Which generator to run when one of these goes red. Derived from the file
 *  name rather than hand-mapped, so a new generated file is covered on arrival. */
export const generatorFor = (file: string): string =>
  `npm run gen:${GENERATOR_ALIAS[file] ?? file.replace(/\.ts$/, "").replace(/([A-Z])/g, (m) => "-" + m.toLowerCase())}`;

/** Whole days between a `YYYY-MM-DD` stamp and now. */
export function ageDays(stamp: string, now: Date = new Date()): number {
  return Math.floor((now.getTime() - Date.parse(stamp)) / 86_400_000);
}

/**
 * The three states, and why the middle one is the whole point.
 *
 * OK and BROKEN are what GitHub already gives you. DEGRADED — passing,
 * succeeding daily, and quietly aging toward its deadline — is the state every
 * failure this perimeter was built for actually lived in.
 */
export type OpsState = "OK" | "DEGRADED" | "BROKEN";

/** Aging is DEGRADED from two-thirds of the way to the deadline. */
export function stateForAge(age: number, sla: number): OpsState {
  if (age > sla) return "BROKEN";
  if (age >= Math.floor(sla * (2 / 3))) return "DEGRADED";
  return "OK";
}
