import { describe, it, expect } from "vitest";
import { readFileSync, mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
// The SLA table, the stamp shapes and the must-be-stamped list moved to
// freshnessSla.ts so /ops draws this exact perimeter from the same numbers.
// A dashboard about silent drift keeping a private copy of the thresholds
// would be the defect it exists to report.
//
// The per-file SLA-breach assertion itself moved OUT of this file and out of
// `npm test` entirely, into scripts/check-freshness.mjs,
// run only by the doctor (self-healing-spec.md#2.2). It used to fail the whole
// suite, and therefore the refresh gate and the PR gate, the moment ANY one
// file breached its SLA — which is how one stale store.ts withheld every
// other file's fresh data for weeks. What stays here is structural: does the
// stamp still parse, is every MUST_BE_STAMPED file still covered. Those are a
// generator regressing at commit time, which a green CI is the right place
// to catch; staleness is an operational question with an operational answer
// now, not a reason to block a build.
//
// MUST_BE_STAMPED is itself discovery now, not a hand-kept list: every
// src/data/**/*.ts whose header says AUTO-GENERATED, plus every file that
// ever earned a hand-set SLA_DAYS row (freshnessSla.ts's own comment has the
// full reasoning). A file with no SLA row is "cadence not tracked" — never a
// failure here, since it was never promised a cadence to breach.
import {
  MAX_AGE_DAYS,
  MUST_BE_STAMPED,
  SLA_DAYS,
  STAMP_RE,
  discoverAutoGenerated,
  stampVerdict,
} from "./freshnessSla.ts";

/**
 * ROT HAS TO BE LOUD.
 *
 * Almost every generator here promises the same thing, and each one is right
 * on its own terms: if a fetch fails, keep the previous file rather than ship
 * a gap. gen-anthology says it, gen-project-stats says it, gen-chess-stats
 * says it. What none of them says is what happens when the fetch keeps
 * failing — the committed file stays valid, the build stays green, the daily
 * job keeps "succeeding", and the data quietly ages out.
 *
 * That is not hypothetical. On 2026-08-24, with a refresh job running every
 * day at 06:17 UTC, chessDeep.ts was 25 days old and weeb.ts was 19 — and
 * weeb's own page argues that a hand-kept list cannot see the present.
 *
 * So this asserts freshness on anything that timestamps itself. The threshold
 * is deliberately generous: it is not there to nag about a quiet week, it is
 * there so a generator that has been failing for a MONTH cannot keep passing
 * for one that works.
 */
describe("generated data has not quietly aged out", () => {
  const dir = new URL("./", import.meta.url).pathname;
  // Read against MUST_BE_STAMPED itself, not the AUTO-GENERATED header scan:
  // the explicit-list floor exists precisely because chess.ts says
  // "GENERATED by", never "AUTO-GENERATED", so a header-only read would miss
  // its stamp entirely (this bit us once already — see the two-shape note
  // below).
  //
  // Two stamp shapes, because assuming one was a hole big enough to hide the
  // largest generated file in the repo. The JSON-ish `"generatedAt": "..."`
  // is what most generators emit; store.ts emits a TypeScript const,
  // `export const storeGeneratedAt = "..."`. The original pattern only knew
  // the first, so store.ts (5,150 lines) never entered `stamped` and the
  // freshness alarm could not see it at all. It sat 21 days old, unwatched,
  // while this suite stayed green. A file that opts out by accident is
  // exactly what this test exists to prevent, so match both shapes.
  const hasStamp = (file: string) => STAMP_RE.test(readFileSync(join(dir, file), "utf8"));

  it.each(MUST_BE_STAMPED)("%s carries a generatedAt stamp, or is cadence-not-tracked", (file) => {
    const verdict = stampVerdict(hasStamp(file), file in SLA_DAYS);
    expect(
      verdict,
      `${file} lost its generatedAt and carries an SLA_DAYS row — scripts/check-freshness.mjs's ` +
        `SLA alarm cannot see it any more. Restore the stamp in its generator rather than deleting this line.`,
    ).not.toBe("missing");
  });

  /**
   * Break-it (G15): every discovery/verdict rule above needs a fixture that
   * makes it fail, run alongside the assertion it guards.
   */
  describe("discovery and verdict rules (break-it fixtures)", () => {
    it("a fixture AUTO-GENERATED file with an SLA row and no stamp fails", () => {
      const scratch = mkdtempSync(join(tmpdir(), "freshness-fixture-"));
      try {
        writeFileSync(join(scratch, "noStamp.ts"), "// AUTO-GENERATED by fixture — do not edit.\nexport const noStamp = 1;\n");
        const discovered = discoverAutoGenerated(scratch);
        expect(discovered).toContain("noStamp.ts");
        const hasStamp = STAMP_RE.test(readFileSync(join(scratch, "noStamp.ts"), "utf8"));
        expect(stampVerdict(hasStamp, /* hasSlaRow */ true)).toBe("missing");
      } finally {
        rmSync(scratch, { recursive: true, force: true });
      }
    });

    it("removing the stamp from a discovered, SLA-tracked file fails", () => {
      const scratch = mkdtempSync(join(tmpdir(), "freshness-fixture-"));
      try {
        const stampedPath = join(scratch, "wasStamped.ts");
        writeFileSync(stampedPath, '// AUTO-GENERATED by fixture — do not edit.\nexport const generatedAt = "2026-09-24";\n');
        expect(stampVerdict(STAMP_RE.test(readFileSync(stampedPath, "utf8")), true)).toBe("stamped");
        // Regenerate the same file with its stamp stripped, simulating a
        // generator regression.
        writeFileSync(stampedPath, "// AUTO-GENERATED by fixture — do not edit.\nexport const value = 1;\n");
        expect(discoverAutoGenerated(scratch)).toContain("wasStamped.ts");
        expect(stampVerdict(STAMP_RE.test(readFileSync(stampedPath, "utf8")), true)).toBe("missing");
      } finally {
        rmSync(scratch, { recursive: true, force: true });
      }
    });

    it("a stamped file without an SLA row passes as cadence-not-tracked-equivalent (stamped)", () => {
      expect(stampVerdict(true, false)).toBe("stamped");
    });

    it("an unstamped file without an SLA row passes as cadence not tracked, never a failure", () => {
      const scratch = mkdtempSync(join(tmpdir(), "freshness-fixture-"));
      try {
        writeFileSync(join(scratch, "untracked.ts"), "// AUTO-GENERATED by fixture — do not edit.\nexport const untracked = 1;\n");
        expect(discoverAutoGenerated(scratch)).toContain("untracked.ts");
        expect(stampVerdict(false, /* hasSlaRow */ false)).toBe("cadence-not-tracked");
      } finally {
        rmSync(scratch, { recursive: true, force: true });
      }
    });
  });

/**
 * The hand-kept half of the same problem.
 *
 * profile.ts's `recentGrowth` is a curated narrative — "Doori — offline AI +
 * policy engine" is a sentence no API produces — so it cannot be generated.
 * But it is dated, it is labelled RECENT, and on 2026-08-24 its newest entry
 * said Jul 2026 while the live GitHub feed showed pushes from yesterday. A
 * section headed "recently shipped" that stops a month and a half ago says
 * something worse about the site than having no such section.
 *
 * Nothing can auto-write this. What a test CAN do is refuse to let it rot in
 * silence, which is the whole difference between a list that is current and a
 * list that merely was.
 */
describe("the curated 'recent' list is actually recent", () => {
  const MONTHS = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];

  it("has a newest entry inside the freshness window", async () => {
    const { recentGrowth } = (await import("./profile.ts")) as { recentGrowth?: { date: string }[] };
    if (!recentGrowth?.length) return;
    // Dates read like "Jul 2026" or "Jun–Aug 2026"; take the LAST month named.
    const newest = recentGrowth
      .map((e) => {
        const year = /(\d{4})/.exec(e.date)?.[1];
        const months = [...e.date.toLowerCase().matchAll(/(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)/g)].map((m) => MONTHS.indexOf(m[1]));
        if (!year || !months.length) return 0;
        return Date.UTC(Number(year), Math.max(...months), 1);
      })
      .reduce((a, b) => Math.max(a, b), 0);
    expect(newest, "no recentGrowth entry carried a parseable date").toBeGreaterThan(0);
    const ageDays = Math.floor((Date.now() - newest) / 86_400_000);
    expect(
      ageDays,
      `profile.ts's newest recentGrowth entry is ${ageDays} days old. It is the section headed ` +
        `"recently shipped" — nothing can generate it, so it is on a person to add what shipped ` +
        `since. The live /api/github-activity feed beside it is a good prompt for what to write.`,
    ).toBeLessThanOrEqual(MAX_AGE_DAYS + 30);
  });
});
});
