// AUTO-GENERATED by scripts/gen-history.mjs from this repo's own `git log` — do not edit by hand.
// Run `npm run gen:history` to refresh. Bytes here change on every real commit,
// so this generator is NOT in check-generated.mjs's deterministic set (see that
// file's own note on "git commit counts").
export interface HistoryMonth {
  ym: string;
  commits: number;
  insertions: number;
  deletions: number;
  filesChanged: number;
  subjects: string[];
  cumulative: { commits: number; insertions: number; deletions: number };
}
export const historyMonths: HistoryMonth[] = [
  {
    "ym": "2026-06",
    "commits": 19,
    "insertions": 8349,
    "deletions": 377,
    "filesChanged": 355,
    "subjects": [
      "feat(portfolio): redesign + Mileway V19 / Sentry / Trip V2 content refresh",
      "feat(content): add Projects, Open Source & Recent Growth from single source of truth",
      "feat(hub): project detail subpages, auto-galleries, chatbot from single source",
      "feat(ui): alive/futuristic project detail pages",
      "fix(vercel): make chatbot prompt self-contained (cross-dir .ts import broke function build)",
      "fix(ui): make whole project card clickable → opens its subpage"
    ],
    "cumulative": {
      "commits": 19,
      "insertions": 8349,
      "deletions": 377
    }
  },
  {
    "ym": "2026-07",
    "commits": 223,
    "insertions": 64329,
    "deletions": 10428,
    "filesChanged": 1449,
    "subjects": [
      "feat(mileway): refresh case study for V20 (offline AI assistant) + fix repo links",
      "feat: add PaymentsLab project card with screenshots",
      "feat(portfolio): Mileway gallery, shared-infra band, self-updating stats + media",
      "feat(content): fix cross-project content drift + per-project branding",
      "fix(chatbot): sync system-prompt with current project data",
      "feat(readme): add animated hero, badges, fix inflated 3D claim"
    ],
    "cumulative": {
      "commits": 242,
      "insertions": 72678,
      "deletions": 10805
    }
  },
  {
    "ym": "2026-08",
    "commits": 221,
    "insertions": 80423,
    "deletions": 18594,
    "filesChanged": 2884,
    "subjects": [
      "fix(profile): correct three dead links, two module counts, the PR claim",
      "fix(profile): stop pointing at a public career-ops fork (#15)",
      "feat(profile): add cv-siddharth-kmp as a project card (#16)",
      "feat(playground): count who comes through, on a CRDT-safe counter",
      "feat(ui): editorial scroll spine — chapter words, filing rows, giant CTA",
      "feat(writing): Excelsior shelf — the print lineage, as actual magazines"
    ],
    "cumulative": {
      "commits": 463,
      "insertions": 153101,
      "deletions": 29399
    }
  },
  {
    "ym": "2026-09",
    "commits": 40,
    "insertions": 9560,
    "deletions": 2153,
    "filesChanged": 803,
    "subjects": [
      "feat(ci): fail when a committed artifact disagrees with its generator (#58)",
      "fix(gen): widen the drift guard to nine, and catch up two stale artifacts (#59)",
      "feat(ci): automate the twin's drift instead of correcting it by hand (#60)",
      "fix(data): the twin's line count had a second copy, and the first fix missed it (#61)",
      "feat(site): give /ops, /pulse and /playground a shape you can read",
      "feat(ops): the board arrives, and only the alarm keeps moving"
    ],
    "cumulative": {
      "commits": 503,
      "insertions": 162661,
      "deletions": 31552
    }
  }
] as const;
export const historyGeneratedAt = "2026-09-07T08:13:16.788Z";
export const historyFrom = "2026-06";
export const historyTo = "2026-09";
export const totalCommits = 503;
