// AUTO-GENERATED by scripts/gen-project-stats.mjs — do not edit by hand.
// kmp-toolkit's module catalog, which consumer app first substituted each
// module and when (git history of that consumer's own settings.gradle.kts),
// and the repo-level includeBuild spine. Feeds mermaidFromGraph
// (src/lib/mermaidFromGraph.ts). Run `npm run gen:stats` to refresh.
export interface KmpModuleUsage { app: string; firstMonth: string | null }
export interface KmpModule { id: string; usedBy: KmpModuleUsage[] }
export interface KmpConsumer { id: string; label: string }
export interface KmpDependencyEdge { from: string; to: string }
export interface KmpGraph { generatedAt: string; modules: KmpModule[]; consumers: KmpConsumer[]; dependencySpine: KmpDependencyEdge[] }

export const kmpGraph: KmpGraph = {
  "generatedAt": "2026-10-09",
  "modules": [
    {
      "id": "result",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        },
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        },
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        },
        {
          "app": "candidai",
          "firstMonth": "2026-09"
        },
        {
          "app": "portfolio",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "common",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        },
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        },
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        },
        {
          "app": "candidai",
          "firstMonth": "2026-07"
        }
      ]
    },
    {
      "id": "mvi-core",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        },
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        },
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        },
        {
          "app": "candidai",
          "firstMonth": "2026-07"
        }
      ]
    },
    {
      "id": "network",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        },
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        },
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        },
        {
          "app": "candidai",
          "firstMonth": "2026-07"
        },
        {
          "app": "portfolio",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "security",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        },
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        },
        {
          "app": "candidai",
          "firstMonth": "2026-07"
        }
      ]
    },
    {
      "id": "biometric",
      "usedBy": []
    },
    {
      "id": "secure-store",
      "usedBy": []
    },
    {
      "id": "device-integrity",
      "usedBy": []
    },
    {
      "id": "settings",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "auth",
      "usedBy": []
    },
    {
      "id": "netlog",
      "usedBy": []
    },
    {
      "id": "designsystem",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        },
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        },
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        },
        {
          "app": "candidai",
          "firstMonth": "2026-07"
        }
      ]
    },
    {
      "id": "ai",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        },
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        },
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        },
        {
          "app": "candidai",
          "firstMonth": "2026-07"
        }
      ]
    },
    {
      "id": "ai-mlkit",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "designsystem-wallet-gms",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "ai-testing",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        },
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        },
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        },
        {
          "app": "candidai",
          "firstMonth": "2026-09"
        }
      ]
    },
    {
      "id": "llm-chat",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        },
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        },
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        },
        {
          "app": "candidai",
          "firstMonth": "2026-09"
        },
        {
          "app": "portfolio",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "feedback",
      "usedBy": [
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "location",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "app-shell",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "app-shell-location-gms",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "payments-api",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "offline-outbox",
      "usedBy": [
        {
          "app": "doori",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "store",
      "usedBy": []
    },
    {
      "id": "bots-policy",
      "usedBy": [
        {
          "app": "gaddi",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "charts",
      "usedBy": []
    },
    {
      "id": "stripe",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "upi-intent",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "cashfree",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "applepay",
      "usedBy": []
    },
    {
      "id": "googlepay",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "omise",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "razorpay",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "square",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "hosted-webview",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "flutterwave",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "paystack",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "paytm",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "stripe-connect",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "cash",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "nmi",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "peach",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "mobile-money",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "mpesa",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "wallet",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    },
    {
      "id": "xendit",
      "usedBy": [
        {
          "app": "paymentslab-kmp",
          "firstMonth": "2026-10"
        }
      ]
    }
  ],
  "consumers": [
    {
      "id": "doori",
      "label": "Doori"
    },
    {
      "id": "gaddi",
      "label": "Gaddi"
    },
    {
      "id": "paymentslab-kmp",
      "label": "PaymentsLab-KMP"
    },
    {
      "id": "candidai",
      "label": "Candidai"
    },
    {
      "id": "portfolio",
      "label": "Portfolio twin"
    }
  ],
  "dependencySpine": [
    {
      "from": "kmp-build-logic",
      "to": "doori"
    },
    {
      "from": "kmp-toolkit",
      "to": "doori"
    },
    {
      "from": "kmp-build-logic",
      "to": "gaddi"
    },
    {
      "from": "kmp-toolkit",
      "to": "gaddi"
    },
    {
      "from": "kmp-build-logic",
      "to": "paymentslab-kmp"
    },
    {
      "from": "kmp-toolkit",
      "to": "paymentslab-kmp"
    },
    {
      "from": "kmp-build-logic",
      "to": "candidai"
    },
    {
      "from": "kmp-toolkit",
      "to": "candidai"
    },
    {
      "from": "kmp-build-logic",
      "to": "portfolio"
    },
    {
      "from": "kmp-toolkit",
      "to": "portfolio"
    }
  ]
};
