// AUTO-GENERATED by scripts/gen-loopdown-art.mjs, do not edit by hand.
// Source: github.com/darkpandawarrior/the-loopdown (lore/assets/manifest.json)
export type LoopdownArtKind = "cast" | "series";
export type LoopdownArt = {
  id: string;
  kind: LoopdownArtKind;
  src: string; // HEAVY_ASSET_BASE-relative; join with heavy() from lib/assetBase.ts
  alt: string;
  castIds: string[];
  seriesIds: string[];
  width: number;
  height: number;
};
export const loopdownArt: LoopdownArt[] = [
  {
    "id": "doze-the-jailer",
    "kind": "cast",
    "src": "/loopdown/cast/doze-the-jailer.webp",
    "alt": "A jailer studies a glowing stopwatch with its hand almost at the end of the sweep, one palm already on the bolt, unmoved and about to close the door.",
    "castIds": [
      "doze-the-jailer"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "null",
    "kind": "cast",
    "src": "/loopdown/cast/null.webp",
    "alt": "A featureless black figure steps calmly out of a hairline crack in the wall at the worst possible moment, and every professional in the room reacts too late.",
    "castIds": [
      "null"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-archivist",
    "kind": "cast",
    "src": "/loopdown/cast/the-archivist.webp",
    "alt": "A clerk stamps a fresh folder at his desk beside a bank of filing cabinet drawers, smugly certain a properly dated record is the only thing that survives a dispute.",
    "castIds": [
      "the-archivist"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-backlog",
    "kind": "cast",
    "src": "/loopdown/cast/the-backlog.webp",
    "alt": "A many-headed hydra severs one of its own necks with a satisfied snip, two new heads already budding at the stump before the cut lands.",
    "castIds": [
      "the-backlog"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-borrowed-hand",
    "kind": "cast",
    "src": "/loopdown/cast/the-borrowed-hand.webp",
    "alt": "A single vast hand reaches up through a hatch to complete a blueprint, filling in the missing corner with something plausible that was never drawn.",
    "castIds": [
      "the-borrowed-hand"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-concussed-witness",
    "kind": "cast",
    "src": "/loopdown/cast/the-concussed-witness.webp",
    "alt": "A bandaged detective points down a dark alley with total, serene confidence, certain and pointing the wrong way.",
    "castIds": [
      "the-concussed-witness"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-ferryman",
    "kind": "cast",
    "src": "/loopdown/cast/the-ferryman.webp",
    "alt": "A cloaked ferryman poles a laden boat away from a crumbling dock, raising an amber lantern toward a passenger's hand still reaching from the dock across the widening gap.",
    "castIds": [
      "the-ferryman"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-fleet",
    "kind": "cast",
    "src": "/loopdown/cast/the-fleet.webp",
    "alt": "A captain stands clean-handed at the helm pointing at a chart, while a crew of identical rowers strains in unison below deck doing all the actual work.",
    "castIds": [
      "the-fleet"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-messenger",
    "kind": "cast",
    "src": "/loopdown/cast/the-messenger.webp",
    "alt": "A hooded courier holds out a small glowing note while unseen hands drag at his cloak to strike him down for carrying it.",
    "castIds": [
      "the-messenger"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-recomposer",
    "kind": "cast",
    "src": "/loopdown/cast/the-recomposer.webp",
    "alt": "A gremlin perched on a ladder repaints an already-empty room, brush loaded and bored, because nothing had to change for it to redo the work anyway.",
    "castIds": [
      "the-recomposer"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-second-witness",
    "kind": "cast",
    "src": "/loopdown/cast/the-second-witness.webp",
    "alt": "A figure presses both palms flat to a wall in total darkness, eyes shut, one finger lighting up the instant it feels a tremor it cannot locate.",
    "castIds": [
      "the-second-witness"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-understudy",
    "kind": "cast",
    "src": "/loopdown/cast/the-understudy.webp",
    "alt": "A performer stands between two stage doors adjusting a costume that no longer fits the part, a rack of other roles waiting in the dark behind them.",
    "castIds": [
      "the-understudy"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-vault-keeper",
    "kind": "cast",
    "src": "/loopdown/cast/the-vault-keeper.webp",
    "alt": "A guard winces as he turns a key set into a lock built into his own chest, sealing something away from himself as surely as from anyone else.",
    "castIds": [
      "the-vault-keeper"
    ],
    "seriesIds": [],
    "width": 1600,
    "height": 873
  },
  {
    "id": "chain-of-custody",
    "kind": "series",
    "src": "/loopdown/series/chain-of-custody.webp",
    "alt": "A clerk stamps a fresh folder while an unbroken chain of tied, dated folders recedes into the dark behind him, every one still accounted for.",
    "castIds": [
      "the-archivist"
    ],
    "seriesIds": [
      "chain-of-custody"
    ],
    "width": 1600,
    "height": 873
  },
  {
    "id": "crossing-the-schema",
    "kind": "series",
    "src": "/loopdown/series/crossing-the-schema.webp",
    "alt": "A ferryman poles a boat of passengers away from a crumbling shore toward a distant vault door, the crossing visibly one-way on both banks.",
    "castIds": [
      "the-ferryman",
      "the-vault-keeper"
    ],
    "seriesIds": [
      "crossing-the-schema"
    ],
    "width": 1600,
    "height": 873
  },
  {
    "id": "ghosts-in-the-recomposition",
    "kind": "series",
    "src": "/loopdown/series/ghosts-in-the-recomposition.webp",
    "alt": "A gremlin repaints an already-empty room from a ladder, because the room redraws itself whether or not anyone asked it to.",
    "castIds": [
      "the-recomposer"
    ],
    "seriesIds": [
      "ghosts-in-the-recomposition"
    ],
    "width": 1600,
    "height": 873
  },
  {
    "id": "notes-from-the-loop",
    "kind": "series",
    "src": "/loopdown/series/notes-from-the-loop.webp",
    "alt": "A captain charts a course while his crew rows below deck and a many-headed sea serpent keeps pace alongside the hull, always one head ahead.",
    "castIds": [
      "the-fleet",
      "the-backlog"
    ],
    "seriesIds": [
      "notes-from-the-loop"
    ],
    "width": 1600,
    "height": 873
  },
  {
    "id": "one-brain-two-bodies",
    "kind": "series",
    "src": "/loopdown/series/one-brain-two-bodies.webp",
    "alt": "A single performer, split down the middle into two different costumes, holds open two stage doors at once, belonging fully to neither.",
    "castIds": [
      "the-understudy"
    ],
    "seriesIds": [
      "one-brain-two-bodies"
    ],
    "width": 1600,
    "height": 873
  },
  {
    "id": "sensors-who-lie",
    "kind": "series",
    "src": "/loopdown/series/sensors-who-lie.webp",
    "alt": "A bandaged, confident figure points the wrong way down a lamplit alley while a huddle of trusting instruments follow the gesture without question.",
    "castIds": [
      "the-concussed-witness"
    ],
    "seriesIds": [
      "sensors-who-lie"
    ],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-coroutine-court",
    "kind": "series",
    "src": "/loopdown/series/the-coroutine-court.webp",
    "alt": "A courier holds out a small glowing note to a judge whose gavel is already falling, the note the only evidence anyone in the room is looking at.",
    "castIds": [
      "the-messenger"
    ],
    "seriesIds": [
      "the-coroutine-court"
    ],
    "width": 1600,
    "height": 873
  },
  {
    "id": "the-night-shift",
    "kind": "series",
    "src": "/loopdown/series/the-night-shift.webp",
    "alt": "A jailer studies a glowing stopwatch at a cell door while a line of weary night workers wait to make their case before it closes.",
    "castIds": [
      "doze-the-jailer"
    ],
    "seriesIds": [
      "the-night-shift"
    ],
    "width": 1600,
    "height": 873
  }
];

export const loopdownArtGeneratedAt = "2026-09-25";
