// AUTO-GENERATED by scripts/gen-ops.mjs — do not edit by hand.
// The perimeter is scanned from src/data/*.ts stamps against the SLAs in
// freshnessSla.ts; the leverage board is scanned from the sibling KMP repos.
// Run `npm run gen:ops` to refresh.
export const perimeter = [
  {
    "file": "chess.ts",
    "generatedAt": "2026-08-30",
    "slaDays": 21,
    "generator": "npm run gen:chess"
  },
  {
    "file": "chessDeep.ts",
    "generatedAt": "2026-09-03",
    "slaDays": 21,
    "generator": "npm run gen:chess-deep"
  },
  {
    "file": "store.ts",
    "generatedAt": "2026-08-07",
    "slaDays": 45,
    "generator": "npm run gen:store"
  },
  {
    "file": "timeline.ts",
    "generatedAt": "2026-09-03",
    "slaDays": 45,
    "generator": "npm run gen:timeline"
  },
  {
    "file": "weeb.ts",
    "generatedAt": "2026-09-03",
    "slaDays": 21,
    "generator": "npm run gen:weeb"
  }
] as const;

export const leverage = [
  {
    "id": "shared.cmp.feature",
    "modules": 31,
    "repos": [
      "HireSignal",
      "Mileway",
      "PaymentsLab"
    ]
  },
  {
    "id": "shared.android.library",
    "modules": 24,
    "repos": [
      "Mileway",
      "kmp-toolkit"
    ]
  },
  {
    "id": "shared.kmp.library",
    "modules": 18,
    "repos": [
      "HireSignal",
      "Mileway",
      "PaymentsLab"
    ]
  },
  {
    "id": "shared.kmp.compose",
    "modules": 9,
    "repos": [
      "HireSignal",
      "Mileway",
      "PaymentsLab"
    ]
  },
  {
    "id": "shared.android.application",
    "modules": 4,
    "repos": [
      "HireSignal",
      "Mileway",
      "PaymentsLab"
    ]
  },
  {
    "id": "shared.test",
    "modules": 3,
    "repos": [
      "HireSignal",
      "Mileway"
    ]
  },
  {
    "id": "shared.purity",
    "modules": 1,
    "repos": [
      "Kursi"
    ]
  },
  {
    "id": "shared.android.firebase",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.android.lint",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.detekt",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.flavors",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.kmp.pure",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.koin",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.kover",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.ktlint",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.room",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.spotless",
    "modules": 0,
    "repos": []
  }
] as const;

export type Drift = { repo: string; upstream: string; pin: string; behind: number | null; pinnedAt: string | null };
export const drift: Drift[] = [
  {
    "repo": "Mileway",
    "upstream": "kmp-build-logic",
    "pin": "b31574f",
    "behind": 2,
    "pinnedAt": "2026-08-27"
  },
  {
    "repo": "Mileway",
    "upstream": "kmp-toolkit",
    "pin": "774c5c6",
    "behind": 4,
    "pinnedAt": "2026-08-27"
  },
  {
    "repo": "Kursi",
    "upstream": "kmp-build-logic",
    "pin": "b31574f",
    "behind": 2,
    "pinnedAt": "2026-08-27"
  },
  {
    "repo": "Kursi",
    "upstream": "kmp-toolkit",
    "pin": "774c5c6",
    "behind": 4,
    "pinnedAt": "2026-08-27"
  },
  {
    "repo": "PaymentsLab",
    "upstream": "kmp-build-logic",
    "pin": "b31574f",
    "behind": 2,
    "pinnedAt": "2026-08-27"
  },
  {
    "repo": "PaymentsLab",
    "upstream": "kmp-toolkit",
    "pin": "774c5c6",
    "behind": 4,
    "pinnedAt": "2026-08-27"
  },
  {
    "repo": "HireSignal",
    "upstream": "kmp-build-logic",
    "pin": "b31574f",
    "behind": 2,
    "pinnedAt": "2026-08-27"
  },
  {
    "repo": "HireSignal",
    "upstream": "kmp-toolkit",
    "pin": "774c5c6",
    "behind": 4,
    "pinnedAt": "2026-08-27"
  }
];

export const opsGeneratedAt = "2026-09-03";
