// AUTO-GENERATED by scripts/gen-ops.mjs — do not edit by hand.
// The perimeter is scanned from src/data/*.ts stamps against the SLAs in
// freshnessSla.ts; the leverage board is scanned from the sibling KMP repos.
// Run `npm run gen:ops` to refresh.
export const perimeter = [
  {
    "file": "chess.ts",
    "generatedAt": "2026-09-06",
    "slaDays": 21,
    "generator": "npm run gen:chess"
  },
  {
    "file": "chessDeep.ts",
    "generatedAt": "2026-09-08",
    "slaDays": 21,
    "generator": "npm run gen:chess-deep"
  },
  {
    "file": "history.ts",
    "generatedAt": "2026-09-08",
    "slaDays": 21,
    "generator": "npm run gen:history"
  },
  {
    "file": "store.ts",
    "generatedAt": "2026-08-07",
    "slaDays": 45,
    "generator": "npm run gen:store"
  },
  {
    "file": "systemGraph.ts",
    "generatedAt": "2026-09-08",
    "slaDays": 45,
    "generator": "npm run gen:system-graph"
  },
  {
    "file": "timeline.ts",
    "generatedAt": "2026-09-08",
    "slaDays": 45,
    "generator": "npm run gen:timeline"
  },
  {
    "file": "weeb.ts",
    "generatedAt": "2026-09-06",
    "slaDays": 21,
    "generator": "npm run gen:weeb"
  }
] as const;

export const leverage = [
  {
    "id": "shared.cmp.feature",
    "modules": 31,
    "repos": [
      "Candidai",
      "Doori",
      "PaymentsLab-KMP"
    ]
  },
  {
    "id": "shared.android.library",
    "modules": 24,
    "repos": [
      "Doori",
      "kmp-toolkit"
    ]
  },
  {
    "id": "shared.kmp.library",
    "modules": 18,
    "repos": [
      "Candidai",
      "Doori",
      "PaymentsLab-KMP"
    ]
  },
  {
    "id": "shared.kmp.compose",
    "modules": 9,
    "repos": [
      "Candidai",
      "Doori",
      "PaymentsLab-KMP"
    ]
  },
  {
    "id": "shared.android.application",
    "modules": 4,
    "repos": [
      "Candidai",
      "Doori",
      "PaymentsLab-KMP"
    ]
  },
  {
    "id": "shared.test",
    "modules": 3,
    "repos": [
      "Candidai",
      "Doori"
    ]
  },
  {
    "id": "shared.purity",
    "modules": 1,
    "repos": [
      "Gaddi"
    ]
  },
  {
    "id": "shared.android.firebase",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.android.lint",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.detekt",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.flavors",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.kmp.pure",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.koin",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.kover",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.ktlint",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.room",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.spotless",
    "modules": 0,
    "repos": []
  }
] as const;

export type Drift = { repo: string; upstream: string; pin: string; behind: number | null; pinnedAt: string | null };
export const drift: Drift[] = [
  {
    "repo": "Doori",
    "upstream": "kmp-build-logic",
    "pin": "7cfd5c3",
    "behind": 2,
    "pinnedAt": "2026-09-07"
  },
  {
    "repo": "Doori",
    "upstream": "kmp-toolkit",
    "pin": "00b8e0f",
    "behind": 4,
    "pinnedAt": "2026-09-07"
  },
  {
    "repo": "Gaddi",
    "upstream": "kmp-build-logic",
    "pin": "b31574f",
    "behind": 8,
    "pinnedAt": "2026-08-27"
  },
  {
    "repo": "Gaddi",
    "upstream": "kmp-toolkit",
    "pin": "5cbf5dd",
    "behind": 12,
    "pinnedAt": "2026-09-07"
  },
  {
    "repo": "PaymentsLab-KMP",
    "upstream": "kmp-build-logic",
    "pin": "7cfd5c3",
    "behind": 2,
    "pinnedAt": "2026-09-07"
  },
  {
    "repo": "PaymentsLab-KMP",
    "upstream": "kmp-toolkit",
    "pin": "00b8e0f",
    "behind": 4,
    "pinnedAt": "2026-09-07"
  },
  {
    "repo": "kmp-app-template",
    "upstream": "kmp-build-logic",
    "pin": "02c40bf",
    "behind": 4,
    "pinnedAt": "2026-09-07"
  },
  {
    "repo": "kmp-app-template",
    "upstream": "kmp-toolkit",
    "pin": "5cbf5dd",
    "behind": 12,
    "pinnedAt": "2026-09-07"
  },
  {
    "repo": "Candidai",
    "upstream": "kmp-build-logic",
    "pin": "02c40bf",
    "behind": 4,
    "pinnedAt": "2026-09-07"
  },
  {
    "repo": "Candidai",
    "upstream": "kmp-toolkit",
    "pin": "5cbf5dd",
    "behind": 12,
    "pinnedAt": "2026-09-07"
  }
];

export const opsGeneratedAt = "2026-09-08";
