// AUTO-GENERATED by scripts/gen-ops.mjs — do not edit by hand.
// The perimeter is scanned from src/data/*.ts stamps against the SLAs in
// freshnessSla.ts; the leverage board is scanned from the sibling KMP repos.
// Run `npm run gen:ops` to refresh.
export const perimeter = [
  {
    "file": "anthology.ts",
    "generatedAt": "2026-09-24",
    "slaDays": 21,
    "generator": "npm run gen:anthology"
  },
  {
    "file": "archiveText.ts",
    "generatedAt": "2026-09-24",
    "slaDays": 45,
    "generator": "npm run gen:archive-text"
  },
  {
    "file": "chess.ts",
    "generatedAt": "2026-09-24",
    "slaDays": 21,
    "generator": "npm run gen:chess"
  },
  {
    "file": "chessDeep.ts",
    "generatedAt": "2026-09-24",
    "slaDays": 21,
    "generator": "npm run gen:chess-deep"
  },
  {
    "file": "history.ts",
    "generatedAt": "2026-09-23",
    "slaDays": 21,
    "generator": "npm run gen:history"
  },
  {
    "file": "lanes.ts",
    "generatedAt": "2026-09-24",
    "slaDays": 45,
    "generator": "npm run gen:lanes"
  },
  {
    "file": "projectStats.ts",
    "generatedAt": "2026-09-23",
    "slaDays": 21,
    "generator": "npm run gen:stats"
  },
  {
    "file": "repoStats.ts",
    "generatedAt": "2026-09-23",
    "slaDays": 30,
    "generator": "npm run gen:repo-stats"
  },
  {
    "file": "store.ts",
    "generatedAt": "2026-09-24",
    "slaDays": 45,
    "generator": "npm run gen:store"
  },
  {
    "file": "systemGraph.ts",
    "generatedAt": "2026-09-24",
    "slaDays": 30,
    "generator": "npm run gen:system-graph"
  },
  {
    "file": "timeline.ts",
    "generatedAt": "2026-09-23",
    "slaDays": 45,
    "generator": "npm run gen:timeline"
  },
  {
    "file": "weeb.ts",
    "generatedAt": "2026-09-24",
    "slaDays": 21,
    "generator": "npm run gen:weeb"
  },
  {
    "file": "writing.ts",
    "generatedAt": "2026-09-24",
    "slaDays": 21,
    "generator": "npm run gen:loopdown"
  }
] as const;

export const leverage = [
  {
    "id": "shared.cmp.feature",
    "modules": 31,
    "repos": [
      "Candidai",
      "Doori",
      "PaymentsLab-KMP"
    ]
  },
  {
    "id": "shared.kmp.library",
    "modules": 20,
    "repos": [
      "Candidai",
      "Doori",
      "PaymentsLab-KMP"
    ]
  },
  {
    "id": "shared.android.library",
    "modules": 11,
    "repos": [
      "kmp-toolkit"
    ]
  },
  {
    "id": "shared.kmp.compose",
    "modules": 9,
    "repos": [
      "Candidai",
      "Doori",
      "PaymentsLab-KMP"
    ]
  },
  {
    "id": "shared.android.application",
    "modules": 4,
    "repos": [
      "Candidai",
      "Doori",
      "PaymentsLab-KMP"
    ]
  },
  {
    "id": "shared.test",
    "modules": 3,
    "repos": [
      "Candidai",
      "Doori"
    ]
  },
  {
    "id": "shared.purity",
    "modules": 1,
    "repos": [
      "Gaddi"
    ]
  },
  {
    "id": "shared.android.firebase",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.android.lint",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.detekt",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.flavors",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.kmp.pure",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.kmp.test",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.koin",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.kover",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.ktlint",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.room",
    "modules": 0,
    "repos": []
  },
  {
    "id": "shared.spotless",
    "modules": 0,
    "repos": []
  }
] as const;

export type Drift = { repo: string; upstream: string; pin: string; behind: number | null; pinnedAt: string | null };
export const drift: Drift[] = [
  {
    "repo": "Doori",
    "upstream": "kmp-build-logic",
    "pin": "c2d31a0",
    "behind": 4,
    "pinnedAt": "2026-09-22"
  },
  {
    "repo": "Doori",
    "upstream": "kmp-toolkit",
    "pin": "db8ffcc",
    "behind": 13,
    "pinnedAt": "2026-09-22"
  },
  {
    "repo": "Gaddi",
    "upstream": "kmp-build-logic",
    "pin": "c2d31a0",
    "behind": 4,
    "pinnedAt": "2026-09-22"
  },
  {
    "repo": "Gaddi",
    "upstream": "kmp-toolkit",
    "pin": "ce21dce",
    "behind": 11,
    "pinnedAt": "2026-09-23"
  },
  {
    "repo": "PaymentsLab-KMP",
    "upstream": "kmp-build-logic",
    "pin": "c2d31a0",
    "behind": 4,
    "pinnedAt": "2026-09-22"
  },
  {
    "repo": "PaymentsLab-KMP",
    "upstream": "kmp-toolkit",
    "pin": "db8ffcc",
    "behind": 13,
    "pinnedAt": "2026-09-22"
  },
  {
    "repo": "kmp-app-template",
    "upstream": "kmp-build-logic",
    "pin": "1b7f221",
    "behind": 22,
    "pinnedAt": "2026-09-21"
  },
  {
    "repo": "kmp-app-template",
    "upstream": "kmp-toolkit",
    "pin": "2324a3a",
    "behind": 56,
    "pinnedAt": "2026-09-21"
  },
  {
    "repo": "Candidai",
    "upstream": "kmp-build-logic",
    "pin": "c2d31a0",
    "behind": 4,
    "pinnedAt": "2026-09-22"
  },
  {
    "repo": "Candidai",
    "upstream": "kmp-toolkit",
    "pin": "db8ffcc",
    "behind": 13,
    "pinnedAt": "2026-09-22"
  }
];

export const opsGeneratedAt = "2026-09-24";
