// AUTO-GENERATED by scripts/gen-project-stats.mjs — do not edit by hand.
// Numbers are derived from each app repo's settings.gradle.kts + Room DB over
// raw.githubusercontent, plus a local sibling-checkout scan for the KMP
// substitution/adoption fields (candidai's repo is private and can only ever
// be read locally — see the module docstring). candidai/portfolio's own
// composedModules/substitutedModules live in the separate kmpAdoption export
// below, not on projectStats itself — see the module docstring for why.
// Run `npm run gen:stats` to refresh.
export const projectStats = {
  "foundation": {
    "modules": 43,
    "providerModules": 20,
    "conventionPlugins": 18
  },
  "doori": {
    "modules": 36,
    "composedModules": 13,
    "features": 13,
    "cores": 12,
    "dbVersion": 48,
    "screenshots": 372,
    "schemaVersion": 48,
    "substitutedModules": [
      "location",
      "common",
      "offline-outbox",
      "network",
      "mvi-core",
      "result",
      "app-shell",
      "ai",
      "ai-testing",
      "security",
      "settings",
      "llm-chat",
      "designsystem"
    ]
  },
  "paymentslab-kmp": {
    "modules": 17,
    "composedModules": 29,
    "providers": 0,
    "features": 4,
    "cores": 9,
    "gatewaysNative": 15,
    "gatewaysInternal": 1,
    "gatewaysHosted": 44,
    "gatewaysMobileMoney": 7,
    "gatewaysStub": 3,
    "screenshots": 26,
    "substitutedModules": [
      "common",
      "mvi-core",
      "security",
      "network",
      "designsystem",
      "result",
      "ai",
      "ai-testing",
      "llm-chat",
      "payments-api",
      "stripe",
      "upi-intent",
      "cashfree",
      "googlepay",
      "omise",
      "razorpay",
      "square",
      "hosted-webview",
      "flutterwave",
      "paystack",
      "paytm",
      "stripe-connect",
      "cash",
      "nmi",
      "peach",
      "mobile-money",
      "mpesa",
      "wallet",
      "xendit"
    ]
  },
  "gaddi": {
    "modules": 15,
    "screenshots": 61,
    "composedModules": 10,
    "substitutedModules": [
      "mvi-core",
      "common",
      "feedback",
      "bots-policy",
      "network",
      "ai",
      "llm-chat",
      "result",
      "ai-testing",
      "designsystem"
    ]
  }
} as const;
export const projectStatsGeneratedAt = "2026-09-25";
export const kmpAdoption = {
  "candidai": {
    "composedModules": 9,
    "substitutedModules": [
      "common",
      "mvi-core",
      "network",
      "designsystem",
      "ai",
      "security",
      "result",
      "llm-chat",
      "ai-testing"
    ]
  },
  "portfolio": {
    "composedModules": 3,
    "substitutedModules": [
      "network",
      "result",
      "llm-chat"
    ]
  }
} as const;
