// AUTO-GENERATED by scripts/gen-project-stats.mjs — do not edit by hand.
// Numbers are derived from each app repo's settings.gradle.kts + Room DB over
// raw.githubusercontent. Run `npm run gen:stats` to refresh.
export const projectStats = {
  "mileway": {
    "modules": 28,
    "features": 11,
    "cores": 9,
    "dbVersion": 18,
    "screenshots": 131
  },
  "paymentslab": {
    "modules": 35,
    "providers": 19,
    "features": 4,
    "cores": 9,
    "screenshots": 23
  }
} as const;
