// AUTO-GENERATED by scripts/gen-providers.mjs. Do not edit by hand.
// One entry per docs/providers/*.md in the `PaymentsLab` sibling checkout
// (Region/Archetype/Status-shipped headers). Drives GatewayCompare,
// GatewayLab and rails.ts's provider counts; see idea-atlas.md#REC-2.
// Run `npm run gen:providers` to refresh.
//
// A generic redaction note, not a provider-specific one: the same
// discipline that keeps every provider's credentials and PII out of this
// app's own logs (core:security's redaction layer) is why this catalog
// carries archetypes and regions only, never a live credential or endpoint.
export interface Provider {
  slug: string;
  name: string;
  region: string;
  archetype: string;
  archetypeLabel: string;
  status: string;
}

export const generatedAt = "2026-09-20";

export const ARCHETYPES = [
  {
    "id": "native-sdk",
    "label": "Native SDK"
  },
  {
    "id": "hosted-webview",
    "label": "Hosted webview"
  },
  {
    "id": "mobile-money",
    "label": "Mobile money"
  },
  {
    "id": "internal",
    "label": "Internal rail"
  },
  {
    "id": "stub",
    "label": "Stub / KYC-gated"
  },
  {
    "id": "other",
    "label": "Uncategorized"
  }
] as const;

export const providers: Provider[] = [
  {
    "slug": "acceptcard",
    "name": "AcceptCard",
    "region": "Global",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "amole",
    "name": "Amole",
    "region": "Ethiopia",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "araka",
    "name": "Araka",
    "region": "unconfirmed (the provider name alone doesn't specify)",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "areeba",
    "name": "Areeba",
    "region": "Lebanon/Levant",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "asapcards",
    "name": "ASAP Cards",
    "region": "unconfirmed",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "beyonic",
    "name": "Beyonic (+ wallet)",
    "region": "Africa",
    "archetype": "mobile-money",
    "archetypeLabel": "Mobile money",
    "status": "MOCK_MODE"
  },
  {
    "slug": "bkash",
    "name": "bKash",
    "region": "Bangladesh",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "cardnet",
    "name": "CardNet",
    "region": "Caribbean",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "cash",
    "name": "Cash",
    "region": "Global",
    "archetype": "mobile-money",
    "archetypeLabel": "Mobile money",
    "status": "MOCK_MODE"
  },
  {
    "slug": "cashfree-ios",
    "name": "Cashfree on iOS",
    "region": "India",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "SANDBOX_READY"
  },
  {
    "slug": "cashfree",
    "name": "Cashfree",
    "region": "India",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "SANDBOX_READY"
  },
  {
    "slug": "cmi",
    "name": "CMI",
    "region": "Morocco",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "conekta",
    "name": "Conekta",
    "region": "Mexico",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "culqi",
    "name": "Culqi",
    "region": "Peru (LATAM)",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "cybersource",
    "name": "Cybersource",
    "region": "Global",
    "archetype": "stub",
    "archetypeLabel": "Stub / KYC-gated",
    "status": "COMING_SOON"
  },
  {
    "slug": "dotlines",
    "name": "DotLines",
    "region": "Bangladesh",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "easypaisa",
    "name": "Easypaisa",
    "region": "Pakistan",
    "archetype": "mobile-money",
    "archetypeLabel": "Mobile money",
    "status": "MOCK_MODE"
  },
  {
    "slug": "ecocash",
    "name": "EcoCash",
    "region": "Zimbabwe",
    "archetype": "mobile-money",
    "archetypeLabel": "Mobile money",
    "status": "MOCK_MODE"
  },
  {
    "slug": "expresspay",
    "name": "ExpressPay",
    "region": "Ghana",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "factranz",
    "name": "FAC / PowerTranz",
    "region": "Caribbean",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "flutterwave",
    "name": "Flutterwave",
    "region": "Africa",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "googlepay",
    "name": "Google Pay",
    "region": "Global",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "SANDBOX_READY"
  },
  {
    "slug": "hyperpay",
    "name": "HyperPay (+ Payfort/MADA)",
    "region": "MENA",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "ipay88",
    "name": "iPay88",
    "region": "Malaysia",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "jcc",
    "name": "JCC",
    "region": "Cyprus",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "kanoo",
    "name": "Kanoo",
    "region": "Gulf",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "midtrans",
    "name": "Midtrans",
    "region": "Indonesia",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "mobizpay",
    "name": "Mobizpay",
    "region": "Africa",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "mollie",
    "name": "Mollie",
    "region": "EU",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "moncash",
    "name": "MonCash (+ Directpay)",
    "region": "Haiti",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "mpesa",
    "name": "M-Pesa",
    "region": "Kenya/Tanzania",
    "archetype": "mobile-money",
    "archetypeLabel": "Mobile money",
    "status": "MOCK_MODE"
  },
  {
    "slug": "mtnmomo",
    "name": "MTN MoMo",
    "region": "Africa (multi-country)",
    "archetype": "mobile-money",
    "archetypeLabel": "Mobile money",
    "status": "MOCK_MODE"
  },
  {
    "slug": "myfatoorah",
    "name": "MyFatoorah",
    "region": "Kuwait/MENA",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "mypos",
    "name": "myPOS",
    "region": "EU",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "nmi",
    "name": "NMI",
    "region": "Global",
    "archetype": "stub",
    "archetypeLabel": "Stub / KYC-gated",
    "status": "COMING_SOON"
  },
  {
    "slug": "omise-ios",
    "name": "Omise on iOS",
    "region": "SEA",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "omise",
    "name": "Omise",
    "region": "SEA (Thailand)",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "orangemoney",
    "name": "Orange Money",
    "region": "Africa (multi-country)",
    "archetype": "mobile-money",
    "archetypeLabel": "Mobile money",
    "status": "MOCK_MODE"
  },
  {
    "slug": "ozow",
    "name": "Ozow",
    "region": "South Africa",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "paymark",
    "name": "Paymark",
    "region": "New Zealand",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "paymentez",
    "name": "Paymentez",
    "region": "LATAM",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "paypal",
    "name": "PayPal",
    "region": "Global",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "paystack",
    "name": "Paystack",
    "region": "Africa",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "paytmaio",
    "name": "Paytm All-in-One",
    "region": "India",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "payu",
    "name": "PayU (India + LATAM)",
    "region": "India / LATAM",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "payway",
    "name": "PayWay (ABA)",
    "region": "Cambodia",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "peach",
    "name": "Peach Payments",
    "region": "Africa/Global",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "phonepe",
    "name": "PhonePe",
    "region": "India",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "placetopay",
    "name": "PlaceToPay",
    "region": "LATAM",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "plugnpay",
    "name": "Plug'n'Pay / Play",
    "region": "Caribbean",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "razorpay-ios",
    "name": "Razorpay on iOS",
    "region": "India",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "SANDBOX_READY"
  },
  {
    "slug": "razorpay",
    "name": "Razorpay",
    "region": "India",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "SANDBOX_READY"
  },
  {
    "slug": "savvy",
    "name": "Savvy",
    "region": "unconfirmed (the provider name alone suggests an NMI-backed white-label integration)",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "selcom",
    "name": "Selcom",
    "region": "Tanzania",
    "archetype": "stub",
    "archetypeLabel": "Stub / KYC-gated",
    "status": "COMING_SOON"
  },
  {
    "slug": "smartpay",
    "name": "SmartPay (SMPAY)",
    "region": "unconfirmed (the provider name alone doesn't specify)",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "square-ios",
    "name": "Square on iOS",
    "region": "Global",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "square",
    "name": "Square",
    "region": "Global",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "sslcommerz",
    "name": "SSLCommerz",
    "region": "Bangladesh",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "stripe-ios",
    "name": "Stripe on iOS",
    "region": "Global",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "SANDBOX_READY"
  },
  {
    "slug": "stripe",
    "name": "Stripe",
    "region": "Global",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "SANDBOX_READY"
  },
  {
    "slug": "supaghanapay",
    "name": "Supa Ghana Pay",
    "region": "Ghana",
    "archetype": "stub",
    "archetypeLabel": "Stub / KYC-gated",
    "status": "COMING_SOON"
  },
  {
    "slug": "telr",
    "name": "Telr",
    "region": "MENA",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "thiwani",
    "name": "Thiwani",
    "region": "unconfirmed (the provider name alone doesn't specify)",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "truevo",
    "name": "Truevo",
    "region": "EU/Malta",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "twint",
    "name": "TWINT",
    "region": "Switzerland",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "upi-intent",
    "name": "UPI (raw intent)",
    "region": "India",
    "archetype": "other",
    "archetypeLabel": "Uncategorized",
    "status": "SANDBOX_READY"
  },
  {
    "slug": "vistamoney",
    "name": "VistaMoney",
    "region": "LATAM",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "vukapay",
    "name": "VukaPay",
    "region": "Africa",
    "archetype": "mobile-money",
    "archetypeLabel": "Mobile money",
    "status": "MOCK_MODE"
  },
  {
    "slug": "wallet",
    "name": "Wallet",
    "region": "Global",
    "archetype": "internal",
    "archetypeLabel": "Internal rail",
    "status": "SANDBOX_READY"
  },
  {
    "slug": "wave",
    "name": "Wave",
    "region": "Senegal",
    "archetype": "mobile-money",
    "archetypeLabel": "Mobile money",
    "status": "MOCK_MODE"
  },
  {
    "slug": "webxpay",
    "name": "Webxpay",
    "region": "Sri Lanka",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "wipay",
    "name": "WiPay",
    "region": "Caribbean",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "worldpay",
    "name": "Worldpay",
    "region": "Global",
    "archetype": "native-sdk",
    "archetypeLabel": "Native SDK",
    "status": "MOCK_MODE"
  },
  {
    "slug": "woyopay",
    "name": "Woyo Pay",
    "region": "Africa",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  },
  {
    "slug": "xendit",
    "name": "Xendit",
    "region": "Indonesia (DANA/OVO/LinkAja e-wallets)",
    "archetype": "hosted-webview",
    "archetypeLabel": "Hosted webview",
    "status": "MOCK_MODE"
  }
] as const;
