// AUTO-GENERATED by scripts/gen-repo-stats.mjs — do not edit by hand.
// Collected with `vitest list`, which enumerates the suite without running it.
// Run `npm run gen:repo-stats` to refresh.
export const repoStats = {
  "tests": 930,
  "testFiles": 83
} as const;
