// AUTO-GENERATED by scripts/gen-repo-stats.mjs — do not edit by hand.
// Collected with `vitest list`, which enumerates the suite without running it.
// Run `npm run gen:repo-stats` to refresh.
export const repoStats = {
  "tests": 1384,
  "testFiles": 136,
  "kotlinLines": 35670,
  "kotlinFiles": 72,
  "kotlin": "2.4.20",
  "compose": "1.13.0-alpha01",
  "agp": "9.5.0-alpha06",
  "gradle": "9.8.0-rc-2"
} as const;
