// AUTO-GENERATED by scripts/gen-system-graph.mjs — do not edit by hand.
//
// The Storyboard's constellation. NODES' colour/label/target manifest and
// which pairs wire together (EDGES) are curated here in the generator, same
// footing as connections.ts's RELATED_SERIES; x/y is computed by BFS layering
// from "sid" rather than hand-placed, so two labels can no longer land on top
// of each other just because someone picked close-together numbers.
//
// EDGE_KIND says which edges are measured (pulled straight from
// systemGraph.ts's own `runs-here` facts) vs declared (editorial wiring) —
// /map renders them solid vs dashed and its legend explains which is which.
//
// StoryMap.tsx re-exports all three original names, so importers keep their
// old path; the extra EDGE_KIND export is additive.
export type StoryNode = {
  id: string;
  label: string;
  sub?: string;
  x: number; // normalized 0..1
  y: number;
  r: number;
  color: string;
  target: string; // "#hash", external url, or "chat"
};

export const NODES: StoryNode[] = [
  {
    "id": "sid",
    "label": "SID",
    "sub": "prototype → platform",
    "r": 26,
    "color": "#3ddc84",
    "target": "#top",
    "x": 0.5,
    "y": 0.46
  },
  {
    "id": "work",
    "label": "Case studies",
    "sub": "the numbers",
    "r": 15,
    "color": "#3ddc84",
    "target": "#work",
    "x": 0.5,
    "y": 0.24
  },
  {
    "id": "doori",
    "label": "Doori",
    "sub": "5 platforms",
    "r": 14,
    "color": "#3ddc84",
    "target": "#project/doori",
    "x": 0.6128,
    "y": 0.2618
  },
  {
    "id": "gaddi",
    "label": "Gaddi",
    "sub": "live web build",
    "r": 12,
    "color": "#3ddc84",
    "target": "#project/gaddi",
    "x": 0.7033,
    "y": 0.3228
  },
  {
    "id": "paymentslab-kmp",
    "label": "PaymentsLab-KMP",
    "sub": "gateway lab",
    "r": 12,
    "color": "#3ddc84",
    "target": "#project/paymentslab-kmp",
    "x": 0.7535,
    "y": 0.411
  },
  {
    "id": "candidai",
    "label": "Candidai",
    "sub": "25-module KMP",
    "r": 12,
    "color": "#3ddc84",
    "target": "#project/candidai",
    "x": 0.7535,
    "y": 0.509
  },
  {
    "id": "stutter",
    "label": "STUTTER",
    "sub": "time-loop game",
    "r": 12,
    "color": "#3ddc84",
    "target": "#project/stutter",
    "x": 0.7033,
    "y": 0.5972
  },
  {
    "id": "portfolio",
    "label": "Portfolio",
    "sub": "this build, twice",
    "r": 12,
    "color": "#3ddc84",
    "target": "#project/portfolio",
    "x": 0.6128,
    "y": 0.6582
  },
  {
    "id": "sinc-p",
    "label": "SINC-P",
    "sub": "campus platform",
    "r": 12,
    "color": "#3ddc84",
    "target": "#project/sinc-p",
    "x": 0.5,
    "y": 0.68
  },
  {
    "id": "kmp-family",
    "label": "KMP toolkit family",
    "sub": "shared build logic",
    "r": 13,
    "color": "#3ddc84",
    "target": "#project/kmp-family",
    "x": 0.3872,
    "y": 0.6582
  },
  {
    "id": "experience",
    "label": "Experience",
    "r": 11,
    "color": "#5ee6ff",
    "target": "#experience",
    "x": 0.2967,
    "y": 0.5972
  },
  {
    "id": "skills",
    "label": "Skills",
    "r": 11,
    "color": "#5ee6ff",
    "target": "#skills",
    "x": 0.2465,
    "y": 0.509
  },
  {
    "id": "the-loopdown",
    "label": "The Loopdown",
    "sub": "field notes",
    "r": 15,
    "color": "#8f74ff",
    "target": "#loopdown",
    "x": 0.2465,
    "y": 0.411
  },
  {
    "id": "books",
    "label": "Books Before Bros",
    "sub": "the origin blog",
    "r": 13,
    "color": "#f0883e",
    "target": "https://booksbeforebros.wordpress.com/",
    "x": 0.1073,
    "y": 0.3955
  },
  {
    "id": "chat",
    "label": "Ask my AI",
    "sub": "knows all of this",
    "r": 13,
    "color": "#5ee6ff",
    "target": "chat",
    "x": 0.2967,
    "y": 0.3228
  },
  {
    "id": "blueprint",
    "label": "Blueprint Room",
    "sub": "infinite canvas",
    "r": 12,
    "color": "#f0883e",
    "target": "#blueprint",
    "x": 0.3872,
    "y": 0.2618
  }
];

export const EDGES: [string, string][] = [["sid","work"],["sid","doori"],["sid","gaddi"],["sid","paymentslab-kmp"],["sid","candidai"],["sid","stutter"],["sid","portfolio"],["sid","sinc-p"],["sid","kmp-family"],["sid","experience"],["sid","skills"],["sid","the-loopdown"],["sid","chat"],["doori","the-loopdown"],["work","the-loopdown"],["books","the-loopdown"],["doori","gaddi"],["gaddi","paymentslab-kmp"],["paymentslab-kmp","candidai"],["candidai","stutter"],["kmp-family","doori"],["kmp-family","gaddi"],["kmp-family","paymentslab-kmp"],["kmp-family","candidai"],["kmp-family","portfolio"],["chat","the-loopdown"],["chat","work"],["sid","blueprint"],["gaddi","portfolio"],["doori","portfolio"],["paymentslab-kmp","portfolio"],["stutter","portfolio"]];

/** "measured" edges are read straight from systemGraph.ts's own runs-here
 *  facts; "declared" edges are curated wiring — the same distinction
 *  systemGraph.ts's own edges carry, extended to the constellation. */
export const EDGE_KIND: Record<string, "measured" | "declared"> = {
  "sid->work": "declared",
  "sid->doori": "declared",
  "sid->gaddi": "declared",
  "sid->paymentslab-kmp": "declared",
  "sid->candidai": "declared",
  "sid->stutter": "declared",
  "sid->portfolio": "declared",
  "sid->sinc-p": "declared",
  "sid->kmp-family": "declared",
  "sid->experience": "declared",
  "sid->skills": "declared",
  "sid->the-loopdown": "declared",
  "sid->chat": "declared",
  "doori->the-loopdown": "declared",
  "work->the-loopdown": "declared",
  "books->the-loopdown": "declared",
  "doori->gaddi": "declared",
  "gaddi->paymentslab-kmp": "declared",
  "paymentslab-kmp->candidai": "declared",
  "candidai->stutter": "declared",
  "kmp-family->doori": "declared",
  "kmp-family->gaddi": "declared",
  "kmp-family->paymentslab-kmp": "declared",
  "kmp-family->candidai": "declared",
  "kmp-family->portfolio": "declared",
  "chat->the-loopdown": "declared",
  "chat->work": "declared",
  "sid->blueprint": "declared",
  "gaddi->portfolio": "measured",
  "doori->portfolio": "measured",
  "paymentslab-kmp->portfolio": "measured",
  "stutter->portfolio": "measured"
};
