// AUTO-GENERATED by scripts/gen-store.mjs — do not edit by hand.
//
// Shipped Android apps, verified live on the Play Store at generation time.
// Package ids are mined from the applicationId lines in each repo's product
// flavours; anything that does not resolve is dropped rather than shipped as a
// dead link. Run `npm run gen:store` to refresh.
export const storeApps = [
  {
    "id": "io.eka.ekav2",
    "name": "Dice Employee HQ",
    "rating": 4.5,
    "installs": "100K+",
    "url": "https://play.google.com/store/apps/details?id=io.eka.ekav2&hl=en",
    "role": "Technical owner & Product Owner",
    "employer": "Dice.tech"
  },
  {
    "id": "product.clicklabs.jugnoo",
    "name": "Jugnoo",
    "rating": 4.5,
    "installs": "5M+",
    "url": "https://play.google.com/store/apps/details?id=product.clicklabs.jugnoo&hl=en",
    "role": "Android engineer",
    "employer": "Jugnoo"
  },
  {
    "id": "product.clicklabs.jugnoo.driver",
    "name": "Jugnoo Drivers",
    "rating": 4.6,
    "installs": "1M+",
    "url": "https://play.google.com/store/apps/details?id=product.clicklabs.jugnoo.driver&hl=en",
    "role": "Android engineer",
    "employer": "Jugnoo"
  }
] as const;

/**
 * White-label flavours that exist in the repos and are NOT separately published
 * — each client ships under its own package id. Counted, never linked.
 */
export const whiteLabelFlavours = [
  "product.clicklabs.jugnoo.white",
  "product.clicklabs.jugnoo.white.driver",
  "product.customer.tempwl",
  "product.driver.tempwl"
] as const;

export const storeGeneratedAt = "2026-08-07";
