// AUTO-GENERATED by scripts/gen-store.mjs — do not edit by hand.
//
// Package ids mined from the applicationId lines of every wl_* branch in the
// Jugnoo rider and driver repos, then verified against the live Play Store.
// Anything that does not resolve is dropped rather than shipped as a dead link.
// Branch names are deliberately not exported — they are internal.
// Run `npm run gen:store` to refresh.

/** The three apps that get their own card. */
export const storeApps = [
  {
    "id": "io.eka.ekav2",
    "name": "Dice Employee HQ",
    "rating": 4.5,
    "installs": "100K+",
    "url": "https://play.google.com/store/apps/details?id=io.eka.ekav2&hl=en",
    "role": "Technical owner & Product Owner",
    "employer": "Dice.tech"
  },
  {
    "id": "product.clicklabs.jugnoo",
    "name": "Jugnoo",
    "rating": 4.5,
    "installs": "5M+",
    "url": "https://play.google.com/store/apps/details?id=product.clicklabs.jugnoo&hl=en",
    "role": "Android engineer",
    "employer": "Jugnoo"
  },
  {
    "id": "product.clicklabs.jugnoo.driver",
    "name": "Jugnoo Drivers",
    "rating": 4.6,
    "installs": "1M+",
    "url": "https://play.google.com/store/apps/details?id=product.clicklabs.jugnoo.driver&hl=en",
    "role": "Android engineer",
    "employer": "Jugnoo"
  }
] as const;

/**
 * The white-label fleet: client builds of the Jugnoo platform that are still on
 * the Play Store. `setUpByHim` means he authored the commit that introduced
 * that client's applicationId; the rest carry his commits in their history.
 */
export const fleet = [
 {
  "id": "production.smartbikemobility.customer",
  "name": "SmartBike",
  "rating": 3.1,
  "installs": "1M+",
  "url": "https://play.google.com/store/apps/details?id=production.smartbikemobility.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "com.snape",
  "name": "SnapE Cabs",
  "rating": 1.9,
  "installs": "500K+",
  "url": "https://play.google.com/store/apps/details?id=com.snape&hl=en",
  "side": "rider",
  "setUpByHim": true
 },
 {
  "id": "production.ttrides.customer",
  "name": "TT RideShare",
  "rating": 5,
  "installs": "100K+",
  "url": "https://play.google.com/store/apps/details?id=production.ttrides.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.zofeur.customer",
  "name": "Zofeur - Hire a Safe Driver.",
  "rating": 4.8,
  "installs": "100K+",
  "url": "https://play.google.com/store/apps/details?id=production.zofeur.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "com.VivaTaxi",
  "name": "Viva Taxi",
  "rating": 4.2,
  "installs": "100K+",
  "url": "https://play.google.com/store/apps/details?id=com.VivaTaxi&hl=en",
  "side": "rider",
  "setUpByHim": true
 },
 {
  "id": "com.asap.courier",
  "name": "ASAP",
  "rating": 3.7,
  "installs": "100K+",
  "url": "https://play.google.com/store/apps/details?id=com.asap.courier&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.rydecust.customer",
  "name": "Ryde – Book a Ride",
  "rating": 3.1,
  "installs": "100K+",
  "url": "https://play.google.com/store/apps/details?id=production.rydecust.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.togopool.carpool",
  "name": "Togopool: Carpool & Bikepool",
  "rating": 2.9,
  "installs": "100K+",
  "url": "https://play.google.com/store/apps/details?id=production.togopool.carpool&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.qooxy.customer",
  "name": "Qooxy: Livraison à domicile",
  "rating": null,
  "installs": "100K+",
  "url": "https://play.google.com/store/apps/details?id=production.qooxy.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.urban.customer",
  "name": "Urban - Passenger",
  "rating": null,
  "installs": "100K+",
  "url": "https://play.google.com/store/apps/details?id=production.urban.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.urban.driver",
  "name": "Urban Driver - for drivers",
  "rating": null,
  "installs": "100K+",
  "url": "https://play.google.com/store/apps/details?id=production.urban.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.zofeur.driver",
  "name": "Zofeur - Driver App",
  "rating": 4.6,
  "installs": "50K+",
  "url": "https://play.google.com/store/apps/details?id=production.zofeur.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.pickupbarbodas.customer",
  "name": "pickUP Barbados",
  "rating": 4.5,
  "installs": "50K+",
  "url": "https://play.google.com/store/apps/details?id=production.pickupbarbodas.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.rydedrive.driver",
  "name": "Ryde Drive",
  "rating": 3.9,
  "installs": "50K+",
  "url": "https://play.google.com/store/apps/details?id=production.rydedrive.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.customer.bena",
  "name": "1Bena – Food, Delivery & Rides",
  "rating": null,
  "installs": "50K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.bena&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.ttrides.driver",
  "name": "TT RideShare Driver",
  "rating": null,
  "installs": "50K+",
  "url": "https://play.google.com/store/apps/details?id=production.ttrides.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "app.production.delivermett",
  "name": "DeliverMe TT Taxi - Rideshare",
  "rating": 5,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=app.production.delivermett&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "com.hitch",
  "name": "HITCH Bermuda",
  "rating": 4.8,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=com.hitch&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.rio",
  "name": "Rio Cabs",
  "rating": 4.5,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.rio&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.one",
  "name": "1Go",
  "rating": 3.8,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.one&hl=en",
  "side": "rider",
  "setUpByHim": true
 },
 {
  "id": "product.driver.snapecabs",
  "name": "SnapE Driver Partner",
  "rating": 3.8,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.snapecabs&hl=en",
  "side": "driver",
  "setUpByHim": true
 },
 {
  "id": "com.hurryup.driver",
  "name": "HURRY UP CAPTAIN",
  "rating": 3.3,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=com.hurryup.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.customer.dailyecuador",
  "name": "Daily Pasajero: Viaja seguro",
  "rating": 3.2,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.dailyecuador&hl=en",
  "side": "rider",
  "setUpByHim": true
 },
 {
  "id": "product.customer.hola",
  "name": "Hola Taxi Ireland",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.hola&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.hovr.customer",
  "name": "HOVR",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=production.hovr.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.hum.customer",
  "name": "HUM Rideshare",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=production.hum.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.onux",
  "name": "ONUX Cliente",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.onux&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "com.taxiye",
  "name": "Taxiye Passenger",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=com.taxiye&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "com.tryapptivities.pamdriver",
  "name": "Pamdriver: Driver & Delivery",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=com.tryapptivities.pamdriver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.dailyecuador",
  "name": "Daily Conductor: Maneja y gana",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.dailyecuador&hl=en",
  "side": "driver",
  "setUpByHim": true
 },
 {
  "id": "production.hovr.driver",
  "name": "HOVR Driver",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=production.hovr.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.hum.driver",
  "name": "HUM Driver",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=production.hum.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.onux",
  "name": "ONUX Driver",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.onux&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.pickupbarbodas.driver",
  "name": "pickUP Driver",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=production.pickupbarbodas.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.qooxy.driver",
  "name": "Qooxy Agent",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=production.qooxy.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "com.taxiye.driver",
  "name": "Taxiye Driver",
  "rating": null,
  "installs": "10K+",
  "url": "https://play.google.com/store/apps/details?id=com.taxiye.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.customer.jett",
  "name": "Jett :Safe , Affordable rides",
  "rating": 4.8,
  "installs": "5K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.jett&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.nairaxi.customer",
  "name": "NAIRAXI- Ride, Shop, Delivery",
  "rating": 4.2,
  "installs": "5K+",
  "url": "https://play.google.com/store/apps/details?id=production.nairaxi.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "com.hurryup",
  "name": "HURRY UP RIDE",
  "rating": 3.3,
  "installs": "5K+",
  "url": "https://play.google.com/store/apps/details?id=com.hurryup&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.driver.jett",
  "name": "Jett Driver: Drive,Earn",
  "rating": 3.2,
  "installs": "5K+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.jett&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.nawi.customer",
  "name": "NAWI RIDES",
  "rating": null,
  "installs": "5K+",
  "url": "https://play.google.com/store/apps/details?id=production.nawi.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.pikmi.customer",
  "name": "Pikmi",
  "rating": null,
  "installs": "5K+",
  "url": "https://play.google.com/store/apps/details?id=production.pikmi.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.woulib.customer",
  "name": "Woulib",
  "rating": null,
  "installs": "5K+",
  "url": "https://play.google.com/store/apps/details?id=production.woulib.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "driver.production.delivermett",
  "name": "DeliverMe TT Driver",
  "rating": null,
  "installs": "5K+",
  "url": "https://play.google.com/store/apps/details?id=driver.production.delivermett&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "com.VivaDriver.driver",
  "name": "Motoristas moz",
  "rating": null,
  "installs": "5K+",
  "url": "https://play.google.com/store/apps/details?id=com.VivaDriver.driver&hl=en",
  "side": "driver",
  "setUpByHim": true
 },
 {
  "id": "product.driver.rio",
  "name": "Rio Partners",
  "rating": 4.7,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.rio&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.limoz.customer",
  "name": "Limoz Customer",
  "rating": 3.8,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.limoz.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.superapp",
  "name": "Super Rental",
  "rating": 3.6,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.superapp&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.superapp.driver",
  "name": "Super driver!",
  "rating": 3.6,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.superapp.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.customer.driveme",
  "name": "DriveMeApp: Book a Ride",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.driveme&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.adonisOville",
  "name": "Errand Philippines",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.adonisOville&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "com.cabby.customer",
  "name": "Cabby",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=com.cabby.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.choffer.shuttle",
  "name": "Choffer",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.choffer.shuttle&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "com.leiwand.user",
  "name": "Leiwand Taxi",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=com.leiwand.user&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.roda",
  "name": "RODA",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.roda&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.salamtaxi",
  "name": "Salam-Taxi",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.salamtaxi&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.ttcab",
  "name": "TT Cab",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.ttcab&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.customer.yuber",
  "name": "YUBER Taxi",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.yuber&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.driver.driveme",
  "name": "DriveMeApp Driver",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.driveme&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "com.hitch.driver",
  "name": "HITCH Bermuda Driver",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=com.hitch.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.bena",
  "name": "1Bena Driver –Delivery & Rides",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.bena&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.hola",
  "name": "Hola Driver Ireland",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.hola&hl=en",
  "side": "driver",
  "setUpByHim": true
 },
 {
  "id": "com.leiwand.driver",
  "name": "Flinta Driver",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=com.leiwand.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.nairaxi.driver",
  "name": "NAIRAXI DRIVER",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=production.nairaxi.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.pikmi.driver",
  "name": "Pikmi Driver",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=production.pikmi.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.tapp",
  "name": "TAPP Rideshare Driver",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.tapp&hl=en",
  "side": "driver",
  "setUpByHim": true
 },
 {
  "id": "production.woulib.driver",
  "name": "Woulib Chauffeur",
  "rating": null,
  "installs": "1K+",
  "url": "https://play.google.com/store/apps/details?id=production.woulib.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.adonisOville",
  "name": "Errand Driver App",
  "rating": null,
  "installs": "500+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.adonisOville&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.nawi.driver",
  "name": "NAWI DRIVER",
  "rating": null,
  "installs": "500+",
  "url": "https://play.google.com/store/apps/details?id=production.nawi.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.clicklabs.ttcab.driver",
  "name": "TT Cab Driver",
  "rating": null,
  "installs": "500+",
  "url": "https://play.google.com/store/apps/details?id=product.clicklabs.ttcab.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.yuber",
  "name": "YUBER Taxi - Driver",
  "rating": null,
  "installs": "500+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.yuber&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.one",
  "name": "1Drive",
  "rating": 3.8,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.one&hl=en",
  "side": "driver",
  "setUpByHim": true
 },
 {
  "id": "product.customer.angel",
  "name": "Island Transfer",
  "rating": null,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.angel&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.romi.customer",
  "name": "Romi Ride",
  "rating": null,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=production.romi.customer&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "production.redplate.customer.new",
  "name": "InterMetroONE Customer App",
  "rating": null,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=production.redplate.customer.new&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.driver.apilit",
  "name": "Apilit Conductores",
  "rating": null,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.apilit&hl=en",
  "side": "driver",
  "setUpByHim": true
 },
 {
  "id": "product.driver.choffer",
  "name": "Choffer Driver",
  "rating": null,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.choffer&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "com.limoz.driver",
  "name": "Limoz Driver",
  "rating": null,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=com.limoz.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.redplate.driver",
  "name": "InterMetroONE Transporter",
  "rating": null,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=production.redplate.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "production.romi.driver",
  "name": "Romi Driver",
  "rating": null,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=production.romi.driver&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.salamtaxi",
  "name": "Salam-Chauffeur",
  "rating": null,
  "installs": "100+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.salamtaxi&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.customer.dida",
  "name": "Dida Client",
  "rating": null,
  "installs": "50+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.dida&hl=en",
  "side": "rider",
  "setUpByHim": true
 },
 {
  "id": "product.driver.dida",
  "name": "Dida Chauffeur",
  "rating": null,
  "installs": "50+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.dida&hl=en",
  "side": "driver",
  "setUpByHim": true
 },
 {
  "id": "product.driver.roda",
  "name": "RODA Driver",
  "rating": null,
  "installs": "50+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.roda&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.driver.angel",
  "name": "Island Drive",
  "rating": null,
  "installs": "10+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.angel&hl=en",
  "side": "driver",
  "setUpByHim": false
 },
 {
  "id": "product.customer.btaxi",
  "name": "TAXI NEXLA",
  "rating": null,
  "installs": "5+",
  "url": "https://play.google.com/store/apps/details?id=product.customer.btaxi&hl=en",
  "side": "rider",
  "setUpByHim": false
 },
 {
  "id": "product.driver.btaxi",
  "name": "NEXLA DRIVER",
  "rating": null,
  "installs": "5+",
  "url": "https://play.google.com/store/apps/details?id=product.driver.btaxi&hl=en",
  "side": "driver",
  "setUpByHim": false
 }
] as const;

/** Counts behind the fleet, all derived — see scripts/gen-store.mjs. */
export const fleetStats = {
  "branches": 1642,
  "clients": 1223,
  "live": 87,
  "setUpByHim": 13,
  "carryingHisCommits": 80,
  "installFloor": 2920170
} as const;

export const storeGeneratedAt = "2026-08-07";
