// AUTO-GENERATED by scripts/gen-system-graph.mjs — do not edit by hand.
// Every repo, employer, writing series, distribution channel and room/corpus
// surface on this site, and how they measurably or declaredly connect. See the
// generator for what each edge kind means and where it comes from.
// Run `npm run gen:system-graph` to refresh.
export type SystemNodeKind = "repo" | "employer" | "series" | "surface" | "channel";
export interface SystemNode { id: string; kind: SystemNodeKind; label: string }

export type SystemEdgeKind = "includeBuild" | "born-from" | "ships" | "runs-here" | "extracted-from" | "operates";
export type SystemEdgeEvidence = "measured" | "declared";
export interface SystemEdge { from: string; to: string; kind: SystemEdgeKind; evidence: SystemEdgeEvidence; detail?: string; url?: string }

export interface SystemGraph { generatedAt: string; nodes: SystemNode[]; edges: SystemEdge[] }

export const systemGraph: SystemGraph = {
  "generatedAt": "2026-09-05",
  "nodes": [
    {
      "id": "gaddi",
      "kind": "repo",
      "label": "Gaddi"
    },
    {
      "id": "doori",
      "kind": "repo",
      "label": "Doori"
    },
    {
      "id": "paymentslab-kmp",
      "kind": "repo",
      "label": "PaymentsLab-KMP"
    },
    {
      "id": "candidai",
      "kind": "repo",
      "label": "Candidai"
    },
    {
      "id": "portfolio",
      "kind": "repo",
      "label": "Portfolio Twin"
    },
    {
      "id": "stutter",
      "kind": "repo",
      "label": "STUTTER"
    },
    {
      "id": "sinc-p",
      "kind": "repo",
      "label": "SINC-P"
    },
    {
      "id": "kmp-family",
      "kind": "repo",
      "label": "The KMP toolkit family"
    },
    {
      "id": "the-loopdown",
      "kind": "repo",
      "label": "The Loopdown"
    },
    {
      "id": "kmp-build-logic",
      "kind": "repo",
      "label": "kmp-build-logic"
    },
    {
      "id": "kmp-toolkit",
      "kind": "repo",
      "label": "kmp-toolkit"
    },
    {
      "id": "kmp-app-template",
      "kind": "repo",
      "label": "kmp-app-template"
    },
    {
      "id": "career-ops",
      "kind": "repo",
      "label": "career-ops"
    },
    {
      "id": "agent-harness",
      "kind": "repo",
      "label": "agent-harness"
    },
    {
      "id": "dice",
      "kind": "employer",
      "label": "Dice.tech"
    },
    {
      "id": "chain-of-custody",
      "kind": "series",
      "label": "Chain Of Custody"
    },
    {
      "id": "crossing-the-schema",
      "kind": "series",
      "label": "Crossing The Schema"
    },
    {
      "id": "ghosts-in-the-recomposition",
      "kind": "series",
      "label": "Ghosts In The Recomposition"
    },
    {
      "id": "notes-from-the-loop",
      "kind": "series",
      "label": "Notes From The Loop"
    },
    {
      "id": "one-brain-two-bodies",
      "kind": "series",
      "label": "One Brain Two Bodies"
    },
    {
      "id": "sensors-who-lie",
      "kind": "series",
      "label": "Sensors Who Lie"
    },
    {
      "id": "the-coroutine-court",
      "kind": "series",
      "label": "The Coroutine Court"
    },
    {
      "id": "the-night-shift",
      "kind": "series",
      "label": "The Night Shift"
    },
    {
      "id": "/compose",
      "kind": "surface",
      "label": "Compose Playground"
    },
    {
      "id": "/lab",
      "kind": "surface",
      "label": "The Lab Bench"
    },
    {
      "id": "/blueprint",
      "kind": "surface",
      "label": "The Blueprint Room"
    },
    {
      "id": "/map",
      "kind": "surface",
      "label": "The 3D Storyboard"
    },
    {
      "id": "/forge",
      "kind": "surface",
      "label": "The Particle Forge"
    },
    {
      "id": "/terminal",
      "kind": "surface",
      "label": "The Terminal"
    },
    {
      "id": "/chess",
      "kind": "surface",
      "label": "The Board"
    },
    {
      "id": "/weeb",
      "kind": "surface",
      "label": "Weeb Central"
    },
    {
      "id": "channel:f-droid",
      "kind": "channel",
      "label": "F-Droid"
    },
    {
      "id": "channel:github-releases",
      "kind": "channel",
      "label": "GitHub Releases"
    },
    {
      "id": "channel:headless-cli",
      "kind": "channel",
      "label": "Headless CLI"
    }
  ],
  "edges": [
    {
      "from": "doori",
      "to": "sensors-who-lie",
      "kind": "born-from",
      "evidence": "declared",
      "detail": "Built in: Doori's location engine",
      "url": "/loopdown#series-sensors-who-lie"
    },
    {
      "from": "doori",
      "to": "chain-of-custody",
      "kind": "born-from",
      "evidence": "declared",
      "detail": "Built in: Doori's trip data model",
      "url": "/loopdown#series-chain-of-custody"
    },
    {
      "from": "doori",
      "to": "crossing-the-schema",
      "kind": "born-from",
      "evidence": "declared",
      "detail": "Built in: Doori's Room migrations",
      "url": "/loopdown#series-crossing-the-schema"
    },
    {
      "from": "paymentslab-kmp",
      "to": "one-brain-two-bodies",
      "kind": "born-from",
      "evidence": "declared",
      "detail": "Built in: PaymentsLab-KMP's expect/actual split",
      "url": "/loopdown#series-one-brain-two-bodies"
    },
    {
      "from": "the-loopdown",
      "to": "notes-from-the-loop",
      "kind": "born-from",
      "evidence": "declared",
      "detail": "Built in: The Loopdown itself",
      "url": "/loopdown#series-notes-from-the-loop"
    },
    {
      "from": "dice",
      "to": "the-night-shift",
      "kind": "born-from",
      "evidence": "declared",
      "detail": "From: the 50%→95% GPS work",
      "url": "/loopdown#series-the-night-shift"
    },
    {
      "from": "dice",
      "to": "sensors-who-lie",
      "kind": "born-from",
      "evidence": "declared",
      "detail": "Built in: Doori's location engine",
      "url": "/loopdown#series-sensors-who-lie"
    },
    {
      "from": "dice",
      "to": "the-coroutine-court",
      "kind": "born-from",
      "evidence": "declared",
      "detail": "From: the -80% crashes work",
      "url": "/loopdown#series-the-coroutine-court"
    },
    {
      "from": "dice",
      "to": "ghosts-in-the-recomposition",
      "kind": "born-from",
      "evidence": "declared",
      "detail": "From: the ~87% Compose migration",
      "url": "/loopdown#series-ghosts-in-the-recomposition"
    },
    {
      "from": "gaddi",
      "to": "channel:f-droid",
      "kind": "ships",
      "evidence": "measured",
      "detail": "Live in a self-hosted repository. 16.5 MB, signed, with no Google Play Services and no Firebase in the build.",
      "url": "https://darkpandawarrior.github.io/fdroid/repo"
    },
    {
      "from": "gaddi",
      "to": "channel:github-releases",
      "kind": "ships",
      "evidence": "measured",
      "detail": "Signed APK per tag, plus desktop and web builds.",
      "url": "https://github.com/darkpandawarrior/Gaddi/releases"
    },
    {
      "from": "gaddi",
      "to": "channel:headless-cli",
      "kind": "ships",
      "evidence": "measured",
      "detail": "The engine runs with no UI at all. ./gradlew :cli:run simulates 500 games and reports per-seat win rates."
    },
    {
      "from": "doori",
      "to": "channel:f-droid",
      "kind": "ships",
      "evidence": "measured",
      "detail": "Live in a self-hosted repository. 66 MB, signed, tagged NonFreeDep because location and on-device receipt OCR use Google Play Services components.",
      "url": "https://darkpandawarrior.github.io/fdroid/repo"
    },
    {
      "from": "doori",
      "to": "channel:github-releases",
      "kind": "ships",
      "evidence": "measured",
      "detail": "Signed APK per tag, for both the Play flavour and the Google-free one.",
      "url": "https://github.com/darkpandawarrior/Doori/releases"
    },
    {
      "from": "paymentslab-kmp",
      "to": "channel:f-droid",
      "kind": "ships",
      "evidence": "measured",
      "detail": "Live in a self-hosted repository. 33 MB, signed, tagged NonFreeDep and NonFreeNet because integrating real gateway SDKs is the whole point of the app.",
      "url": "https://darkpandawarrior.github.io/fdroid/repo"
    },
    {
      "from": "paymentslab-kmp",
      "to": "channel:github-releases",
      "kind": "ships",
      "evidence": "measured",
      "detail": "Signed APK per tag.",
      "url": "https://github.com/darkpandawarrior/PaymentsLab-KMP/releases"
    },
    {
      "from": "gaddi",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "/kursi-app/index.html"
    },
    {
      "from": "doori",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "/mileway-app/index.html"
    },
    {
      "from": "paymentslab-kmp",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "/paymentslab-app/index.html"
    },
    {
      "from": "stutter",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "/deadlock-app/index.html"
    },
    {
      "from": "/compose",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "site route"
    },
    {
      "from": "/lab",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "site route"
    },
    {
      "from": "/blueprint",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "site route"
    },
    {
      "from": "/map",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "site route"
    },
    {
      "from": "/forge",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "site route"
    },
    {
      "from": "/terminal",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "site route"
    },
    {
      "from": "/chess",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "site route"
    },
    {
      "from": "/weeb",
      "to": "portfolio",
      "kind": "runs-here",
      "evidence": "measured",
      "detail": "site route"
    },
    {
      "from": "dice",
      "to": "doori",
      "kind": "extracted-from",
      "evidence": "declared",
      "detail": "AgentHarness/plans/portfolio-extraction/CAPABILITY-GAP-ROADMAP.md"
    },
    {
      "from": "doori",
      "to": "kmp-toolkit",
      "kind": "extracted-from",
      "evidence": "declared",
      "detail": "AgentHarness/plans/portfolio-extraction/CAPABILITY-GAP-ROADMAP.md"
    },
    {
      "from": "agent-harness",
      "to": "gaddi",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "doori",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "paymentslab-kmp",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "candidai",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "portfolio",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "stutter",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "sinc-p",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "kmp-family",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "the-loopdown",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "kmp-build-logic",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "kmp-toolkit",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "kmp-app-template",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    },
    {
      "from": "agent-harness",
      "to": "career-ops",
      "kind": "operates",
      "evidence": "declared",
      "detail": "AgentHarness reference_all_repos.md"
    }
  ]
};

// The sibling-scanned half of `includeBuild`, kept separate so a run with no
// sibling checkouts on disk can fall back to what was last committed here
// instead of shipping an empty scan as if it were a measured zero.
export const includeBuildPairs = [] as const;
