// AUTO-GENERATED by scripts/gen-weeb.mjs — do not edit by hand.
// Source: data/weeb/*.csv (Notion export) enriched with AniList public GraphQL.
export const weeb = {
  "generatedAt": "2026-09-02",
  "anime": {
    "total": 479,
    "matched": 467,
    "byWatch": {
      "Watching": 5,
      "Completed": 115,
      "Paused": 50,
      "To Watch": 297,
      "Ongoing": 12
    },
    "scoreDist": {
      "3": 4,
      "4": 18,
      "5": 26
    },
    "scored": 48,
    "seasonsOut": 220,
    "seasonsDone": 173,
    "behindCount": 26,
    "pairedCount": 114,
    "unwatchedSeasons": 47,
    "deepestGaps": [
      {
        "name": "Bleach",
        "gap": 14
      },
      {
        "name": "My Hero Academia",
        "gap": 2
      },
      {
        "name": "Bakugan",
        "gap": 2
      },
      {
        "name": "Teasing Master Takagi-san",
        "gap": 2
      },
      {
        "name": "Mob Psycho 100",
        "gap": 2
      },
      {
        "name": "Rent-A-Girlfriend",
        "gap": 2
      },
      {
        "name": "The Devil Is A Part Timer",
        "gap": 2
      },
      {
        "name": "The Daily Life Of The Immortal King",
        "gap": 2
      }
    ],
    "caughtUp": {
      "completed": {
        "n": 83,
        "pct": 97.6
      },
      "paused": {
        "n": 21,
        "pct": 4.8
      },
      "watching": {
        "n": 3,
        "pct": 100
      }
    }
  },
  "manga": {
    "total": 26,
    "byRead": {
      "Completed": 5,
      "Reading": 21
    },
    "chaptersRead": 1924
  },
  "stale": [
    {
      "name": "Grand Blue",
      "title": "Grand Blue Dreaming",
      "romaji": "Grand Blue",
      "english": "Grand Blue Dreaming",
      "sequel": "Grand Blue Dreaming Season 2",
      "year": 2025,
      "status": "FINISHED"
    },
    {
      "name": "Chainsaw Man",
      "title": "Chainsaw Man",
      "romaji": "Chainsaw Man",
      "english": "Chainsaw Man",
      "sequel": "Chainsaw Man – The Movie: Reze Arc",
      "year": 2025,
      "status": "FINISHED"
    },
    {
      "name": "Frieren: Beyond Journey’s End",
      "title": "Sousou no Frieren: ●● no Mahou",
      "romaji": "Sousou no Frieren: ●● no Mahou",
      "english": null,
      "sequel": "Sousou no Frieren: ●● no Mahou Part 2",
      "year": 2025,
      "status": "FINISHED"
    },
    {
      "name": "Undead Unluck",
      "title": "Undead Unluck",
      "romaji": "Undead Unluck",
      "english": "Undead Unluck",
      "sequel": "Undead Unluck: Winter Arc",
      "year": 2025,
      "status": "FINISHED"
    },
    {
      "name": "I Was Reincarnated As The 7th Prince So I Can Take My Time Perfecting My Magical Ability",
      "title": "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability",
      "romaji": "Tensei Shitara Dai Nana Ouji Datta node, Kimamani Majutsu wo Kiwamemasu",
      "english": "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability",
      "sequel": "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability Season 2",
      "year": 2025,
      "status": "FINISHED"
    },
    {
      "name": "Tower Of God",
      "title": "Tower of God",
      "romaji": "Kami no Tou: Tower of God",
      "english": "Tower of God",
      "sequel": "Tower of God Season 2",
      "year": 2024,
      "status": "FINISHED"
    },
    {
      "name": "Tsukimichi: Moonlit Fantasy",
      "title": "TSUKIMICHI -Moonlit Fantasy-",
      "romaji": "Tsuki ga Michibiku Isekai Douchuu",
      "english": "TSUKIMICHI -Moonlit Fantasy-",
      "sequel": "TSUKIMICHI -Moonlit Fantasy- Season 2",
      "year": 2024,
      "status": "FINISHED"
    },
    {
      "name": "Ron Kamonohashi's Forbidden Deductions",
      "title": "Ron Kamonohashi's Forbidden Deductions",
      "romaji": "Kamonohashi Ron no Kindan Suiri",
      "english": "Ron Kamonohashi's Forbidden Deductions",
      "sequel": "Ron Kamonohashi’s Forbidden Deductions Season 2",
      "year": 2024,
      "status": "FINISHED"
    },
    {
      "name": "Mashle: Magic and Muscles",
      "title": "MASHLE: MAGIC AND MUSCLES",
      "romaji": "MASHLE",
      "english": "MASHLE: MAGIC AND MUSCLES",
      "sequel": "MASHLE: MAGIC AND MUSCLES Season 2",
      "year": 2024,
      "status": "FINISHED"
    },
    {
      "name": "The Eminence In Shadow",
      "title": "The Eminence in Shadow",
      "romaji": "Kage no Jitsuryokusha ni Naritakute!",
      "english": "The Eminence in Shadow",
      "sequel": "The Eminence in Shadow Season 2",
      "year": 2023,
      "status": "FINISHED"
    },
    {
      "name": "That Time I Got Reincarnated As A Slime",
      "title": "That Time I Got Reincarnated as a Slime",
      "romaji": "Tensei Shitara Slime Datta Ken",
      "english": "That Time I Got Reincarnated as a Slime",
      "sequel": "That Time I Got Reincarnated as a Slime: Visions of Coleus",
      "year": 2023,
      "status": "FINISHED"
    },
    {
      "name": "The Misfit Of Demon King Academyu",
      "title": "The Misfit of Demon King Academy: History’s Strongest Demon King Reincarnates and Goes to School with His Descendants",
      "romaji": "Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou",
      "english": "The Misfit of Demon King Academy: History’s Strongest Demon King Reincarnates and Goes to School with His Descendants",
      "sequel": "The Misfit of Demon King Academy Ⅱ: History's Strongest Demon King Reincarnates and Goes to School with His Descendants",
      "year": 2023,
      "status": "FINISHED"
    },
    {
      "name": "Dead Mount Death Play",
      "title": "Dead Mount Death Play",
      "romaji": "Dead Mount Death Play",
      "english": "Dead Mount Death Play",
      "sequel": "Dead Mount Death Play Part 2",
      "year": 2023,
      "status": "FINISHED"
    },
    {
      "name": "Masamune Kun’s Revenge",
      "title": "Masamune-kun's Revenge",
      "romaji": "Masamune-kun no Revenge",
      "english": "Masamune-kun's Revenge",
      "sequel": "Masamune-kun's Revenge R",
      "year": 2023,
      "status": "FINISHED"
    },
    {
      "name": "Classroom Of The Elite",
      "title": "Classroom of the Elite",
      "romaji": "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e",
      "english": "Classroom of the Elite",
      "sequel": "Classroom of the Elite Season 2",
      "year": 2022,
      "status": "FINISHED"
    },
    {
      "name": "Dr Stone",
      "title": "Dr. STONE",
      "romaji": "Dr. STONE",
      "english": "Dr. STONE",
      "sequel": "Dr. STONE: STONE WARS",
      "year": 2021,
      "status": "FINISHED"
    },
    {
      "name": "The Quintessential Quintuplets",
      "title": "The Quintessential Quintuplets",
      "romaji": "Go-toubun no Hanayome",
      "english": "The Quintessential Quintuplets",
      "sequel": "The Quintessential Quintuplets 2",
      "year": 2021,
      "status": "FINISHED"
    },
    {
      "name": "Dogeza: I Tried Asking While Kowtowing",
      "title": "<DOGEZA>I Tried Asking While Kowtowing.",
      "romaji": "Dogeza de Tanondemita",
      "english": "<DOGEZA>I Tried Asking While Kowtowing.",
      "sequel": "Dogeza de Tanondemita: Isekai-hen",
      "year": 2021,
      "status": "FINISHED"
    },
    {
      "name": "ReZero: Starting Life In Another World",
      "title": "Re:ZERO -Starting Life in Another World-",
      "romaji": "Re:Zero kara Hajimeru Isekai Seikatsu",
      "english": "Re:ZERO -Starting Life in Another World-",
      "sequel": "Re:ZERO -Starting Life in Another World- Season 2",
      "year": 2020,
      "status": "FINISHED"
    },
    {
      "name": "Kaguya Sama: Love Is War",
      "title": "Kaguya-sama: Love is War",
      "romaji": "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
      "english": "Kaguya-sama: Love is War",
      "sequel": "Kaguya-sama: Love is War?",
      "year": 2020,
      "status": "FINISHED"
    },
    {
      "name": "Fire Force",
      "title": "Fire Force",
      "romaji": "Enen no Shouboutai",
      "english": "Fire Force",
      "sequel": "Fire Force Season 2",
      "year": 2020,
      "status": "FINISHED"
    },
    {
      "name": "Rascal Does Not Dream Of Bunny Girl Senpai",
      "title": "Rascal Does Not Dream of Bunny Girl Senpai",
      "romaji": "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
      "english": "Rascal Does Not Dream of Bunny Girl Senpai",
      "sequel": "Rascal Does Not Dream of a Dreaming Girl",
      "year": 2019,
      "status": "FINISHED"
    },
    {
      "name": "The Disastrous Life Of Saiki K",
      "title": "The Disastrous Life of Saiki K.",
      "romaji": "Saiki Kusuo no Ψ-nan",
      "english": "The Disastrous Life of Saiki K.",
      "sequel": "The Disastrous Life of Saiki K. Season 2",
      "year": 2018,
      "status": "FINISHED"
    },
    {
      "name": "Konosuba",
      "title": "KONOSUBA -God's blessing on this wonderful world!",
      "romaji": "Kono Subarashii Sekai ni Shukufuku wo!",
      "english": "KONOSUBA -God's blessing on this wonderful world!",
      "sequel": "KONOSUBA -God's blessing on this wonderful world! 2",
      "year": 2017,
      "status": "FINISHED"
    },
    {
      "name": "How To Raise A Boring Girlfriend",
      "title": "Saekano: How to Raise a Boring Girlfriend",
      "romaji": "Saenai Heroine no Sodatekata",
      "english": "Saekano: How to Raise a Boring Girlfriend",
      "sequel": "Saekano: How to Raise a Boring Girlfriend ♭",
      "year": 2017,
      "status": "FINISHED"
    },
    {
      "name": "Blood Blockade Battlefront",
      "title": "Blood Blockade Battlefront",
      "romaji": "Kekkai Sensen",
      "english": "Blood Blockade Battlefront",
      "sequel": "Blood Blockade Battlefront & Beyond",
      "year": 2017,
      "status": "FINISHED"
    },
    {
      "name": "Assassination Classroom",
      "title": "Assassination Classroom",
      "romaji": "Ansatsu Kyoushitsu",
      "english": "Assassination Classroom",
      "sequel": "Assassination Classroom Second Season",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Sakamoto Desu Ga?",
      "title": "Haven't You Heard? I'm Sakamoto",
      "romaji": "Sakamoto desu ga?",
      "english": "Haven't You Heard? I'm Sakamoto",
      "sequel": "Haven't You Heard? I'm Sakamoto: Haven’t You Heard? I was Sakamoto",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Bungo Stray Dogs",
      "title": "Bungo Stray Dogs",
      "romaji": "Bungou Stray Dogs",
      "english": "Bungo Stray Dogs",
      "sequel": "Bungo Stray Dogs 2",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Prison School",
      "title": "Prison School",
      "romaji": "Prison School",
      "english": "Prison School",
      "sequel": "Prison School: Mad Wax",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "My Wife Is The Student Council President",
      "title": "My Wife is the Student Council President",
      "romaji": "Okusama ga Seitokaichou!",
      "english": "My Wife is the Student Council President",
      "sequel": "My Wife is the Student Council President OVA",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Ajin: Demi-Human",
      "title": "AJIN: Demi-Human",
      "romaji": "Ajin",
      "english": "AJIN: Demi-Human",
      "sequel": "AJIN: Demi-Human 2",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Haikyuu",
      "title": "HAIKYU!!",
      "romaji": "Haikyuu!!",
      "english": "HAIKYU!!",
      "sequel": "HAIKYU!! 2nd Season",
      "year": 2015,
      "status": "FINISHED"
    },
    {
      "name": "Beyond The Boundary",
      "title": "Beyond the Boundary",
      "romaji": "Kyoukai no Kanata",
      "english": "Beyond the Boundary",
      "sequel": "Beyond the Boundary -I'LL BE HERE-: Future",
      "year": 2015,
      "status": "FINISHED"
    },
    {
      "name": "Noragami",
      "title": "Noragami",
      "romaji": "Noragami",
      "english": "Noragami",
      "sequel": "Noragami Aragoto",
      "year": 2015,
      "status": "FINISHED"
    },
    {
      "name": "Highschool DxD",
      "title": "High School DxD",
      "romaji": "High School DxD",
      "english": "High School DxD",
      "sequel": "High School DxD NEW",
      "year": 2013,
      "status": "FINISHED"
    },
    {
      "name": "Nisemonogatari",
      "title": "Nisemonogatari",
      "romaji": "Nisemonogatari",
      "english": "Nisemonogatari",
      "sequel": "Monogatari Series Second Season",
      "year": 2013,
      "status": "FINISHED"
    },
    {
      "name": "Love, Chunibyo & Other Delusions",
      "title": "Love, Chunibyo & Other Delusions",
      "romaji": "Chuunibyou demo Koi ga Shitai!",
      "english": "Love, Chunibyo & Other Delusions",
      "sequel": "Love, Chunibyo & Other Delusions: Glimmering...Explosive Festival (Slapstick Noel)",
      "year": 2013,
      "status": "FINISHED"
    },
    {
      "name": "Stein’s;Gate",
      "title": "Steins;Gate",
      "romaji": "Steins;Gate",
      "english": "Steins;Gate",
      "sequel": "Steins;Gate: Egoistic Poriomania",
      "year": 2012,
      "status": "FINISHED"
    },
    {
      "name": "Bakemonogatari",
      "title": "Bakemonogatari",
      "romaji": "Bakemonogatari",
      "english": "Bakemonogatari",
      "sequel": "Nisemonogatari",
      "year": 2012,
      "status": "FINISHED"
    },
    {
      "name": "Highschool Of The Dead",
      "title": "High School of the Dead",
      "romaji": "Gakuen Mokushiroku: HIGHSCHOOL OF THE DEAD",
      "english": "High School of the Dead",
      "sequel": "High School of the Dead: Drifters of the Dead",
      "year": 2011,
      "status": "FINISHED"
    },
    {
      "name": "Nekomonogatari: Black",
      "title": "Nekomonogatari Black",
      "romaji": "Nekomonogatari (Kuro)",
      "english": "Nekomonogatari Black",
      "sequel": "Bakemonogatari",
      "year": 2009,
      "status": "FINISHED"
    },
    {
      "name": "Naruto",
      "title": "Naruto",
      "romaji": "NARUTO",
      "english": "Naruto",
      "sequel": "Naruto: Shippuden",
      "year": 2007,
      "status": "FINISHED"
    },
    {
      "name": "Dragon Ball Z",
      "title": "Dragon Ball Z",
      "romaji": "Dragon Ball Z",
      "english": "Dragon Ball Z",
      "sequel": "Dragon Ball GT",
      "year": 1996,
      "status": "FINISHED"
    },
    {
      "name": "Ranma ½",
      "title": "Ranma ½",
      "romaji": "Ranma 1/2",
      "english": "Ranma ½",
      "sequel": "Ranma ½ (1989)",
      "year": 1989,
      "status": "FINISHED"
    },
    {
      "name": "The World’s Finest Assassin Gets Reincarnated In Another World As An Aristocrat",
      "title": "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
      "romaji": "Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru",
      "english": "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
      "sequel": "Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru 2nd Season",
      "year": null,
      "status": "NOT_YET_RELEASED"
    },
    {
      "name": "Loner Life In Another World",
      "title": "Loner Life in Another World",
      "romaji": "Hitoribocchi no Isekai Kouryaku",
      "english": "Loner Life in Another World",
      "sequel": "Hitoribocchi no Isekai Kouryaku 2nd Season",
      "year": null,
      "status": "NOT_YET_RELEASED"
    },
    {
      "name": "The Wrong Way To Use Healing Magic",
      "title": "The Wrong Way to Use Healing Magic",
      "romaji": "Chiyu Mahou no Machigatta Tsukaikata",
      "english": "The Wrong Way to Use Healing Magic",
      "sequel": "The Wrong Way to Use Healing Magic Season 2",
      "year": null,
      "status": "NOT_YET_RELEASED"
    }
  ],
  "duplicates": [
    {
      "anilistId": 11843,
      "rows": [
        "Daily Life Of Highschool Boys",
        "Daily Lives of Highschool Boys"
      ],
      "english": "Daily Lives of High School Boys",
      "romaji": "Danshi Koukousei no Nichijou"
    },
    {
      "anilistId": 5114,
      "rows": [
        "Fullmetal Alchemist: Brotherhood",
        "FMA Brotherhood"
      ],
      "english": "Fullmetal Alchemist: Brotherhood",
      "romaji": "Hagane no Renkinjutsushi: FULLMETAL ALCHEMIST"
    },
    {
      "anilistId": 171018,
      "rows": [
        "Dan Da Dan",
        "Dandadan"
      ],
      "english": "DAN DA DAN",
      "romaji": "Dandadan"
    },
    {
      "anilistId": 116566,
      "rows": [
        "Akuma Drive",
        "Akudama Drive"
      ],
      "english": "Akudama Drive",
      "romaji": "Akudama Drive"
    },
    {
      "anilistId": 99629,
      "rows": [
        "Angels of Death",
        "Angel of Slaughter"
      ],
      "english": "Angels of Death",
      "romaji": "Satsuriku no Tenshi"
    },
    {
      "anilistId": 114232,
      "rows": [
        "Hige Wo Soru",
        "Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway"
      ],
      "english": "Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway",
      "romaji": "Hige wo Soru. Soshite Joshikousei wo Hirou."
    }
  ],
  "divergence": {
    "n": 48,
    "top": [
      {
        "name": "Boruto: Naruto Next Generations",
        "mine": 5,
        "crowd": 57,
        "delta": 43
      },
      {
        "name": "Platinum End",
        "mine": 5,
        "crowd": 58,
        "delta": 42
      },
      {
        "name": "Ninja Kamui",
        "mine": 5,
        "crowd": 64,
        "delta": 36
      },
      {
        "name": "Highschool DxD",
        "mine": 5,
        "crowd": 69,
        "delta": 31
      },
      {
        "name": "Bakugan",
        "mine": 4,
        "crowd": 53,
        "delta": 27
      },
      {
        "name": "Frieren: Beyond Journey’s End",
        "mine": 5,
        "crowd": 73,
        "delta": 27
      }
    ],
    "bottom": [
      {
        "name": "Takt op. Destiny",
        "mine": 3,
        "crowd": 69,
        "delta": -9
      },
      {
        "name": "Deadman Wonderland",
        "mine": 3,
        "crowd": 67,
        "delta": -7
      },
      {
        "name": "Witchcraft Works",
        "mine": 3,
        "crowd": 67,
        "delta": -7
      },
      {
        "name": "Monster Musume: Everyday Life With Monster Girls",
        "mine": 3,
        "crowd": 66,
        "delta": -6
      },
      {
        "name": "The Disastrous Life Of Saiki K",
        "mine": 4,
        "crowd": 83,
        "delta": -3
      },
      {
        "name": "Dragon Ball Z",
        "mine": 4,
        "crowd": 80,
        "delta": 0
      }
    ]
  }
} as const;
