// AUTO-GENERATED by scripts/gen-weeb.mjs — do not edit by hand.
// Source: data/weeb/*.csv (Notion export) enriched with AniList public GraphQL.
export const weeb = {
  "generatedAt": "2026-08-05",
  "anime": {
    "total": 154,
    "matched": 145,
    "byWatch": {
      "Watching": 5,
      "Completed": 88,
      "Paused": 46,
      "To Watch": 3,
      "Ongoing": 12
    },
    "scoreDist": {
      "3": 4,
      "4": 18,
      "5": 27
    },
    "scored": 49,
    "seasonsOut": 242,
    "seasonsDone": 195,
    "behindCount": 26,
    "pairedCount": 115,
    "unwatchedSeasons": 47,
    "deepestGaps": [
      {
        "name": "Bleach",
        "gap": 14
      },
      {
        "name": "My Hero Academia",
        "gap": 2
      },
      {
        "name": "Bakugan",
        "gap": 2
      },
      {
        "name": "Teasing Master Takagi-san",
        "gap": 2
      },
      {
        "name": "Mob Psycho 100",
        "gap": 2
      },
      {
        "name": "Rent-A-Girlfriend",
        "gap": 2
      },
      {
        "name": "The Devil Is A Part Timer",
        "gap": 2
      },
      {
        "name": "The Daily Life Of The Immortal King",
        "gap": 2
      }
    ],
    "caughtUp": {
      "completed": {
        "n": 84,
        "pct": 97.6
      },
      "paused": {
        "n": 21,
        "pct": 4.8
      },
      "watching": {
        "n": 3,
        "pct": 100
      }
    }
  },
  "manga": {
    "total": 22,
    "byRead": {
      "Completed": 5,
      "Reading": 17
    },
    "chaptersRead": 1924
  },
  "stale": [
    {
      "name": "Frieren: Beyond Journey’s End",
      "sequel": "Frieren: Beyond Journey’s End Season 2",
      "year": 2026,
      "status": "FINISHED"
    },
    {
      "name": "Grand Blue",
      "sequel": "Grand Blue Dreaming Season 2",
      "year": 2025,
      "status": "FINISHED"
    },
    {
      "name": "Chainsaw Man",
      "sequel": "Chainsaw Man – The Movie: Reze Arc",
      "year": 2025,
      "status": "FINISHED"
    },
    {
      "name": "Undead Unluck",
      "sequel": "Undead Unluck: Winter Arc",
      "year": 2025,
      "status": "FINISHED"
    },
    {
      "name": "I Was Reincarnated As The 7th Prince So I Can Take My Time Perfecting My Magical Ability",
      "sequel": "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability Season 2",
      "year": 2025,
      "status": "FINISHED"
    },
    {
      "name": "Tower Of God",
      "sequel": "Tower of God Season 2",
      "year": 2024,
      "status": "FINISHED"
    },
    {
      "name": "Tsukimichi: Moonlit Fantasy",
      "sequel": "TSUKIMICHI -Moonlit Fantasy- Season 2",
      "year": 2024,
      "status": "FINISHED"
    },
    {
      "name": "Ron Kamonohashi's Forbidden Deductions",
      "sequel": "Ron Kamonohashi’s Forbidden Deductions Season 2",
      "year": 2024,
      "status": "FINISHED"
    },
    {
      "name": "Mashle: Magic and Muscles",
      "sequel": "MASHLE: MAGIC AND MUSCLES Season 2",
      "year": 2024,
      "status": "FINISHED"
    },
    {
      "name": "The Eminence In Shadow",
      "sequel": "The Eminence in Shadow Season 2",
      "year": 2023,
      "status": "FINISHED"
    },
    {
      "name": "That Time I Got Reincarnated As A Slime",
      "sequel": "That Time I Got Reincarnated as a Slime: Visions of Coleus",
      "year": 2023,
      "status": "FINISHED"
    },
    {
      "name": "Dead Mount Death Play",
      "sequel": "Dead Mount Death Play Part 2",
      "year": 2023,
      "status": "FINISHED"
    },
    {
      "name": "Classroom Of The Elite",
      "sequel": "Classroom of the Elite Season 2",
      "year": 2022,
      "status": "FINISHED"
    },
    {
      "name": "Dr Stone",
      "sequel": "Dr. STONE: STONE WARS",
      "year": 2021,
      "status": "FINISHED"
    },
    {
      "name": "The Quintessential Quintuplets",
      "sequel": "The Quintessential Quintuplets 2",
      "year": 2021,
      "status": "FINISHED"
    },
    {
      "name": "Dogeza: I Tried Asking While Kowtowing",
      "sequel": "Dogeza de Tanondemita: Isekai-hen",
      "year": 2021,
      "status": "FINISHED"
    },
    {
      "name": "Kaguya Sama: Love Is War",
      "sequel": "Kaguya-sama: Love is War?",
      "year": 2020,
      "status": "FINISHED"
    },
    {
      "name": "Fire Force",
      "sequel": "Fire Force Season 2",
      "year": 2020,
      "status": "FINISHED"
    },
    {
      "name": "Rascal Does Not Dream Of Bunny Girl Senpai",
      "sequel": "Rascal Does Not Dream of a Dreaming Girl",
      "year": 2019,
      "status": "FINISHED"
    },
    {
      "name": "The Disastrous Life Of Saiki K",
      "sequel": "The Disastrous Life of Saiki K. Season 2",
      "year": 2018,
      "status": "FINISHED"
    },
    {
      "name": "Highschool DxD",
      "sequel": "High School DxD HERO",
      "year": 2018,
      "status": "FINISHED"
    },
    {
      "name": "Konosuba",
      "sequel": "KONOSUBA -God's blessing on this wonderful world! 2",
      "year": 2017,
      "status": "FINISHED"
    },
    {
      "name": "How To Raise A Boring Girlfriend",
      "sequel": "Saekano: How to Raise a Boring Girlfriend ♭",
      "year": 2017,
      "status": "FINISHED"
    },
    {
      "name": "Blood Blockade Battlefront",
      "sequel": "Blood Blockade Battlefront & Beyond",
      "year": 2017,
      "status": "FINISHED"
    },
    {
      "name": "Sakamoto Desu Ga?",
      "sequel": "Haven't You Heard? I'm Sakamoto: Haven’t You Heard? I was Sakamoto",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Bungo Stray Dogs",
      "sequel": "Bungo Stray Dogs 2",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Prison School",
      "sequel": "Prison School: Mad Wax",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "My Wife Is The Student Council President",
      "sequel": "My Wife is the Student Council President OVA",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Ajin: Demi-Human",
      "sequel": "AJIN: Demi-Human 2",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Naruto Shippudden",
      "sequel": "Boruto: Naruto the Movie - The Day Naruto Became Hokage",
      "year": 2016,
      "status": "FINISHED"
    },
    {
      "name": "Haikyuu",
      "sequel": "HAIKYU!! 2nd Season",
      "year": 2015,
      "status": "FINISHED"
    },
    {
      "name": "Beyond The Boundary",
      "sequel": "Beyond the Boundary -I'LL BE HERE-: Future",
      "year": 2015,
      "status": "FINISHED"
    },
    {
      "name": "Noragami",
      "sequel": "Noragami Aragoto",
      "year": 2015,
      "status": "FINISHED"
    },
    {
      "name": "Nisemonogatari",
      "sequel": "Monogatari Series Second Season",
      "year": 2013,
      "status": "FINISHED"
    },
    {
      "name": "Love, Chunibyo & Other Delusions",
      "sequel": "Love, Chunibyo & Other Delusions: Glimmering...Explosive Festival (Slapstick Noel)",
      "year": 2013,
      "status": "FINISHED"
    },
    {
      "name": "Stein’s;Gate",
      "sequel": "Steins;Gate: Egoistic Poriomania",
      "year": 2012,
      "status": "FINISHED"
    },
    {
      "name": "Bakemonogatari",
      "sequel": "Nisemonogatari",
      "year": 2012,
      "status": "FINISHED"
    },
    {
      "name": "Highschool Of The Dead",
      "sequel": "High School of the Dead: Drifters of the Dead",
      "year": 2011,
      "status": "FINISHED"
    },
    {
      "name": "Nekomonogatari: Black",
      "sequel": "Bakemonogatari",
      "year": 2009,
      "status": "FINISHED"
    },
    {
      "name": "Naruto",
      "sequel": "Naruto: Shippuden",
      "year": 2007,
      "status": "FINISHED"
    },
    {
      "name": "Dragon Ball Z",
      "sequel": "Dragon Ball GT",
      "year": 1996,
      "status": "FINISHED"
    },
    {
      "name": "Ranma ½",
      "sequel": "Ranma ½ (1989)",
      "year": 1989,
      "status": "FINISHED"
    },
    {
      "name": "Loner Life In Another World",
      "sequel": "Hitoribocchi no Isekai Kouryaku 2nd Season",
      "year": null,
      "status": "NOT_YET_RELEASED"
    },
    {
      "name": "The Wrong Way To Use Healing Magic",
      "sequel": "The Wrong Way to Use Healing Magic Season 2",
      "year": null,
      "status": "NOT_YET_RELEASED"
    }
  ],
  "divergence": {
    "n": 48,
    "top": [
      {
        "name": "Platinum End",
        "mine": 5,
        "crowd": 58,
        "delta": 42
      },
      {
        "name": "Ninja Kamui",
        "mine": 5,
        "crowd": 64,
        "delta": 36
      },
      {
        "name": "Assassination Classroom",
        "mine": 5,
        "crowd": 68,
        "delta": 32
      },
      {
        "name": "Boruto: Naruto Next Generations",
        "mine": 5,
        "crowd": 71,
        "delta": 29
      },
      {
        "name": "Highschool DxD",
        "mine": 5,
        "crowd": 71,
        "delta": 29
      },
      {
        "name": "Bakugan",
        "mine": 4,
        "crowd": 53,
        "delta": 27
      }
    ],
    "bottom": [
      {
        "name": "Takt op. Destiny",
        "mine": 3,
        "crowd": 69,
        "delta": -9
      },
      {
        "name": "Deadman Wonderland",
        "mine": 3,
        "crowd": 67,
        "delta": -7
      },
      {
        "name": "Witchcraft Works",
        "mine": 3,
        "crowd": 67,
        "delta": -7
      },
      {
        "name": "Monster Musume: Everyday Life With Monster Girls",
        "mine": 3,
        "crowd": 66,
        "delta": -6
      },
      {
        "name": "The Disastrous Life Of Saiki K",
        "mine": 4,
        "crowd": 83,
        "delta": -3
      },
      {
        "name": "Dragon Ball Z",
        "mine": 4,
        "crowd": 80,
        "delta": 0
      }
    ]
  }
} as const;
