// AUTO-GENERATED by scripts/gen-weeb.mjs. Do not edit by hand.
// Matched and scored titles only: name, year, genres, crowd score, his score. No covers.
export const weebTitlesGeneratedAt = "2026-09-26";
export const weebTitles = [
  {
    "name": "The Eminence In Shadow",
    "year": 2022,
    "genres": [
      "Action",
      "Comedy",
      "Fantasy"
    ],
    "crowd": 81,
    "mine": 5
  },
  {
    "name": "Zom 100",
    "year": 2023,
    "genres": [
      "Action",
      "Adventure",
      "Comedy",
      "Horror",
      "Supernatural"
    ],
    "crowd": 76,
    "mine": 5
  },
  {
    "name": "Naruto",
    "year": 2002,
    "genres": [
      "Action",
      "Adventure",
      "Comedy",
      "Drama",
      "Fantasy",
      "Supernatural"
    ],
    "crowd": 80,
    "mine": 4
  },
  {
    "name": "Bleach",
    "year": 2004,
    "genres": [
      "Action",
      "Adventure",
      "Supernatural"
    ],
    "crowd": 79,
    "mine": 5
  },
  {
    "name": "Assassination Classroom",
    "year": 2013,
    "genres": [
      "Action",
      "Comedy",
      "Drama",
      "Supernatural"
    ],
    "crowd": 79,
    "mine": 5
  },
  {
    "name": "Good Luck Girl",
    "year": 2012,
    "genres": [
      "Adventure",
      "Comedy",
      "Supernatural"
    ],
    "crowd": 74,
    "mine": 4
  },
  {
    "name": "My Hero Academia",
    "year": 2016,
    "genres": [
      "Action",
      "Adventure",
      "Comedy"
    ],
    "crowd": 76,
    "mine": 5
  },
  {
    "name": "ReZero: Starting Life In Another World",
    "year": 2016,
    "genres": [
      "Action",
      "Adventure",
      "Drama",
      "Fantasy",
      "Psychological",
      "Romance",
      "Thriller"
    ],
    "crowd": 81,
    "mine": 5
  },
  {
    "name": "Future Diary",
    "year": 2011,
    "genres": [
      "Action",
      "Horror",
      "Mystery",
      "Psychological",
      "Supernatural",
      "Thriller"
    ],
    "crowd": 69,
    "mine": 4
  },
  {
    "name": "Konosuba",
    "year": 2016,
    "genres": [
      "Adventure",
      "Comedy",
      "Ecchi",
      "Fantasy"
    ],
    "crowd": 79,
    "mine": 5
  },
  {
    "name": "The Disastrous Life Of Saiki K",
    "year": 2016,
    "genres": [
      "Comedy",
      "Slice of Life",
      "Supernatural"
    ],
    "crowd": 81,
    "mine": 4
  },
  {
    "name": "Boruto: Naruto Next Generations",
    "year": 2017,
    "genres": [
      "Action",
      "Adventure",
      "Fantasy"
    ],
    "crowd": 56,
    "mine": 5
  },
  {
    "name": "Haikyuu",
    "year": 2014,
    "genres": [
      "Comedy",
      "Drama",
      "Sports"
    ],
    "crowd": 83,
    "mine": 5
  },
  {
    "name": "Dragon Ball Z",
    "year": 1989,
    "genres": [
      "Action",
      "Adventure",
      "Comedy",
      "Fantasy",
      "Supernatural"
    ],
    "crowd": 80,
    "mine": 4
  },
  {
    "name": "Dragon Ball Super",
    "year": 2015,
    "genres": [
      "Action",
      "Adventure",
      "Comedy",
      "Fantasy",
      "Sci-Fi"
    ],
    "crowd": 73,
    "mine": 4
  },
  {
    "name": "Stein’s;Gate",
    "year": 2011,
    "genres": [
      "Drama",
      "Psychological",
      "Sci-Fi",
      "Thriller"
    ],
    "crowd": 89,
    "mine": 5
  },
  {
    "name": "Witchcraft Works",
    "year": 2014,
    "genres": [
      "Action",
      "Fantasy",
      "Supernatural"
    ],
    "crowd": 67,
    "mine": 3
  },
  {
    "name": "Beyond The Boundary",
    "year": 2013,
    "genres": [
      "Action",
      "Drama",
      "Fantasy",
      "Slice of Life",
      "Supernatural"
    ],
    "crowd": 74,
    "mine": 4
  },
  {
    "name": "Monster Musume: Everyday Life With Monster Girls",
    "year": 2015,
    "genres": [
      "Comedy",
      "Ecchi",
      "Fantasy",
      "Romance"
    ],
    "crowd": 65,
    "mine": 3
  },
  {
    "name": "Isekai Quartet",
    "year": 2019,
    "genres": [
      "Comedy",
      "Fantasy",
      "Slice of Life"
    ],
    "crowd": 72,
    "mine": 4
  },
  {
    "name": "Highschool DxD",
    "year": 2012,
    "genres": [
      "Action",
      "Comedy",
      "Ecchi",
      "Fantasy",
      "Romance"
    ],
    "crowd": 69,
    "mine": 5
  },
  {
    "name": "Bakugan",
    "year": 2023,
    "genres": [
      "Action",
      "Fantasy"
    ],
    "crowd": 53,
    "mine": 4
  },
  {
    "name": "Dr Stone",
    "year": 2019,
    "genres": [
      "Action",
      "Adventure",
      "Comedy",
      "Sci-Fi"
    ],
    "crowd": 81,
    "mine": 5
  },
  {
    "name": "Fire Force",
    "year": 2019,
    "genres": [
      "Action",
      "Drama",
      "Sci-Fi",
      "Supernatural"
    ],
    "crowd": 76,
    "mine": 5
  },
  {
    "name": "Food Wars",
    "year": 2015,
    "genres": [
      "Comedy",
      "Ecchi"
    ],
    "crowd": 78,
    "mine": 5
  },
  {
    "name": "Deadman Wonderland",
    "year": 2011,
    "genres": [
      "Action",
      "Drama",
      "Sci-Fi",
      "Supernatural"
    ],
    "crowd": 67,
    "mine": 3
  },
  {
    "name": "Bungo Stray Dogs",
    "year": 2016,
    "genres": [
      "Action",
      "Comedy",
      "Mystery",
      "Supernatural"
    ],
    "crowd": 77,
    "mine": 5
  },
  {
    "name": "No Game No Life",
    "year": 2014,
    "genres": [
      "Adventure",
      "Comedy",
      "Ecchi",
      "Fantasy"
    ],
    "crowd": 77,
    "mine": 5
  },
  {
    "name": "Platinum End",
    "year": 2021,
    "genres": [
      "Drama",
      "Mystery",
      "Psychological",
      "Romance",
      "Supernatural"
    ],
    "crowd": 58,
    "mine": 5
  },
  {
    "name": "Ragna Crimson",
    "year": 2023,
    "genres": [
      "Action",
      "Adventure",
      "Fantasy",
      "Mystery"
    ],
    "crowd": 74,
    "mine": 4
  },
  {
    "name": "Dead Mount Death Play",
    "year": 2021,
    "genres": [
      "Action",
      "Fantasy",
      "Supernatural",
      "Thriller"
    ],
    "crowd": 72,
    "mine": 4
  },
  {
    "name": "Ron Kamonohashi's Forbidden Deductions",
    "year": 2023,
    "genres": [
      "Drama",
      "Mystery"
    ],
    "crowd": 74,
    "mine": 5
  },
  {
    "name": "Wind Breaker",
    "year": 2024,
    "genres": [
      "Action",
      "Comedy",
      "Drama"
    ],
    "crowd": 77,
    "mine": 5
  },
  {
    "name": "Solo Leveling",
    "year": 2024,
    "genres": [
      "Action",
      "Adventure",
      "Fantasy"
    ],
    "crowd": 80,
    "mine": 5
  },
  {
    "name": "Ninja Kamui",
    "year": 2024,
    "genres": [
      "Action",
      "Adventure",
      "Drama",
      "Sci-Fi"
    ],
    "crowd": 64,
    "mine": 5
  },
  {
    "name": "Mashle: Magic and Muscles",
    "year": 2023,
    "genres": [
      "Action",
      "Comedy",
      "Fantasy"
    ],
    "crowd": 76,
    "mine": 4
  },
  {
    "name": "Frieren: Beyond Journey’s End",
    "year": 2023,
    "genres": [
      "Comedy",
      "Fantasy"
    ],
    "crowd": 73,
    "mine": 5
  },
  {
    "name": "Undead Unluck",
    "year": 2023,
    "genres": [
      "Action",
      "Comedy",
      "Sci-Fi",
      "Supernatural"
    ],
    "crowd": 76,
    "mine": 5
  },
  {
    "name": "Dan Da Dan",
    "year": 2024,
    "genres": [
      "Action",
      "Comedy",
      "Drama",
      "Romance",
      "Sci-Fi",
      "Supernatural"
    ],
    "crowd": 83,
    "mine": 5
  },
  {
    "name": "Ranma ½",
    "year": 2024,
    "genres": [
      "Action",
      "Comedy",
      "Ecchi",
      "Romance",
      "Slice of Life"
    ],
    "crowd": 75,
    "mine": 4
  },
  {
    "name": "Masamune Kun’s Revenge",
    "year": 2023,
    "genres": [
      "Comedy",
      "Romance",
      "Slice of Life"
    ],
    "crowd": 66,
    "mine": 4
  },
  {
    "name": "Loner Life In Another World",
    "year": 2024,
    "genres": [
      "Action",
      "Adventure",
      "Fantasy"
    ],
    "crowd": 65,
    "mine": 4
  },
  {
    "name": "The Wrong Way To Use Healing Magic",
    "year": 2024,
    "genres": [
      "Action",
      "Fantasy"
    ],
    "crowd": 75,
    "mine": 4
  },
  {
    "name": "To Be Hero X",
    "year": 2025,
    "genres": [
      "Action",
      "Drama",
      "Mystery",
      "Supernatural"
    ],
    "crowd": 85,
    "mine": 5
  },
  {
    "name": "Rising Of The Shield Hero",
    "year": 2019,
    "genres": [
      "Action",
      "Adventure",
      "Fantasy"
    ],
    "crowd": 76,
    "mine": 5
  },
  {
    "name": "Takt op. Destiny",
    "year": 2021,
    "genres": [
      "Action",
      "Fantasy",
      "Music"
    ],
    "crowd": 69,
    "mine": 3
  },
  {
    "name": "Go Go Loser Ranger!",
    "year": 2023,
    "genres": [
      "Action",
      "Comedy",
      "Drama",
      "Sci-Fi"
    ],
    "crowd": 72,
    "mine": 4
  },
  {
    "name": "I Was Reincarnated As The 7th Prince So I Can Take My Time Perfecting My Magical Ability",
    "year": 2025,
    "genres": [
      "Action",
      "Adventure",
      "Fantasy"
    ],
    "crowd": 73,
    "mine": 4
  }
] as const;
