// AUTO-GENERATED by scripts/gen-loopdown.mjs — do not edit by hand.
// Source: github.com/darkpandawarrior/the-loopdown (data/registry.json)
export type Lesson = { title: string; slug: string; pillar?: string; series?: string; status?: string; created?: string; live?: string; tags?: string[]; };
export type Series = { id: string; title: string; episodes: number };
export type Archive = { title: string; slug: string; form?: string; era?: string; words?: string | number; tags?: string[]; blurb?: string };
export type CastMember = { id: string; appearances: number };
export type Writing = { lessons: Lesson[]; series: Series[]; archive: Archive[]; cast: CastMember[] };
export const writing: Writing = {
  "lessons": [
    {
      "title": "collectAsState is quietly leaking your work",
      "slug": "collectasstate-leak",
      "pillar": "compose-performance",
      "series": "ghosts-in-the-recomposition",
      "status": "ready",
      "created": "2026-07-31",
      "tags": [
        "android",
        "jetpack-compose",
        "flow",
        "lifecycle",
        "collectAsStateWithLifecycle"
      ]
    },
    {
      "title": "expect/actual is the wrong default in KMP",
      "slug": "kmp-expect-actual-default",
      "pillar": "kmp",
      "series": "one-brain-two-bodies",
      "status": "ready",
      "created": "2026-07-29",
      "tags": [
        "kotlin",
        "kmp",
        "multiplatform",
        "architecture",
        "expect-actual",
        "di"
      ]
    },
    {
      "title": "Your LazyColumn recomposes on every scroll",
      "slug": "lazycolumn-recomposition",
      "pillar": "compose-performance",
      "series": "ghosts-in-the-recomposition",
      "status": "ready",
      "created": "2026-07-24",
      "tags": [
        "android",
        "jetpack-compose",
        "recomposition",
        "stability",
        "performance"
      ]
    },
    {
      "title": "The 5-second window that crashes your service",
      "slug": "foreground-service-five-seconds",
      "pillar": "background-execution",
      "series": "the-night-shift",
      "status": "ready",
      "created": "2026-07-22",
      "tags": [
        "android",
        "foreground-service",
        "workmanager",
        "lifecycle",
        "doze"
      ]
    },
    {
      "title": "CancellationException is not an assassin",
      "slug": "coroutine-cancellation-messenger",
      "pillar": "concurrency",
      "series": "the-coroutine-court",
      "status": "ready",
      "created": "2026-07-20",
      "tags": [
        "kotlin",
        "coroutines",
        "cancellation",
        "structured-concurrency",
        "android"
      ]
    },
    {
      "title": "Teaching a phone to disbelieve its own GPS",
      "slug": "mileway-dead-reckoning",
      "pillar": "location",
      "series": "sensors-who-lie",
      "status": "published",
      "created": "2026-07-19",
      "live": "https://dev.to/darkpandawarrior/teaching-a-phone-to-disbelieve-its-own-gps-cip",
      "tags": [
        "android",
        "location",
        "sensor-fusion",
        "dead-reckoning",
        "kalman"
      ]
    }
  ],
  "series": [
    {
      "id": "ghosts-in-the-recomposition",
      "title": "Ghosts In The Recomposition",
      "episodes": 2
    },
    {
      "id": "one-brain-two-bodies",
      "title": "One Brain Two Bodies",
      "episodes": 1
    },
    {
      "id": "sensors-who-lie",
      "title": "Sensors Who Lie",
      "episodes": 1
    },
    {
      "id": "the-coroutine-court",
      "title": "The Coroutine Court",
      "episodes": 1
    },
    {
      "id": "the-night-shift",
      "title": "The Night Shift",
      "episodes": 1
    }
  ],
  "archive": [
    {
      "title": "Chronicles Of An NRE Kid",
      "slug": "chronicles-of-an-nre-kid",
      "form": "essay",
      "era": "personal-essay",
      "words": "1966",
      "tags": [
        "memoir",
        "identity",
        "growing-up"
      ],
      "blurb": "Growing up between two worlds as a Non-Resident kid."
    },
    {
      "title": "College Clubs: Why Aren't You In Any?",
      "slug": "college-clubs",
      "form": "opinion",
      "era": "opinion",
      "words": "363",
      "tags": [
        "opinion",
        "college",
        "soft-skills"
      ],
      "blurb": "The case for joining a society when time, sleep, and parties are all in deficit."
    },
    {
      "title": "CTC: Cost To Company",
      "slug": "ctc-cost-to-company",
      "form": "short-fiction",
      "era": "2069 (written 2020)",
      "words": "1628",
      "tags": [
        "dystopia",
        "satire",
        "world-building",
        "corporate"
      ],
      "blurb": "A 2069 climate dystopia where salary is paid in days of drinkable water. Placement culture as speculative fiction."
    },
    {
      "title": "Deadline",
      "slug": "deadline",
      "form": "short-fiction",
      "era": "2018",
      "words": "3164",
      "tags": [
        "memento-mori",
        "sci-fi",
        "diary",
        "philosophy"
      ],
      "blurb": "Death shows up in a skull t-shirt and hands you six months. A memento-mori meditation wearing a Deadpool costume."
    },
    {
      "title": "Honest College Fests",
      "slug": "honest-college-fests",
      "form": "humor",
      "era": "humor",
      "words": "978",
      "tags": [
        "satire",
        "college",
        "listicle"
      ],
      "blurb": "College fests, described honestly. The gap between the poster and the reality."
    },
    {
      "title": "It's A Doggone Life",
      "slug": "its-a-doggone-life",
      "form": "essay",
      "era": "personal-essay",
      "words": "1371",
      "tags": [
        "memoir",
        "dogs",
        "heart"
      ],
      "blurb": "A dog's-eye life, and everything it teaches."
    },
    {
      "title": "Pointer Games",
      "slug": "pointer-games",
      "form": "short-fiction",
      "era": "campus-lore",
      "words": "1739",
      "tags": [
        "campus-lore",
        "mystery",
        "hinglish",
        "world-building"
      ],
      "blurb": "A midnight call from a legendary dropout, a conspiracy in the exam schedule, and the boogeyman of MANIT."
    },
    {
      "title": "Prophecy #201112003",
      "slug": "prophecy-201112003",
      "form": "short-fiction",
      "era": "campus-lore",
      "words": "1761",
      "tags": [
        "campus-lore",
        "mystery",
        "world-building"
      ],
      "blurb": "A scholar number, a prophecy, and campus mythology."
    },
    {
      "title": "The Loopdown",
      "slug": "the-loopdown-story",
      "form": "short-fiction",
      "era": "2020",
      "words": "1973",
      "tags": [
        "time-loop",
        "sci-fi",
        "world-building",
        "diary"
      ],
      "blurb": "A week that refuses to end. 52 iterations of the same Wednesday — the namesake of this whole repo."
    },
    {
      "title": "The Pun Force",
      "slug": "the-pun-force",
      "form": "humor",
      "era": "humor",
      "words": "627",
      "tags": [
        "puns",
        "meta",
        "comedy",
        "world-building"
      ],
      "blurb": "An origin myth for the pun, narrated by the punniest man alive. The building block of humor, weaponized."
    }
  ],
  "cast": [
    {
      "id": "the-recomposer",
      "appearances": 2
    },
    {
      "id": "the-understudy",
      "appearances": 1
    },
    {
      "id": "doze-the-jailer",
      "appearances": 1
    },
    {
      "id": "the-messenger",
      "appearances": 1
    },
    {
      "id": "the-concussed-witness",
      "appearances": 1
    }
  ]
};
